// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 1907350542b76241 "Blimpy", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * title?: string // Title
 * image?: {src: string, srcSet?: string, alt?: string} // Image
 * link?: string // Link
}} Props

 */
import { routes } from "./chunks/chunk-RHU4XTMM.js";

// virtual:about-button
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/jV4suGbiAYpkERyuATaw/JOTUCp0aC0eIqDgQIvyC/tOMgpIwdN.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	getLoadingLazyAtYPosition,
	Image,
	Link,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";

// /:https://framerusercontent.com/modules/FcBikMkwX6opV2lMiA4d/4tlY6S47lvMXpaqqGaFj/FOYoieLgU.js
import { fontStore } from "unframer";
fontStore.loadFonts([
	"GF;Rethink Sans-600",
	"GF;Rethink Sans-700",
	"GF;Rethink Sans-700italic",
	"GF;Rethink Sans-600italic",
]);
var fonts = [
	{
		explicitInter: true,
		fonts: [
			{
				family: "Rethink Sans",
				openType: true,
				source: "google",
				style: "normal",
				url: "https://fonts.gstatic.com/s/rethinksans/v6/AMODz4SDuXOMCPfdoglY9JQuWHBGG0X45Dmqkr9WCEvmma-aua4.woff2",
				weight: "600",
			},
			{
				family: "Rethink Sans",
				openType: true,
				source: "google",
				style: "normal",
				url: "https://fonts.gstatic.com/s/rethinksans/v6/AMODz4SDuXOMCPfdoglY9JQuWHBGG0X45DmqkoZWCEvmma-aua4.woff2",
				weight: "700",
			},
			{
				family: "Rethink Sans",
				openType: true,
				source: "google",
				style: "italic",
				url: "https://fonts.gstatic.com/s/rethinksans/v6/AMOFz4SDuXOMCPfdoglY9JQEUUK5wyyTfpeth6kSBwrsmI2fqa7iVQ.woff2",
				weight: "700",
			},
			{
				family: "Rethink Sans",
				openType: true,
				source: "google",
				style: "italic",
				url: "https://fonts.gstatic.com/s/rethinksans/v6/AMOFz4SDuXOMCPfdoglY9JQEUUK5wyyTfpeth6kSPgrsmI2fqa7iVQ.woff2",
				weight: "600",
			},
		],
	},
];
var css = [
	`.framer-BIMuU .framer-styles-preset-ei9thp:not(.rich-text-wrapper), .framer-BIMuU .framer-styles-preset-ei9thp.rich-text-wrapper p { --framer-font-family: "Rethink Sans", "Rethink Sans Placeholder", sans-serif; --framer-font-family-bold: "Rethink Sans", "Rethink Sans Placeholder", sans-serif; --framer-font-family-bold-italic: "Rethink Sans", "Rethink Sans Placeholder", sans-serif; --framer-font-family-italic: "Rethink Sans", "Rethink Sans Placeholder", sans-serif; --framer-font-open-type-features: 'blwf' on, 'cv09' on, 'cv03' on, 'cv04' on, 'cv11' on; --framer-font-size: 16px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 600; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 600; --framer-letter-spacing: 0px; --framer-line-height: 1.2em; --framer-paragraph-spacing: 20px; --framer-text-alignment: start; --framer-text-color: var(--token-d0efb30f-1ca4-4318-a615-3c27c4e89f33, #ff1f00); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: uppercase; }`,
];
var className = "framer-BIMuU";

// /:https://framerusercontent.com/modules/jV4suGbiAYpkERyuATaw/JOTUCp0aC0eIqDgQIvyC/tOMgpIwdN.js
var enabledGestures = {
	oX19YTKHw: {
		hover: true,
	},
};
var serializationHash = "framer-oIyWP";
var variantClassNames = {
	oX19YTKHw: "framer-v-1e3oia4",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.1,
	delay: 0,
	duration: 0.5,
	type: "spring",
};
var toResponsiveImage = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider
			suppressHydrationWarning={true}
			value={contextValue}
		>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var getProps = ({ height, id, image, link, title, width, ...props }) => {
	return {
		...props,
		GI5Q9ZBz8: image ??
			props.GI5Q9ZBz8 ?? {
				alt: "Icon",
				pixelHeight: 20,
				pixelWidth: 20,
				src: "https://framerusercontent.com/images/ne7C5pcflqjINmq1pB6QEuz0C4.svg",
			},
		Lqi_k0oA9: title ?? props.Lqi_k0oA9 ?? "[ MORE ABOUT US ]",
		wUmti0vkQ: link ?? props.wUmti0vkQ,
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		Lqi_k0oA9,
		GI5Q9ZBz8,
		wUmti0vkQ,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		defaultVariant: "oX19YTKHw",
		enabledGestures,
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup
			suppressHydrationWarning={true}
			id={layoutId ?? defaultLayoutId}
		>
			<Variants
				suppressHydrationWarning={true}
				animate={variants}
				initial={false}
			>
				<Transition suppressHydrationWarning={true} value={transition1}>
					<Link
						suppressHydrationWarning={true}
						href={wUmti0vkQ}
						motionChild={true}
						nodeId={"oX19YTKHw"}
						scopeId={"tOMgpIwdN"}
					>
						<motion.a
							suppressHydrationWarning={true}
							{...restProps}
							{...gestureHandlers}
							className={`${cx(scopingClassNames, "framer-1e3oia4", className2, classNames)} framer-knhbn8`}
							data-framer-name={"About Button"}
							layoutDependency={layoutDependency}
							layoutId={"oX19YTKHw"}
							ref={refBinding}
							style={{
								...style,
							}}
							{...addPropertyOverrides(
								{
									"oX19YTKHw-hover": {
										"data-framer-name": void 0,
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<motion.div
								suppressHydrationWarning={true}
								className={"framer-1ecidpj"}
								data-framer-name={"Text"}
								layoutDependency={layoutDependency}
								layoutId={"hNld9UpLC"}
							>
								<RichText
									suppressHydrationWarning={true}
									__fromCanvasComponent={true}
									className={"framer-798uxj"}
									data-framer-name={"[ MORE ABOUT US ]"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"J18BrvqJC"}
									style={{
										"--framer-paragraph-spacing": "0px",
									}}
									text={Lqi_k0oA9}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.p
											suppressHydrationWarning={true}
											className={"framer-styles-preset-ei9thp"}
											data-styles-preset={"FOYoieLgU"}
										>
											{"[ MORE ABOUT US ]"}
										</motion.p>
									</React.Fragment>
								</RichText>
								<motion.div
									suppressHydrationWarning={true}
									className={"framer-14umr1w"}
									data-framer-name={"Line"}
									layoutDependency={layoutDependency}
									layoutId={"eKZX7XzUk"}
									style={{
										backgroundColor:
											"var(--token-d0efb30f-1ca4-4318-a615-3c27c4e89f33, rgb(255, 31, 0))",
									}}
								/>
							</motion.div>
							<motion.div
								suppressHydrationWarning={true}
								className={"framer-xgasds"}
								data-framer-name={"Icon Wrap"}
								layoutDependency={layoutDependency}
								layoutId={"FKfDv99ne"}
							>
								<Image
									suppressHydrationWarning={true}
									background={{
										alt: "",
										fit: "fill",
										loading: getLoadingLazyAtYPosition(
											(componentViewport?.y || 0) + 0 + 0,
										),
										pixelHeight: 20,
										pixelWidth: 20,
										sizes: "20px",
										...toResponsiveImage(GI5Q9ZBz8),
									}}
									className={"framer-4b79y2"}
									layoutDependency={layoutDependency}
									layoutId={"nuxQtQIVs"}
									{...addPropertyOverrides(
										{
											"oX19YTKHw-hover": {
												background: {
													alt: "",
													fit: "fill",
													loading: getLoadingLazyAtYPosition(
														(componentViewport?.y || 0) + 0 + -20,
													),
													pixelHeight: 20,
													pixelWidth: 20,
													sizes: "20px",
													...toResponsiveImage(GI5Q9ZBz8),
												},
											},
										},
										baseVariant,
										gestureVariant,
									)}
								/>
								<Image
									suppressHydrationWarning={true}
									background={{
										alt: "",
										fit: "fill",
										loading: getLoadingLazyAtYPosition(
											(componentViewport?.y || 0) + 0 + 20 - 0,
										),
										pixelHeight: 20,
										pixelWidth: 20,
										sizes: "20px",
										...toResponsiveImage(GI5Q9ZBz8),
									}}
									className={"framer-1jlrfsb"}
									layoutDependency={layoutDependency}
									layoutId={"LO44_1m5g"}
									{...addPropertyOverrides(
										{
											"oX19YTKHw-hover": {
												background: {
													alt: "",
													fit: "fill",
													loading: getLoadingLazyAtYPosition(
														(componentViewport?.y || 0) + 0 + 0,
													),
													pixelHeight: 20,
													pixelWidth: 20,
													sizes: "20px",
													...toResponsiveImage(GI5Q9ZBz8),
												},
											},
										},
										baseVariant,
										gestureVariant,
									)}
								/>
							</motion.div>
						</motion.a>
					</Link>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css2 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-oIyWP.framer-knhbn8, .framer-oIyWP .framer-knhbn8 { display: block; }",
	".framer-oIyWP.framer-1e3oia4 { align-content: flex-start; align-items: flex-start; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 9px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; text-decoration: none; width: min-content; }",
	".framer-oIyWP .framer-1ecidpj { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 0px 0px 2px 0px; position: relative; width: min-content; }",
	".framer-oIyWP .framer-798uxj { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-oIyWP .framer-14umr1w { align-content: center; align-items: center; bottom: 0px; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 1px; justify-content: center; left: -2px; overflow: hidden; padding: 0px; position: absolute; width: 1%; z-index: 1; }",
	".framer-oIyWP .framer-xgasds { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: min-content; }",
	".framer-oIyWP .framer-4b79y2 { flex: none; height: 20px; position: relative; width: 20px; }",
	".framer-oIyWP .framer-1jlrfsb { bottom: -20px; flex: none; height: 20px; left: -20px; position: absolute; width: 20px; z-index: 1; }",
	".framer-oIyWP.framer-v-1e3oia4.hover .framer-14umr1w { width: 103%; }",
	".framer-oIyWP.framer-v-1e3oia4.hover .framer-4b79y2 { position: absolute; right: -20px; top: -20px; z-index: 1; }",
	".framer-oIyWP.framer-v-1e3oia4.hover .framer-1jlrfsb { bottom: unset; left: unset; position: relative; }",
	...css,
];
var FramertOMgpIwdN = withCSS(Component, css2, "framer-oIyWP");
var stdin_default = FramertOMgpIwdN;
FramertOMgpIwdN.displayName = "About Button";
FramertOMgpIwdN.defaultProps = {
	height: 21,
	width: 173,
};
addPropertyControls(FramertOMgpIwdN, {
	Lqi_k0oA9: {
		defaultValue: "[ MORE ABOUT US ]",
		displayTextArea: false,
		title: "Title",
		type: ControlType.String,
	},
	GI5Q9ZBz8: {
		__defaultAssetReference:
			"data:framer/asset-reference,ne7C5pcflqjINmq1pB6QEuz0C4.svg?originalFilename=_arrow-top-right+%283%29.svg&preferredSize=auto",
		__vekterDefault: {
			alt: "Icon",
			assetReference:
				"data:framer/asset-reference,ne7C5pcflqjINmq1pB6QEuz0C4.svg?originalFilename=_arrow-top-right+%283%29.svg&preferredSize=auto",
		},
		title: "Image",
		type: ControlType.ResponsiveImage,
	},
	wUmti0vkQ: {
		title: "Link",
		type: ControlType.Link,
	},
});
addFonts(
	FramertOMgpIwdN,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:about-button
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"1907350542b7624112d99063e9127837bac05866cdf3676335c1d928983f49a3"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				suppressHydrationWarning: true,
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders AboutButtonFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"1907350542b7624112d99063e9127837bac05866cdf3676335c1d928983f49a3"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				suppressHydrationWarning={true}
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var about_button_default = ComponentWithRoot;
export { about_button_default as default };
