// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 1907350542b76241 "Blimpy", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop' | 'Phone' // Variant
 * title?: string // Title
 * onzFZOH0j0FCHange?: any // onzFZOH0j0FCHange
 * location?: string // Location
 * onA8FY0H4acChange?: any // onA8FY0H4acChange
 * arrangement?: string // Arrangement
 * onAlHdDw7tiChange?: any // onAlHdDw7tiChange
 * link?: string // Link
 * tags?: string // Tags
 * onel0WlnnkJCHange?: any // onel0WlnnkJCHange
 * date?: string // Date
 * onMsiDjIQY0Change?: any // onMsiDjIQY0Change
 * padding?: any // Padding
}} Props

 */
import { stdin_default } from "./chunks/chunk-F2ABRL4S.js";
import { className, css, fonts } from "./chunks/chunk-S5VMJNA7.js";
import { routes } from "./chunks/chunk-RHU4XTMM.js";

// virtual:career-card
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/lEbkDglvg30txbOq3N4s/1IaneoNb58wVnSMUcUbJ/dBEPkdbr1.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	forwardLoader,
	getFonts,
	getFontsFromSharedStyle,
	RichText,
	SmartComponentScopedContainer,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";

// /:https://framerusercontent.com/modules/7cfG3H5KM0lBmzTDdx3u/F0iJMdSzgDQeAVkRjfqJ/iRghmYol2.js
import { fontStore } from "unframer";
fontStore.loadFonts([
	"GF;Funnel Display-700",
	"Inter-Bold",
	"Inter-BoldItalic",
	"Inter-Italic",
]);
var fonts2 = [
	{
		explicitInter: true,
		fonts: [
			{
				family: "Funnel Display",
				openType: true,
				source: "google",
				style: "normal",
				url: "https://fonts.gstatic.com/s/funneldisplay/v2/B50bF7FGv37QNVWgE0ga--4PbZSRJXrOHcLHLoAYfWTXXcVwIZDKFA.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
				url: "https://framerusercontent.com/assets/DpPBYI0sL4fYLgAkX8KXOPVt7c.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
				url: "https://framerusercontent.com/assets/4RAEQdEOrcnDkhHiiCbJOw92Lk.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange: "U+1F00-1FFF",
				url: "https://framerusercontent.com/assets/1K3W8DizY3v4emK8Mb08YHxTbs.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange: "U+0370-03FF",
				url: "https://framerusercontent.com/assets/tUSCtfYVM1I1IchuyCwz9gDdQ.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
				url: "https://framerusercontent.com/assets/VgYFWiwsAC5OYxAycRXXvhze58.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
				url: "https://framerusercontent.com/assets/DXD0Q7LSl7HEvDzucnyLnGBHM.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
				url: "https://framerusercontent.com/assets/GIryZETIX4IFypco5pYZONKhJIo.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
				url: "https://framerusercontent.com/assets/H89BbHkbHDzlxZzxi8uPzTsp90.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
				url: "https://framerusercontent.com/assets/u6gJwDuwB143kpNK1T1MDKDWkMc.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+1F00-1FFF",
				url: "https://framerusercontent.com/assets/43sJ6MfOPh1LCJt46OvyDuSbA6o.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+0370-03FF",
				url: "https://framerusercontent.com/assets/wccHG0r4gBDAIRhfHiOlq6oEkqw.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
				url: "https://framerusercontent.com/assets/WZ367JPwf9bRW6LdTHN8rXgSjw.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
				url: "https://framerusercontent.com/assets/QxmhnWTzLtyjIiZcfaLIJ8EFBXU.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
				url: "https://framerusercontent.com/assets/2A4Xx7CngadFGlVV4xrO06OBHY.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
				url: "https://framerusercontent.com/assets/CfMzU8w2e7tHgF4T4rATMPuWosA.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
				url: "https://framerusercontent.com/assets/867QObYax8ANsfX4TGEVU9YiCM.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+1F00-1FFF",
				url: "https://framerusercontent.com/assets/Oyn2ZbENFdnW7mt2Lzjk1h9Zb9k.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+0370-03FF",
				url: "https://framerusercontent.com/assets/cdAe8hgZ1cMyLu9g005pAW3xMo.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
				url: "https://framerusercontent.com/assets/DOfvtmE1UplCq161m6Hj8CSQYg.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
				url: "https://framerusercontent.com/assets/vFzuJY0c65av44uhEKB6vyjFMg.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
				url: "https://framerusercontent.com/assets/tKtBcDnBMevsEEJKdNGhhkLzYo.woff2",
				weight: "400",
			},
		],
	},
];
var css2 = [
	`.framer-fZPS4 .framer-styles-preset-12jh57g:not(.rich-text-wrapper), .framer-fZPS4 .framer-styles-preset-12jh57g.rich-text-wrapper p { --framer-font-family: "Funnel Display", sans-serif; --framer-font-family-bold: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-bold-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-open-type-features: 'blwf' on, 'cv09' on, 'cv03' on, 'cv04' on, 'cv11' on; --framer-font-size: 18px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 700; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 400; --framer-letter-spacing: 0px; --framer-line-height: 1.4em; --framer-paragraph-spacing: 20px; --framer-text-alignment: start; --framer-text-color: var(--token-1ca63064-b503-4f13-8e66-ff201796eaf9, #ffffff); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; }`,
];
var className2 = "framer-fZPS4";

// /:https://framerusercontent.com/modules/u5TslTkiiqCIGkjO9i0p/Bu87WAuQwcQsTW6KqynR/QcfEIk6MJ.js
import { fontStore as fontStore2 } from "unframer";
fontStore2.loadFonts([
	"GF;Funnel Display-regular",
	"Inter-Bold",
	"Inter-BoldItalic",
	"Inter-Italic",
]);
var fonts3 = [
	{
		explicitInter: true,
		fonts: [
			{
				family: "Funnel Display",
				openType: true,
				source: "google",
				style: "normal",
				url: "https://fonts.gstatic.com/s/funneldisplay/v2/B50bF7FGv37QNVWgE0ga--4PbZSRJXrOHcLHLoAYmmPXXcVwIZDKFA.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
				url: "https://framerusercontent.com/assets/DpPBYI0sL4fYLgAkX8KXOPVt7c.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
				url: "https://framerusercontent.com/assets/4RAEQdEOrcnDkhHiiCbJOw92Lk.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange: "U+1F00-1FFF",
				url: "https://framerusercontent.com/assets/1K3W8DizY3v4emK8Mb08YHxTbs.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange: "U+0370-03FF",
				url: "https://framerusercontent.com/assets/tUSCtfYVM1I1IchuyCwz9gDdQ.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
				url: "https://framerusercontent.com/assets/VgYFWiwsAC5OYxAycRXXvhze58.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
				url: "https://framerusercontent.com/assets/DXD0Q7LSl7HEvDzucnyLnGBHM.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
				url: "https://framerusercontent.com/assets/GIryZETIX4IFypco5pYZONKhJIo.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
				url: "https://framerusercontent.com/assets/H89BbHkbHDzlxZzxi8uPzTsp90.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
				url: "https://framerusercontent.com/assets/u6gJwDuwB143kpNK1T1MDKDWkMc.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+1F00-1FFF",
				url: "https://framerusercontent.com/assets/43sJ6MfOPh1LCJt46OvyDuSbA6o.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+0370-03FF",
				url: "https://framerusercontent.com/assets/wccHG0r4gBDAIRhfHiOlq6oEkqw.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
				url: "https://framerusercontent.com/assets/WZ367JPwf9bRW6LdTHN8rXgSjw.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
				url: "https://framerusercontent.com/assets/QxmhnWTzLtyjIiZcfaLIJ8EFBXU.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
				url: "https://framerusercontent.com/assets/2A4Xx7CngadFGlVV4xrO06OBHY.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
				url: "https://framerusercontent.com/assets/CfMzU8w2e7tHgF4T4rATMPuWosA.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
				url: "https://framerusercontent.com/assets/867QObYax8ANsfX4TGEVU9YiCM.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+1F00-1FFF",
				url: "https://framerusercontent.com/assets/Oyn2ZbENFdnW7mt2Lzjk1h9Zb9k.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+0370-03FF",
				url: "https://framerusercontent.com/assets/cdAe8hgZ1cMyLu9g005pAW3xMo.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
				url: "https://framerusercontent.com/assets/DOfvtmE1UplCq161m6Hj8CSQYg.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
				url: "https://framerusercontent.com/assets/vFzuJY0c65av44uhEKB6vyjFMg.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
				url: "https://framerusercontent.com/assets/tKtBcDnBMevsEEJKdNGhhkLzYo.woff2",
				weight: "400",
			},
		],
	},
];
var css3 = [
	`.framer-sQIah .framer-styles-preset-1k52hy1:not(.rich-text-wrapper), .framer-sQIah .framer-styles-preset-1k52hy1.rich-text-wrapper p { --framer-font-family: "Funnel Display", sans-serif; --framer-font-family-bold: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-bold-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-open-type-features: 'blwf' on, 'cv09' on, 'cv03' on, 'cv04' on, 'cv11' on; --framer-font-size: 18px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 400; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 400; --framer-letter-spacing: 0px; --framer-line-height: 1.4em; --framer-paragraph-spacing: 20px; --framer-text-alignment: start; --framer-text-color: var(--token-1ca63064-b503-4f13-8e66-ff201796eaf9, #ffffff); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; }`,
];
var className3 = "framer-sQIah";

// /:https://framerusercontent.com/modules/nH7piZO3mufC0H28ARLq/3pjJQzrD7sKHmNO2A6Lx/YyydkF6BV.js
import { fontStore as fontStore3 } from "unframer";
fontStore3.loadFonts(["GF;Funnel Display-regular", "GF;Funnel Display-700"]);
var fonts4 = [
	{
		explicitInter: true,
		fonts: [
			{
				family: "Funnel Display",
				openType: true,
				source: "google",
				style: "normal",
				url: "https://fonts.gstatic.com/s/funneldisplay/v2/B50bF7FGv37QNVWgE0ga--4PbZSRJXrOHcLHLoAYmmPXXcVwIZDKFA.woff2",
				weight: "400",
			},
			{
				family: "Funnel Display",
				openType: true,
				source: "google",
				style: "normal",
				url: "https://fonts.gstatic.com/s/funneldisplay/v2/B50bF7FGv37QNVWgE0ga--4PbZSRJXrOHcLHLoAYfWTXXcVwIZDKFA.woff2",
				weight: "700",
			},
		],
	},
];
var css4 = [
	`.framer-MJAIV .framer-styles-preset-g7itge:not(.rich-text-wrapper), .framer-MJAIV .framer-styles-preset-g7itge.rich-text-wrapper p { --framer-font-family: "Funnel Display", sans-serif; --framer-font-family-bold: "Funnel Display", sans-serif; --framer-font-open-type-features: 'blwf' on, 'cv09' on, 'cv03' on, 'cv04' on, 'cv11' on; --framer-font-size: 16px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-variation-axes: normal; --framer-font-weight: 400; --framer-font-weight-bold: 700; --framer-letter-spacing: 0px; --framer-line-height: 1.4em; --framer-paragraph-spacing: 20px; --framer-text-alignment: start; --framer-text-color: var(--token-1ca63064-b503-4f13-8e66-ff201796eaf9, #ffffff); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; }`,
];
var className4 = "framer-MJAIV";

// /:https://framerusercontent.com/modules/lEbkDglvg30txbOq3N4s/1IaneoNb58wVnSMUcUbJ/dBEPkdbr1.js
var NavbarButtonFonts = getFonts(stdin_default);
var cycleOrder = ["cEhdOM0re", "foKAw5vLg"];
var serializationHash = "framer-waZBR";
var variantClassNames = {
	cEhdOM0re: "framer-v-v8uy6h",
	foKAw5vLg: "framer-v-1d0d876",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var numberToPixelString = (value) => {
	if (typeof value !== "number") return value;
	if (!Number.isFinite(value)) return void 0;
	return Math.max(0, value) + "px";
};
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var matchVariant = (...args) => {
	for (const arg of args) {
		if (arg && typeof arg === "string") return arg;
	}
	return void 0;
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider
			suppressHydrationWarning={true}
			value={contextValue}
		>
			{children}
		</MotionConfigContext.Provider>
	);
};
var humanReadableVariantMap = {
	Desktop: "cEhdOM0re",
	Phone: "foKAw5vLg",
};
var Variants = motion.create(React.Fragment);
var getProps = ({
	arrangement,
	date,
	height,
	id,
	link,
	location,
	padding,
	tags,
	title,
	width,
	...props
}) => {
	return {
		...props,
		A8FY0H4ac: location ?? props.A8FY0H4ac ?? "Nairobi, Kenya",
		AlHdDw7ti: arrangement ?? props.AlHdDw7ti ?? "Remote",
		el0WlnnkJ: tags ?? props.el0WlnnkJ ?? "Developer",
		I4Pw5T6sx: padding ?? props.I4Pw5T6sx ?? "64px",
		jxQ2ZbxEP: link ?? props.jxQ2ZbxEP,
		MsiDjIQY0: date ?? props.MsiDjIQY0 ?? "Listed on September 15, 2025",
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "cEhdOM0re",
		zFZoH0j0F: title ?? props.zFZoH0j0F ?? "Marketing Specialist",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className5,
		layoutId,
		variant,
		zFZoH0j0F: zFZoH0j0F2,
		A8FY0H4ac: A8FY0H4ac2,
		AlHdDw7ti: AlHdDw7ti2,
		jxQ2ZbxEP: jxQ2ZbxEP2,
		el0WlnnkJ: el0WlnnkJ2,
		MsiDjIQY0: MsiDjIQY02,
		I4Pw5T6sx: I4Pw5T6sx2,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "cEhdOM0re",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className, className4, className3, className2];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup
			suppressHydrationWarning={true}
			id={layoutId ?? defaultLayoutId}
		>
			<Variants
				suppressHydrationWarning={true}
				animate={variants}
				initial={false}
			>
				<Transition suppressHydrationWarning={true} value={transition1}>
					<motion.div
						suppressHydrationWarning={true}
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-v8uy6h",
							className5,
							classNames,
						)}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"cEhdOM0re"}
						ref={refBinding}
						style={{
							"--qrk6na": numberToPixelString(I4Pw5T6sx2),
							backgroundColor:
								"var(--token-e8ab953b-66a2-4200-aa47-a4efe49e09ad, rgb(25, 25, 25))",
							...style,
						}}
						{...addPropertyOverrides(
							{
								foKAw5vLg: {
									"data-framer-name": "Phone",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							suppressHydrationWarning={true}
							className={"framer-1bnlref"}
							data-framer-name={"Title Wrap"}
							layoutDependency={layoutDependency}
							layoutId={"ROZF5oyra"}
						>
							<RichText
								suppressHydrationWarning={true}
								__fromCanvasComponent={true}
								className={"framer-1j33ksy"}
								data-framer-name={"UI Designer"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"oEL1ULE7O"}
								style={{
									"--extracted-1eung3n":
										"var(--token-1ca63064-b503-4f13-8e66-ff201796eaf9, rgb(255, 255, 255))",
									"--framer-paragraph-spacing": "0px",
								}}
								text={zFZoH0j0F2}
								verticalAlignment={"center"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.h4
										suppressHydrationWarning={true}
										className={"framer-styles-preset-16txvtp"}
										data-styles-preset={"vBGA0TBry"}
										style={{
											"--framer-text-color":
												"var(--extracted-1eung3n, var(--token-1ca63064-b503-4f13-8e66-ff201796eaf9, rgb(255, 255, 255)))",
										}}
									>
										{"UI Designer"}
									</motion.h4>
								</React.Fragment>
							</RichText>
							<motion.div
								suppressHydrationWarning={true}
								className={"framer-1e6xxd0"}
								data-framer-name={"Text Wrap"}
								layoutDependency={layoutDependency}
								layoutId={"QaGLOsb_A"}
							>
								<motion.div
									suppressHydrationWarning={true}
									className={"framer-f8kng9"}
									data-framer-name={"Location"}
									layoutDependency={layoutDependency}
									layoutId={"YsyzPZnyT"}
								>
									<RichText
										suppressHydrationWarning={true}
										__fromCanvasComponent={true}
										className={"framer-12ex4cz"}
										data-framer-name={"Location"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"rlNTeN2h7"}
										style={{
											"--framer-paragraph-spacing": "0px",
										}}
										verticalAlignment={"center"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												suppressHydrationWarning={true}
												className={"framer-styles-preset-g7itge"}
												data-styles-preset={"YyydkF6BV"}
											>
												{"Location"}
											</motion.p>
										</React.Fragment>
									</RichText>
									<RichText
										suppressHydrationWarning={true}
										__fromCanvasComponent={true}
										className={"framer-163clsb"}
										data-framer-name={"Montr\xE9al, Canada"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"CzlHvIgX9"}
										style={{
											"--framer-paragraph-spacing": "0px",
										}}
										text={A8FY0H4ac2}
										verticalAlignment={"center"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												suppressHydrationWarning={true}
												className={"framer-styles-preset-1k52hy1"}
												data-styles-preset={"QcfEIk6MJ"}
											>
												{"Montr\xE9al, Canada"}
											</motion.p>
										</React.Fragment>
									</RichText>
								</motion.div>
								<motion.div
									suppressHydrationWarning={true}
									className={"framer-101unen"}
									data-framer-name={"Arrangement"}
									layoutDependency={layoutDependency}
									layoutId={"AxOLVvdyX"}
								>
									<RichText
										suppressHydrationWarning={true}
										__fromCanvasComponent={true}
										className={"framer-1xl3424"}
										data-framer-name={"Location"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"mCb93rJUS"}
										style={{
											"--framer-paragraph-spacing": "0px",
										}}
										verticalAlignment={"center"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												suppressHydrationWarning={true}
												className={"framer-styles-preset-g7itge"}
												data-styles-preset={"YyydkF6BV"}
											>
												{"Arrangement"}
											</motion.p>
										</React.Fragment>
									</RichText>
									<RichText
										suppressHydrationWarning={true}
										__fromCanvasComponent={true}
										className={"framer-j2x0cd"}
										data-framer-name={"Montr\xE9al, Canada"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"iDyRE73ho"}
										style={{
											"--framer-paragraph-spacing": "0px",
										}}
										text={AlHdDw7ti2}
										verticalAlignment={"center"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												suppressHydrationWarning={true}
												className={"framer-styles-preset-1k52hy1"}
												data-styles-preset={"QcfEIk6MJ"}
											>
												{"Remote"}
											</motion.p>
										</React.Fragment>
									</RichText>
								</motion.div>
								<motion.div
									suppressHydrationWarning={true}
									className={"framer-54rwxy"}
									data-framer-name={"Location"}
									layoutDependency={layoutDependency}
									layoutId={"lGoEAsr1a"}
								/>
								<ComponentViewportProvider
									suppressHydrationWarning={true}
									height={44}
									{...addPropertyOverrides(
										{
											foKAw5vLg: {
												y:
													(componentViewport?.y || 0) +
													20 +
													(((componentViewport?.height || 516) - 40 - 412.5) /
														2 +
														0 +
														0) +
													0 +
													69.9 +
													0 +
													179.2,
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<SmartComponentScopedContainer
										suppressHydrationWarning={true}
										className={"framer-2v6hfb-container"}
										layoutDependency={layoutDependency}
										layoutId={"SPLdvKGHC-container"}
										nodeId={"SPLdvKGHC"}
										rendersWithMotion={true}
										scopeId={"dBEPkdbr1"}
									>
										{_jsx(stdin_default, {
											suppressHydrationWarning: true,
											goL4mlrDu: "Apply Now",
											height: "100%",
											id: "SPLdvKGHC",
											layoutId: "SPLdvKGHC",
											variant: matchVariant("sM9ZwX9yv"),
											width: "100%",
											XljpmY9ss: jxQ2ZbxEP2,
										})}
									</SmartComponentScopedContainer>
								</ComponentViewportProvider>
							</motion.div>
						</motion.div>
						<motion.div
							suppressHydrationWarning={true}
							className={"framer-6a8he9"}
							data-framer-name={"Line"}
							layoutDependency={layoutDependency}
							layoutId={"UFsKqR_sk"}
							style={{
								backgroundColor:
									"var(--token-aad9f953-7a89-4aa6-8b88-7994cb74103e, rgba(255, 255, 255, 0.1))",
							}}
						/>
						<motion.div
							suppressHydrationWarning={true}
							className={"framer-1wb0k0l"}
							data-framer-name={"Text Wrap"}
							layoutDependency={layoutDependency}
							layoutId={"xYs5VuuQm"}
						>
							<motion.div
								suppressHydrationWarning={true}
								className={"framer-19roi8u"}
								data-framer-name={"Tag"}
								layoutDependency={layoutDependency}
								layoutId={"UZ9BEUUw0"}
							>
								<RichText
									suppressHydrationWarning={true}
									__fromCanvasComponent={true}
									className={"framer-1t9cbqz"}
									data-framer-name={"Tags:"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"Iv9LBLJqI"}
									style={{
										"--framer-paragraph-spacing": "0px",
									}}
									verticalAlignment={"center"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.p
											suppressHydrationWarning={true}
											className={"framer-styles-preset-1k52hy1"}
											data-styles-preset={"QcfEIk6MJ"}
										>
											{"Tags:"}
										</motion.p>
									</React.Fragment>
								</RichText>
								<RichText
									suppressHydrationWarning={true}
									__fromCanvasComponent={true}
									className={"framer-zvbzbn"}
									data-framer-name={"Develope"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"kHlFELCNw"}
									style={{
										"--extracted-r6o4lv":
											"var(--token-1ca63064-b503-4f13-8e66-ff201796eaf9, rgb(255, 255, 255))",
										"--framer-paragraph-spacing": "0px",
									}}
									text={el0WlnnkJ2}
									verticalAlignment={"center"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.p
											suppressHydrationWarning={true}
											className={"framer-styles-preset-12jh57g"}
											data-styles-preset={"iRghmYol2"}
											style={{
												"--framer-text-color":
													"var(--extracted-r6o4lv, var(--token-1ca63064-b503-4f13-8e66-ff201796eaf9, rgb(255, 255, 255)))",
											}}
										>
											{"Develope"}
										</motion.p>
									</React.Fragment>
								</RichText>
							</motion.div>
							<RichText
								suppressHydrationWarning={true}
								__fromCanvasComponent={true}
								className={"framer-dme924"}
								data-framer-name={"Listed on September 15, 2025"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"mJq4iwhDp"}
								style={{
									"--framer-paragraph-spacing": "0px",
								}}
								text={MsiDjIQY02}
								verticalAlignment={"center"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.p
										suppressHydrationWarning={true}
										className={"framer-styles-preset-12jh57g"}
										data-styles-preset={"iRghmYol2"}
									>
										{"Listed on September 15, 2025"}
									</motion.p>
								</React.Fragment>
							</RichText>
						</motion.div>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css5 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-waZBR.framer-1f0obje, .framer-waZBR .framer-1f0obje { display: block; }",
	".framer-waZBR.framer-v8uy6h { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 36px; height: min-content; justify-content: center; overflow: hidden; padding: var(--qrk6na); position: relative; width: 1140px; }",
	".framer-waZBR .framer-1bnlref { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 48px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-waZBR .framer-1j33ksy { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-waZBR .framer-1e6xxd0, .framer-waZBR .framer-1wb0k0l { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; height: min-content; justify-content: space-between; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-waZBR .framer-f8kng9, .framer-waZBR .framer-101unen { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 12px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: min-content; }",
	".framer-waZBR .framer-12ex4cz, .framer-waZBR .framer-163clsb, .framer-waZBR .framer-1xl3424, .framer-waZBR .framer-j2x0cd, .framer-waZBR .framer-1t9cbqz, .framer-waZBR .framer-zvbzbn, .framer-waZBR .framer-dme924 { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-waZBR .framer-54rwxy { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 12px; height: min-content; justify-content: flex-start; min-height: 22px; min-width: 101px; overflow: visible; padding: 0px; position: relative; width: min-content; }",
	".framer-waZBR .framer-2v6hfb-container { flex: none; height: auto; position: relative; width: auto; }",
	".framer-waZBR .framer-6a8he9 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 1px; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-waZBR .framer-19roi8u { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: min-content; }",
	".framer-waZBR.framer-v-1d0d876.framer-v8uy6h { gap: 24px; padding: 20px; width: 350px; }",
	".framer-waZBR.framer-v-1d0d876 .framer-1bnlref { gap: 30px; }",
	".framer-waZBR.framer-v-1d0d876 .framer-1e6xxd0, .framer-waZBR.framer-v-1d0d876 .framer-1wb0k0l { align-content: flex-start; align-items: flex-start; flex-direction: column; gap: 20px; justify-content: center; }",
	".framer-waZBR.framer-v-1d0d876 .framer-54rwxy { min-width: 100px; }",
	...css,
	...css4,
	...css3,
	...css2,
];
var FramerdBEPkdbr1 = withCSS(Component, css5, "framer-waZBR");
var stdin_default2 = FramerdBEPkdbr1;
FramerdBEPkdbr1.displayName = "Career Card";
FramerdBEPkdbr1.defaultProps = {
	height: 372,
	width: 1140,
};
addPropertyControls(FramerdBEPkdbr1, {
	variant: {
		options: ["cEhdOM0re", "foKAw5vLg"],
		optionTitles: ["Desktop", "Phone"],
		title: "Variant",
		type: ControlType.Enum,
	},
	zFZoH0j0F: {
		defaultValue: "Marketing Specialist",
		displayTextArea: false,
		title: "Title",
		type: ControlType.String,
	},
	onzFZoH0j0FChange: {
		changes: "zFZoH0j0F",
		type: ControlType.ChangeHandler,
	},
	A8FY0H4ac: {
		defaultValue: "Nairobi, Kenya",
		displayTextArea: false,
		title: "Location",
		type: ControlType.String,
	},
	onA8FY0H4acChange: {
		changes: "A8FY0H4ac",
		type: ControlType.ChangeHandler,
	},
	AlHdDw7ti: {
		defaultValue: "Remote",
		displayTextArea: false,
		title: "Arrangement",
		type: ControlType.String,
	},
	onAlHdDw7tiChange: {
		changes: "AlHdDw7ti",
		type: ControlType.ChangeHandler,
	},
	jxQ2ZbxEP: {
		title: "Link",
		type: ControlType.Link,
	},
	el0WlnnkJ: {
		defaultValue: "Developer",
		displayTextArea: false,
		title: "Tags",
		type: ControlType.String,
	},
	onel0WlnnkJChange: {
		changes: "el0WlnnkJ",
		type: ControlType.ChangeHandler,
	},
	MsiDjIQY0: {
		defaultValue: "Listed on September 15, 2025",
		displayTextArea: false,
		title: "Date",
		type: ControlType.String,
	},
	onMsiDjIQY0Change: {
		changes: "MsiDjIQY0",
		type: ControlType.ChangeHandler,
	},
	I4Pw5T6sx: {
		defaultValue: "64px",
		title: "Padding",
		type: ControlType.Padding,
	},
});
addFonts(
	FramerdBEPkdbr1,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...NavbarButtonFonts,
		...getFontsFromSharedStyle(fonts),
		...getFontsFromSharedStyle(fonts4),
		...getFontsFromSharedStyle(fonts3),
		...getFontsFromSharedStyle(fonts2),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);
FramerdBEPkdbr1.loader = {
	load: (props, context) => {
		const locale = context.locale;
		return Promise.allSettled([forwardLoader(stdin_default, {}, context)]);
	},
};

// virtual:career-card
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"1907350542b7624112d99063e9127837bac05866cdf3676335c1d928983f49a3"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				suppressHydrationWarning: true,
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders CareerCardFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"1907350542b7624112d99063e9127837bac05866cdf3676335c1d928983f49a3"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				suppressHydrationWarning={true}
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var career_card_default = ComponentWithRoot;
export { career_card_default as default };
