// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 1907350542b76241 "Blimpy", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
}} Props

 */
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-FNAFLMXC.js";
import { className, css, fonts } from "./chunks/chunk-RCFS46SR.js";
import { stdin_default } from "./chunks/chunk-COI36AVT.js";
import "./chunks/chunk-3KWTDRN7.js";
import { routes } from "./chunks/chunk-RHU4XTMM.js";

// virtual:contact-form
import { Fragment as Fragment3 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/U08cbuufE64CcK242WOX/bq9JdwXUkqZGGwT94vHK/hGn013N_2.js
import {
	jsx as _jsx2,
	jsxs as _jsxs,
	Fragment as _Fragment,
} from "react/jsx-runtime";
import {
	addFonts as addFonts2,
	ComponentViewportProvider,
	cx as cx2,
	FormContainer,
	FormPlainTextInput,
	forwardLoader,
	getFonts,
	getFontsFromSharedStyle as getFontsFromSharedStyle2,
	RichText as RichText2,
	SmartComponentScopedContainer,
	useComponentViewport as useComponentViewport2,
	useLocaleInfo as useLocaleInfo2,
	useVariantState as useVariantState2,
	withCSS as withCSS2,
} from "unframer";
import {
	LayoutGroup as LayoutGroup2,
	motion as motion2,
	MotionConfigContext as MotionConfigContext2,
} from "unframer";
import * as React2 from "react";
import { useRef as useRef2 } from "react";

// /:https://framerusercontent.com/modules/kP1IhiEehDI6eJJmJja2/wKEwwuoKlnwAAh2MCWYk/pQXsYW0yA.js
import { jsx as _jsx } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	RichText,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var cycleOrder = ["p5EIt2jEh", "SXNhuY40P"];
var serializationHash = "framer-3ty1b";
var variantClassNames = {
	p5EIt2jEh: "framer-v-1yr66sc",
	SXNhuY40P: "framer-v-8s9ymc",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider
			suppressHydrationWarning={true}
			value={contextValue}
		>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	Active: "p5EIt2jEh",
	Inactive: "SXNhuY40P",
};
var getProps = ({ height, id, title, width, ...props }) => {
	return {
		...props,
		fsDiSuQiR: title ?? props.fsDiSuQiR ?? "Branding",
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "p5EIt2jEh",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className3,
		layoutId,
		variant,
		fsDiSuQiR,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "p5EIt2jEh",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onTap13bnrvb = activeVariantCallback(async (...args) => {
		setGestureState({
			isPressed: false,
		});
		setVariant("SXNhuY40P");
	});
	const onTapf5ghj2 = activeVariantCallback(async (...args) => {
		setGestureState({
			isPressed: false,
		});
		setVariant("p5EIt2jEh");
	});
	const sharedStyleClassNames = [className2];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup
			suppressHydrationWarning={true}
			id={layoutId ?? defaultLayoutId}
		>
			<Variants
				suppressHydrationWarning={true}
				animate={variants}
				initial={false}
			>
				<Transition suppressHydrationWarning={true} value={transition1}>
					<motion.button
						suppressHydrationWarning={true}
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-1yr66sc",
							className3,
							classNames,
						)}
						data-framer-name={"Active"}
						data-highlight={true}
						data-reset={"button"}
						layoutDependency={layoutDependency}
						layoutId={"p5EIt2jEh"}
						onTap={onTap13bnrvb}
						ref={refBinding}
						style={{
							"--border-bottom-width": "0px",
							"--border-color": "rgba(0, 0, 0, 0)",
							"--border-left-width": "0px",
							"--border-right-width": "0px",
							"--border-style": "solid",
							"--border-top-width": "0px",
							backgroundColor:
								"var(--token-d0efb30f-1ca4-4318-a615-3c27c4e89f33, rgb(255, 31, 0))",
							...style,
						}}
						variants={{
							SXNhuY40P: {
								"--border-bottom-width": "1px",
								"--border-color":
									"var(--token-b4a07562-9d21-427d-a929-14dffff1f88b, rgb(107, 107, 107))",
								"--border-left-width": "1px",
								"--border-right-width": "1px",
								"--border-style": "solid",
								"--border-top-width": "1px",
								backgroundColor:
									"var(--token-6b18cceb-a1b1-4983-8607-c0236a2dd4cd, rgb(18, 18, 18))",
							},
						}}
						{...addPropertyOverrides(
							{
								SXNhuY40P: {
									"data-border": true,
									"data-framer-name": "Inactive",
									onTap: onTapf5ghj2,
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<RichText
							suppressHydrationWarning={true}
							__fromCanvasComponent={true}
							className={"framer-19pfn3o"}
							data-framer-name={"Branding"}
							fonts={["Inter"]}
							layoutDependency={layoutDependency}
							layoutId={"H2rkAEbeh"}
							style={{
								"--extracted-r6o4lv":
									"var(--token-6b18cceb-a1b1-4983-8607-c0236a2dd4cd, rgb(18, 18, 18))",
								"--framer-paragraph-spacing": "0px",
							}}
							text={fsDiSuQiR}
							variants={{
								SXNhuY40P: {
									"--extracted-r6o4lv":
										"var(--token-1ca63064-b503-4f13-8e66-ff201796eaf9, rgb(255, 255, 255))",
								},
							}}
							verticalAlignment={"center"}
							withExternalLayout={true}
							{...addPropertyOverrides(
								{
									SXNhuY40P: {
										children: (
											<React.Fragment>
												<motion.p
													suppressHydrationWarning={true}
													className={"framer-styles-preset-1me9qdm"}
													data-styles-preset={"DH9ENh_0Z"}
													style={{
														"--framer-text-color":
															"var(--extracted-r6o4lv, var(--token-1ca63064-b503-4f13-8e66-ff201796eaf9, rgb(255, 255, 255)))",
													}}
												>
													{"Branding"}
												</motion.p>
											</React.Fragment>
										),
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<React.Fragment>
								<motion.p
									suppressHydrationWarning={true}
									className={"framer-styles-preset-1me9qdm"}
									data-styles-preset={"DH9ENh_0Z"}
									style={{
										"--framer-text-color":
											"var(--extracted-r6o4lv, var(--token-6b18cceb-a1b1-4983-8607-c0236a2dd4cd, rgb(18, 18, 18)))",
									}}
								>
									{"Branding"}
								</motion.p>
							</React.Fragment>
						</RichText>
					</motion.button>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css3 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-3ty1b.framer-7grbwu, .framer-3ty1b .framer-7grbwu { display: block; }",
	".framer-3ty1b.framer-1yr66sc { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: center; overflow: visible; padding: 12px 16px 12px 16px; position: relative; width: min-content; }",
	".framer-3ty1b .framer-19pfn3o { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	...css2,
	'.framer-3ty1b[data-border="true"]::after, .framer-3ty1b [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var FramerpQXsYW0yA = withCSS(Component, css3, "framer-3ty1b");
var stdin_default2 = FramerpQXsYW0yA;
FramerpQXsYW0yA.displayName = "Tab Button";
FramerpQXsYW0yA.defaultProps = {
	height: 50,
	width: 102,
};
addPropertyControls(FramerpQXsYW0yA, {
	variant: {
		options: ["p5EIt2jEh", "SXNhuY40P"],
		optionTitles: ["Active", "Inactive"],
		title: "Variant",
		type: ControlType.Enum,
	},
	fsDiSuQiR: {
		defaultValue: "Branding",
		displayTextArea: false,
		title: "Title",
		type: ControlType.String,
	},
});
addFonts(
	FramerpQXsYW0yA,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts2),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// /:https://framerusercontent.com/modules/U08cbuufE64CcK242WOX/bq9JdwXUkqZGGwT94vHK/hGn013N_2.js
var TabButtonFonts = getFonts(stdin_default2);
var FormButtonFonts = getFonts(stdin_default);
var serializationHash2 = "framer-GrgEQ";
var variantClassNames2 = {
	NeRpGu0_o: "framer-v-yn75hb",
};
var transition12 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var matchVariant = (...args) => {
	for (const arg of args) {
		if (arg && typeof arg === "string") return arg;
	}
	return void 0;
};
var formVariants = (form, variants, currentVariant) => {
	switch (form.state) {
		case "success":
			return variants.success ?? currentVariant;
		case "pending":
			return variants.pending ?? currentVariant;
		case "error":
			return variants.error ?? currentVariant;
		case "incomplete":
			return variants.incomplete ?? currentVariant;
		default:
			return currentVariant;
	}
};
var Transition2 = ({ value, children }) => {
	const config = React2.useContext(MotionConfigContext2);
	const transition = value ?? config.transition;
	const contextValue = React2.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext2.Provider
			suppressHydrationWarning={true}
			value={contextValue}
		>
			{children}
		</MotionConfigContext2.Provider>
	);
};
var Variants2 = motion2.create(React2.Fragment);
var getProps2 = ({ height, id, width, ...props }) => {
	return {
		...props,
	};
};
var createLayoutDependency2 = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component2 = /* @__PURE__ */ React2.forwardRef(function (props, ref) {
	const fallbackRef = useRef2(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React2.useId();
	const { activeLocale, setLocale } = useLocaleInfo2();
	const componentViewport = useComponentViewport2();
	const {
		style,
		className: className3,
		layoutId,
		variant,
		...restProps
	} = getProps2(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState2({
		defaultVariant: "NeRpGu0_o",
		ref: refBinding,
		variant,
		variantClassNames: variantClassNames2,
	});
	const layoutDependency = createLayoutDependency2(props, variants);
	const sharedStyleClassNames = [className];
	const scopingClassNames = cx2(serializationHash2, ...sharedStyleClassNames);
	return (
		<LayoutGroup2
			suppressHydrationWarning={true}
			id={layoutId ?? defaultLayoutId}
		>
			<Variants2
				suppressHydrationWarning={true}
				animate={variants}
				initial={false}
			>
				<Transition2 suppressHydrationWarning={true} value={transition12}>
					<motion2.div
						suppressHydrationWarning={true}
						{...restProps}
						{...gestureHandlers}
						className={cx2(
							scopingClassNames,
							"framer-yn75hb",
							className3,
							classNames,
						)}
						data-framer-name={"Contact Form"}
						layoutDependency={layoutDependency}
						layoutId={"NeRpGu0_o"}
						ref={refBinding}
						style={{
							...style,
						}}
					>
						<motion2.div
							suppressHydrationWarning={true}
							className={"framer-8r2fr6"}
							data-framer-name={"Category Wrapper"}
							layoutDependency={layoutDependency}
							layoutId={"cUVKnoZiT"}
						>
							<RichText2
								suppressHydrationWarning={true}
								__fromCanvasComponent={true}
								className={"framer-1ldvzm"}
								data-framer-name={"Tell us about your projects"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"Ul5ow5vTt"}
								style={{
									"--extracted-r6o4lv":
										"var(--token-687c2cb1-72a4-49d6-83df-e200278f840d, rgb(178, 158, 158))",
									"--framer-paragraph-spacing": "0px",
								}}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React2.Fragment>
									<motion2.p
										suppressHydrationWarning={true}
										className={"framer-styles-preset-1me9qdm"}
										data-styles-preset={"DH9ENh_0Z"}
										dir={"auto"}
										style={{
											"--framer-text-color":
												"var(--extracted-r6o4lv, var(--token-687c2cb1-72a4-49d6-83df-e200278f840d, rgb(178, 158, 158)))",
										}}
									>
										{"Tell us about your projects"}
									</motion2.p>
								</React2.Fragment>
							</RichText2>
							<motion2.div
								suppressHydrationWarning={true}
								className={"framer-1gpwrag"}
								data-framer-name={"List"}
								layoutDependency={layoutDependency}
								layoutId={"VWeN6q4eR"}
							>
								<ComponentViewportProvider
									suppressHydrationWarning={true}
									height={50}
								>
									<SmartComponentScopedContainer
										suppressHydrationWarning={true}
										className={"framer-fsz5rv-container"}
										layoutDependency={layoutDependency}
										layoutId={"DynngJFKm-container"}
										nodeId={"DynngJFKm"}
										rendersWithMotion={true}
										scopeId={"hGn013N_2"}
									>
										{_jsx2(stdin_default2, {
											suppressHydrationWarning: true,
											fsDiSuQiR: "Data Integration",
											height: "100%",
											id: "DynngJFKm",
											layoutId: "DynngJFKm",
											variant: matchVariant("p5EIt2jEh"),
											width: "100%",
										})}
									</SmartComponentScopedContainer>
								</ComponentViewportProvider>
								<ComponentViewportProvider
									suppressHydrationWarning={true}
									height={50}
								>
									<SmartComponentScopedContainer
										suppressHydrationWarning={true}
										className={"framer-1vjgcr6-container"}
										layoutDependency={layoutDependency}
										layoutId={"jmAtaBIO0-container"}
										nodeId={"jmAtaBIO0"}
										rendersWithMotion={true}
										scopeId={"hGn013N_2"}
									>
										{_jsx2(stdin_default2, {
											suppressHydrationWarning: true,
											fsDiSuQiR: "Data Visualization",
											height: "100%",
											id: "jmAtaBIO0",
											layoutId: "jmAtaBIO0",
											variant: matchVariant("p5EIt2jEh"),
											width: "100%",
										})}
									</SmartComponentScopedContainer>
								</ComponentViewportProvider>
								<ComponentViewportProvider
									suppressHydrationWarning={true}
									height={50}
								>
									<SmartComponentScopedContainer
										suppressHydrationWarning={true}
										className={"framer-q74rk3-container"}
										layoutDependency={layoutDependency}
										layoutId={"SSqg0ftlk-container"}
										nodeId={"SSqg0ftlk"}
										rendersWithMotion={true}
										scopeId={"hGn013N_2"}
									>
										{_jsx2(stdin_default2, {
											suppressHydrationWarning: true,
											fsDiSuQiR: "Data Analysis",
											height: "100%",
											id: "SSqg0ftlk",
											layoutId: "SSqg0ftlk",
											variant: matchVariant("p5EIt2jEh"),
											width: "100%",
										})}
									</SmartComponentScopedContainer>
								</ComponentViewportProvider>
								<ComponentViewportProvider
									suppressHydrationWarning={true}
									height={50}
								>
									<SmartComponentScopedContainer
										suppressHydrationWarning={true}
										className={"framer-12kdhz1-container"}
										layoutDependency={layoutDependency}
										layoutId={"ftDLhIPGr-container"}
										nodeId={"ftDLhIPGr"}
										rendersWithMotion={true}
										scopeId={"hGn013N_2"}
									>
										{_jsx2(stdin_default2, {
											suppressHydrationWarning: true,
											fsDiSuQiR: "Creative Marketing",
											height: "100%",
											id: "ftDLhIPGr",
											layoutId: "ftDLhIPGr",
											variant: matchVariant("p5EIt2jEh"),
											width: "100%",
										})}
									</SmartComponentScopedContainer>
								</ComponentViewportProvider>
							</motion2.div>
						</motion2.div>
						<FormContainer
							suppressHydrationWarning={true}
							action={
								"https://api.framer.com/forms/v1/forms/27948f86-0eac-4f2d-b16f-ca9818aecaa7/submit"
							}
							className={"framer-pt14fg"}
							layoutDependency={layoutDependency}
							layoutId={"tocO5xnfO"}
							nodeId={"tocO5xnfO"}
							redirectUrl={"/"}
						>
							{(formState) => (
								<_Fragment>
									<motion2.label
										suppressHydrationWarning={true}
										className={"framer-z2q6xh"}
										layoutDependency={layoutDependency}
										layoutId={"gmR_F9tiX"}
									>
										<FormPlainTextInput
											suppressHydrationWarning={true}
											className={"framer-1oritj7"}
											inputName={"Name"}
											layoutDependency={layoutDependency}
											layoutId={"x1mVDj009"}
											placeholder={"Name"}
											required={true}
											style={{
												"--framer-input-border-bottom-width": "1px",
												"--framer-input-border-color":
													"var(--token-aad9f953-7a89-4aa6-8b88-7994cb74103e, rgba(255, 255, 255, 0.1))",
												"--framer-input-border-left-width": "0px",
												"--framer-input-border-right-width": "0px",
												"--framer-input-border-style": "solid",
												"--framer-input-border-top-width": "0px",
												"--framer-input-font-color":
													"var(--token-62fc56d5-8031-48ca-aadd-0300399f1b61, rgb(212, 212, 212))",
												"--framer-input-icon-color": "rgb(153, 153, 153)",
												"--framer-input-placeholder-color":
													"var(--token-62fc56d5-8031-48ca-aadd-0300399f1b61, rgb(212, 212, 212))",
											}}
											type={"text"}
										/>
									</motion2.label>
									<motion2.label
										suppressHydrationWarning={true}
										className={"framer-mwh0fu"}
										layoutDependency={layoutDependency}
										layoutId={"RLAMdfsBm"}
									>
										<FormPlainTextInput
											suppressHydrationWarning={true}
											className={"framer-ydxboj"}
											inputName={"Phonenumber"}
											layoutDependency={layoutDependency}
											layoutId={"bZCQREQlY"}
											placeholder={"Phone number"}
											required={true}
											style={{
												"--framer-input-border-bottom-width": "1px",
												"--framer-input-border-color":
													"var(--token-aad9f953-7a89-4aa6-8b88-7994cb74103e, rgba(255, 255, 255, 0.1))",
												"--framer-input-border-left-width": "0px",
												"--framer-input-border-right-width": "0px",
												"--framer-input-border-style": "solid",
												"--framer-input-border-top-width": "0px",
												"--framer-input-font-color":
													"var(--token-62fc56d5-8031-48ca-aadd-0300399f1b61, rgb(212, 212, 212))",
												"--framer-input-icon-color": "rgb(153, 153, 153)",
												"--framer-input-placeholder-color":
													"var(--token-62fc56d5-8031-48ca-aadd-0300399f1b61, rgb(212, 212, 212))",
											}}
											type={"tel"}
										/>
									</motion2.label>
									<motion2.label
										suppressHydrationWarning={true}
										className={"framer-15nwhmc"}
										layoutDependency={layoutDependency}
										layoutId={"Pl8krm6Uy"}
									>
										<FormPlainTextInput
											suppressHydrationWarning={true}
											className={"framer-1gzf6we"}
											inputName={"Email"}
											layoutDependency={layoutDependency}
											layoutId={"yRkQtpt92"}
											placeholder={"Email Address"}
											required={true}
											style={{
												"--framer-input-border-bottom-width": "1px",
												"--framer-input-border-color":
													"var(--token-aad9f953-7a89-4aa6-8b88-7994cb74103e, rgba(255, 255, 255, 0.1))",
												"--framer-input-border-left-width": "0px",
												"--framer-input-border-right-width": "0px",
												"--framer-input-border-style": "solid",
												"--framer-input-border-top-width": "0px",
												"--framer-input-font-color":
													"var(--token-62fc56d5-8031-48ca-aadd-0300399f1b61, rgb(212, 212, 212))",
												"--framer-input-icon-color": "rgb(153, 153, 153)",
												"--framer-input-placeholder-color":
													"var(--token-62fc56d5-8031-48ca-aadd-0300399f1b61, rgb(212, 212, 212))",
											}}
											type={"email"}
										/>
									</motion2.label>
									<motion2.label
										suppressHydrationWarning={true}
										className={"framer-19zyt2i"}
										layoutDependency={layoutDependency}
										layoutId={"Cg7FwggFc"}
									>
										<FormPlainTextInput
											suppressHydrationWarning={true}
											className={"framer-13dram1"}
											inputName={"Message"}
											layoutDependency={layoutDependency}
											layoutId={"zOoLdI4tG"}
											placeholder={"Tell us about your business"}
											style={{
												"--framer-input-border-bottom-width": "1px",
												"--framer-input-border-color":
													"var(--token-aad9f953-7a89-4aa6-8b88-7994cb74103e, rgba(255, 255, 255, 0.1))",
												"--framer-input-border-left-width": "0px",
												"--framer-input-border-right-width": "0px",
												"--framer-input-border-style": "solid",
												"--framer-input-border-top-width": "0px",
												"--framer-input-font-color":
													"var(--token-62fc56d5-8031-48ca-aadd-0300399f1b61, rgb(212, 212, 212))",
												"--framer-input-icon-color": "rgb(153, 153, 153)",
												"--framer-input-placeholder-color":
													"var(--token-62fc56d5-8031-48ca-aadd-0300399f1b61, rgb(212, 212, 212))",
											}}
											type={"textarea"}
										/>
									</motion2.label>
									<ComponentViewportProvider
										suppressHydrationWarning={true}
										height={46}
									>
										<SmartComponentScopedContainer
											suppressHydrationWarning={true}
											className={"framer-ahm0ce-container"}
											layoutDependency={layoutDependency}
											layoutId={"rzL0r5BBM-container"}
											nodeId={"rzL0r5BBM"}
											rendersWithMotion={true}
											scopeId={"hGn013N_2"}
										>
											{_jsx2(stdin_default, {
												suppressHydrationWarning: true,
												height: "100%",
												id: "rzL0r5BBM",
												layoutId: "rzL0r5BBM",
												type: "submit",
												variant: formVariants(
													formState,
													{
														pending: "UoA4pMhAv",
														success: "y8XwxU8tT",
													},
													matchVariant("NqnYKWHYF"),
												),
												width: "100%",
											})}
										</SmartComponentScopedContainer>
									</ComponentViewportProvider>
								</_Fragment>
							)}
						</FormContainer>
					</motion2.div>
				</Transition2>
			</Variants2>
		</LayoutGroup2>
	);
});
var css4 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-GrgEQ.framer-ndi8by, .framer-GrgEQ .framer-ndi8by { display: block; }",
	".framer-GrgEQ.framer-yn75hb { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 46px; height: min-content; justify-content: center; max-width: 703px; overflow: hidden; padding: 0px; position: relative; width: 658px; }",
	".framer-GrgEQ .framer-8r2fr6 { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: center; max-width: 703px; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-GrgEQ .framer-1ldvzm { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-GrgEQ .framer-1gpwrag { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-GrgEQ .framer-fsz5rv-container, .framer-GrgEQ .framer-1vjgcr6-container, .framer-GrgEQ .framer-q74rk3-container, .framer-GrgEQ .framer-12kdhz1-container, .framer-GrgEQ .framer-ahm0ce-container { flex: none; height: auto; position: relative; width: auto; }",
	".framer-GrgEQ .framer-pt14fg { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-GrgEQ .framer-z2q6xh, .framer-GrgEQ .framer-mwh0fu, .framer-GrgEQ .framer-15nwhmc, .framer-GrgEQ .framer-19zyt2i { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-start; padding: 0px; position: relative; width: 100%; }",
	'.framer-GrgEQ .framer-1oritj7, .framer-GrgEQ .framer-ydxboj, .framer-GrgEQ .framer-1gzf6we { --framer-input-font-family: "Funnel Display"; --framer-input-font-letter-spacing: 0em; --framer-input-font-line-height: 1.5em; --framer-input-font-size: 18px; --framer-input-font-weight: 400; --framer-input-padding: 10px 0px 24px 0px; --framer-input-wrapper-height: auto; flex: none; height: auto; position: relative; width: 100%; }',
	'.framer-GrgEQ .framer-13dram1 { --framer-input-font-family: "Funnel Display"; --framer-input-font-letter-spacing: 0em; --framer-input-font-line-height: 1.5em; --framer-input-font-size: 18px; --framer-input-font-weight: 400; --framer-input-padding: 10px 0px 24px 0px; --framer-input-wrapper-height: auto; --framer-textarea-resize: vertical; flex: none; height: auto; min-height: 100px; position: relative; width: 100%; }',
	...css,
];
var FramerhGn013N_2 = withCSS2(Component2, css4, "framer-GrgEQ");
var stdin_default3 = FramerhGn013N_2;
FramerhGn013N_2.displayName = "Contact Form";
FramerhGn013N_2.defaultProps = {
	height: 537,
	width: 658,
};
addFonts2(
	FramerhGn013N_2,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Funnel Display",
					source: "google",
					style: "normal",
					uiFamilyName: "Funnel Display",
					url: "https://fonts.gstatic.com/s/funneldisplay/v3/B50bF7FGv37QNVWgE0ga--4PbZSRJXrOHcLHLoAYmmPXXcVwIZDKFA.woff2",
					weight: "400",
				},
			],
		},
		...TabButtonFonts,
		...FormButtonFonts,
		...getFontsFromSharedStyle2(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);
FramerhGn013N_2.loader = {
	load: (props, context) => {
		const locale = context.locale;
		return Promise.allSettled([
			forwardLoader(stdin_default2, {}, context),
			forwardLoader(stdin_default, {}, context),
		]);
	},
};

// virtual:contact-form
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"1907350542b7624112d99063e9127837bac05866cdf3676335c1d928983f49a3"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default3, {
				suppressHydrationWarning: true,
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders ContactFormFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"1907350542b7624112d99063e9127837bac05866cdf3676335c1d928983f49a3"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				suppressHydrationWarning={true}
				Component={stdin_default3}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default3);
var contact_form_default = ComponentWithRoot;
export { contact_form_default as default };
