// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 1907350542b76241 "Blimpy", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Open' | 'Close' // Variant
 * click?: Function // Click
 * padding?: any // Padding
 * title?: string // Title
 * text?: string // Text
}} Props

 */
import {
	className as className2,
	css as css2,
	fonts as fonts2,
	stdin_default,
	stdin_default2,
} from "./chunks/chunk-XRT6IGV4.js";
import { className, css, fonts } from "./chunks/chunk-CM7YMXDZ.js";
import { routes } from "./chunks/chunk-RHU4XTMM.js";

// virtual:faq-card
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/ob5vV5rj9TcYhil9W6jM/T6OjrRPXgkXFUgYUtwEA/QFecanpUy.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	Instance,
	RichText,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var cycleOrder = ["U5H7kMV2j", "dB5vGvZub"];
var serializationHash = "framer-pz0Mz";
var variantClassNames = {
	dB5vGvZub: "framer-v-o5mjf3",
	U5H7kMV2j: "framer-v-1h1g97a",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	damping: 30,
	delay: 0,
	mass: 1,
	stiffness: 400,
	type: "spring",
};
var numberToPixelString = (value) => {
	if (typeof value !== "number") return value;
	if (!Number.isFinite(value)) return void 0;
	return Math.max(0, value) + "px";
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider
			suppressHydrationWarning={true}
			value={contextValue}
		>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	Close: "dB5vGvZub",
	Open: "U5H7kMV2j",
};
var getProps = ({
	click,
	height,
	id,
	padding,
	text,
	title,
	width,
	...props
}) => {
	return {
		...props,
		fmZskzz2R: title ?? props.fmZskzz2R ?? "Speed of design delivery?",
		O7apdCcJm:
			text ??
			props.O7apdCcJm ??
			"How quick is quick? For most design, we\u2019re talking 2-3 business days. We balance speed with quality,ensuring you get top-north design swiftly",
		SWClb3Nqz: click ?? props.SWClb3Nqz,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "U5H7kMV2j",
		yioEeMfQr: padding ?? props.yioEeMfQr ?? "40px",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className3,
		layoutId,
		variant,
		SWClb3Nqz,
		yioEeMfQr,
		fmZskzz2R,
		O7apdCcJm,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "U5H7kMV2j",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onTap1hp7ncs = activeVariantCallback(async (...args) => {
		setGestureState({
			isPressed: false,
		});
		if (SWClb3Nqz) {
			const res = await SWClb3Nqz(...args);
			if (res === false) return false;
		}
		setVariant("dB5vGvZub");
	});
	const onTap145y1ep = activeVariantCallback(async (...args) => {
		setGestureState({
			isPressed: false,
		});
		if (SWClb3Nqz) {
			const res = await SWClb3Nqz(...args);
			if (res === false) return false;
		}
		setVariant("U5H7kMV2j");
	});
	const sharedStyleClassNames = [className2, className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const isDisplayed = () => {
		if (baseVariant === "dB5vGvZub") return false;
		return true;
	};
	return (
		<LayoutGroup
			suppressHydrationWarning={true}
			id={layoutId ?? defaultLayoutId}
		>
			<Variants
				suppressHydrationWarning={true}
				animate={variants}
				initial={false}
			>
				<Transition suppressHydrationWarning={true} value={transition1}>
					<motion.div
						suppressHydrationWarning={true}
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-1h1g97a",
							className3,
							classNames,
						)}
						data-framer-name={"Open"}
						data-highlight={true}
						layoutDependency={layoutDependency}
						layoutId={"U5H7kMV2j"}
						onTap={onTap1hp7ncs}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								dB5vGvZub: {
									"data-framer-name": "Close",
									onTap: onTap145y1ep,
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							suppressHydrationWarning={true}
							className={"framer-1mhqcjd"}
							data-border={true}
							data-framer-name={"Content"}
							layoutDependency={layoutDependency}
							layoutId={"FIOvjfamC"}
							style={{
								"--1fbot2b": numberToPixelString(yioEeMfQr),
								"--border-bottom-width": "1px",
								"--border-color": "rgba(255, 255, 255, 0.01)",
								"--border-left-width": "1px",
								"--border-right-width": "1px",
								"--border-style": "solid",
								"--border-top-width": "1px",
								backgroundColor:
									"var(--token-a63e3e1f-a821-4113-9f64-bc0cd2c2c18e, rgba(255, 255, 255, 0.03))",
							}}
							variants={{
								dB5vGvZub: {
									"--border-color": "rgba(255, 255, 255, 0.05)",
									backgroundColor: "rgba(0, 0, 0, 0)",
								},
							}}
						>
							<motion.div
								suppressHydrationWarning={true}
								className={"framer-1w6mdvl"}
								data-framer-name={"Title"}
								layoutDependency={layoutDependency}
								layoutId={"QwkiYO9Gn"}
							>
								<RichText
									suppressHydrationWarning={true}
									__fromCanvasComponent={true}
									className={"framer-y1fmcd"}
									data-framer-name={"Speed of design delivery?"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"SDnT7PxPl"}
									style={{
										"--framer-paragraph-spacing": "0px",
									}}
									text={fmZskzz2R}
									verticalAlignment={"center"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.h4
											suppressHydrationWarning={true}
											className={"framer-styles-preset-txuqj2"}
											data-styles-preset={"HnFuI95b_"}
										>
											{"Speed of design delivery?"}
										</motion.h4>
									</React.Fragment>
								</RichText>
								<Instance
									suppressHydrationWarning={true}
									animated={true}
									className={"framer-172idd0"}
									Component={stdin_default}
									layoutDependency={layoutDependency}
									layoutId={"xnljokCj8"}
									style={{
										"--43q7um":
											"var(--token-d0efb30f-1ca4-4318-a615-3c27c4e89f33, rgb(255, 31, 0))",
									}}
									variants={{
										dB5vGvZub: {
											"--43q7um":
												"var(--token-1ca63064-b503-4f13-8e66-ff201796eaf9, rgb(255, 255, 255))",
										},
									}}
									{...addPropertyOverrides(
										{
											dB5vGvZub: {
												Component: stdin_default2,
											},
										},
										baseVariant,
										gestureVariant,
									)}
								/>
							</motion.div>
							{isDisplayed() && (
								<RichText
									suppressHydrationWarning={true}
									__fromCanvasComponent={true}
									className={"framer-engws1"}
									data-framer-name={
										"How quick is quick? For most design, we\u2019re talking 2-3 business days. We balance speed with quality,\u2028ensuring you get top-north design swiftly"
									}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"t4slC_AXh"}
									style={{
										"--framer-paragraph-spacing": "0px",
									}}
									text={O7apdCcJm}
									verticalAlignment={"center"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.p
											suppressHydrationWarning={true}
											className={"framer-styles-preset-g7itge"}
											data-styles-preset={"YyydkF6BV"}
										>
											{
												"How quick is quick? For most design, we\u2019re talking 2-3 business days. We balance speed with quality,ensuring you get top-north design swiftly"
											}
										</motion.p>
									</React.Fragment>
								</RichText>
							)}
						</motion.div>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css3 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-pz0Mz.framer-scl3gp, .framer-pz0Mz .framer-scl3gp { display: block; }",
	".framer-pz0Mz.framer-1h1g97a { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 1076px; }",
	".framer-pz0Mz .framer-1mhqcjd { align-content: flex-start; align-items: flex-start; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 32px; height: min-content; justify-content: flex-start; overflow: visible; padding: var(--1fbot2b); position: relative; width: 1px; }",
	".framer-pz0Mz .framer-1w6mdvl { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 20px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-pz0Mz .framer-y1fmcd { flex: 1 0 0px; height: auto; position: relative; white-space: pre-wrap; width: 1px; word-break: break-word; word-wrap: break-word; }",
	".framer-pz0Mz .framer-172idd0 { flex: none; height: var(--framer-aspect-ratio-supported, 24px); position: relative; width: 24px; }",
	".framer-pz0Mz .framer-engws1 { flex: none; height: auto; max-width: 700px; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	...css2,
	...css,
	'.framer-pz0Mz[data-border="true"]::after, .framer-pz0Mz [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var FramerQFecanpUy = withCSS(Component, css3, "framer-pz0Mz");
var stdin_default3 = FramerQFecanpUy;
FramerQFecanpUy.displayName = "FAQ Card";
FramerQFecanpUy.defaultProps = {
	height: 190,
	width: 1076,
};
addPropertyControls(FramerQFecanpUy, {
	variant: {
		options: ["U5H7kMV2j", "dB5vGvZub"],
		optionTitles: ["Open", "Close"],
		title: "Variant",
		type: ControlType.Enum,
	},
	SWClb3Nqz: {
		title: "Click",
		type: ControlType.EventHandler,
	},
	yioEeMfQr: {
		defaultValue: "40px",
		title: "Padding",
		type: ControlType.Padding,
	},
	fmZskzz2R: {
		defaultValue: "Speed of design delivery?",
		displayTextArea: false,
		title: "Title",
		type: ControlType.String,
	},
	O7apdCcJm: {
		defaultValue:
			"How quick is quick? For most design, we\u2019re talking 2-3 business days. We balance speed with quality,ensuring you get top-north design swiftly",
		displayTextArea: false,
		title: "Text",
		type: ControlType.String,
	},
});
addFonts(
	FramerQFecanpUy,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts2),
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:faq-card
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"1907350542b7624112d99063e9127837bac05866cdf3676335c1d928983f49a3"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default3, {
				suppressHydrationWarning: true,
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders FaqCardFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"1907350542b7624112d99063e9127837bac05866cdf3676335c1d928983f49a3"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				suppressHydrationWarning={true}
				Component={stdin_default3}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default3);
var faq_card_default = ComponentWithRoot;
export { faq_card_default as default };
