// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 1907350542b76241 "Blimpy", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop' | 'Tablet' | 'Phone' // Variant
}} Props

 */
import {
	className as className4,
	css as css4,
	fonts as fonts4,
} from "./chunks/chunk-NIQBJUGP.js";
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-CM7YMXDZ.js";
import { className, css, fonts } from "./chunks/chunk-HOM253AJ.js";
import {
	className as className3,
	css as css3,
	fonts as fonts3,
} from "./chunks/chunk-3KWTDRN7.js";
import { routes } from "./chunks/chunk-RHU4XTMM.js";

// virtual:footer
import { Fragment as Fragment3 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/j1jzf3UFtdTJ9EYrkksl/meRGL1yVvaXnQpmoW7ol/Vd2Twz8QN.js
import { jsx as _jsx2, jsxs as _jsxs2 } from "react/jsx-runtime";
import {
	addFonts as addFonts2,
	addPropertyControls as addPropertyControls2,
	ComponentViewportProvider,
	ControlType as ControlType2,
	cx as cx2,
	forwardLoader,
	getFonts,
	getFontsFromSharedStyle as getFontsFromSharedStyle2,
	getLoadingLazyAtYPosition as getLoadingLazyAtYPosition2,
	Image as Image1,
	Link as Link2,
	RichText as RichText2,
	SmartComponentScopedContainer,
	useComponentViewport as useComponentViewport2,
	useLocaleInfo as useLocaleInfo2,
	useVariantState as useVariantState2,
	withCSS as withCSS2,
	withFX,
} from "unframer";
import {
	LayoutGroup as LayoutGroup2,
	motion as motion2,
	MotionConfigContext as MotionConfigContext2,
} from "unframer";
import * as React2 from "react";
import { useRef as useRef2 } from "react";

// /:https://framerusercontent.com/modules/eaRe9DlQxzrLyGSzcy1i/WLRICvHFzEybfEIg4Dtq/DSuiubIBm.js
import { fontStore } from "unframer";
fontStore.loadFonts(["GF;Funnel Display-regular", "GF;Funnel Display-700"]);
var fonts5 = [
	{
		explicitInter: true,
		fonts: [
			{
				family: "Funnel Display",
				openType: true,
				source: "google",
				style: "normal",
				url: "https://fonts.gstatic.com/s/funneldisplay/v2/B50bF7FGv37QNVWgE0ga--4PbZSRJXrOHcLHLoAYmmPXXcVwIZDKFA.woff2",
				weight: "400",
			},
			{
				family: "Funnel Display",
				openType: true,
				source: "google",
				style: "normal",
				url: "https://fonts.gstatic.com/s/funneldisplay/v2/B50bF7FGv37QNVWgE0ga--4PbZSRJXrOHcLHLoAYfWTXXcVwIZDKFA.woff2",
				weight: "700",
			},
		],
	},
];
var css5 = [
	`.framer-m7ot1 .framer-styles-preset-o0c25d:not(.rich-text-wrapper), .framer-m7ot1 .framer-styles-preset-o0c25d.rich-text-wrapper h2 { --framer-font-family: "Funnel Display", sans-serif; --framer-font-family-bold: "Funnel Display", sans-serif; --framer-font-open-type-features: 'blwf' on, 'cv09' on, 'cv03' on, 'cv04' on, 'cv11' on; --framer-font-size: 114px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-variation-axes: normal; --framer-font-weight: 400; --framer-font-weight-bold: 700; --framer-letter-spacing: -0.06em; --framer-line-height: 90%; --framer-paragraph-spacing: 40px; --framer-text-alignment: start; --framer-text-color: var(--token-1ca63064-b503-4f13-8e66-ff201796eaf9, #ffffff); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; }`,
	`@media (max-width: 1199px) and (min-width: 810px) { .framer-m7ot1 .framer-styles-preset-o0c25d:not(.rich-text-wrapper), .framer-m7ot1 .framer-styles-preset-o0c25d.rich-text-wrapper h2 { --framer-font-family: "Funnel Display", sans-serif; --framer-font-family-bold: "Funnel Display", sans-serif; --framer-font-open-type-features: 'blwf' on, 'cv09' on, 'cv03' on, 'cv04' on, 'cv11' on; --framer-font-size: 68px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-variation-axes: normal; --framer-font-weight: 400; --framer-font-weight-bold: 700; --framer-letter-spacing: -0.06em; --framer-line-height: 90%; --framer-paragraph-spacing: 40px; --framer-text-alignment: start; --framer-text-color: var(--token-1ca63064-b503-4f13-8e66-ff201796eaf9, #ffffff); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }`,
	`@media (max-width: 809px) and (min-width: 0px) { .framer-m7ot1 .framer-styles-preset-o0c25d:not(.rich-text-wrapper), .framer-m7ot1 .framer-styles-preset-o0c25d.rich-text-wrapper h2 { --framer-font-family: "Funnel Display", sans-serif; --framer-font-family-bold: "Funnel Display", sans-serif; --framer-font-open-type-features: 'blwf' on, 'cv09' on, 'cv03' on, 'cv04' on, 'cv11' on; --framer-font-size: 42px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-variation-axes: normal; --framer-font-weight: 400; --framer-font-weight-bold: 700; --framer-letter-spacing: -0.03em; --framer-line-height: 90%; --framer-paragraph-spacing: 40px; --framer-text-alignment: start; --framer-text-color: var(--token-1ca63064-b503-4f13-8e66-ff201796eaf9, #ffffff); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }`,
];
var className5 = "framer-m7ot1";

// /:https://framerusercontent.com/modules/gXOy3MlH6ZUb2c1bFKjg/MaTznx30pER2N6x5AfI0/lPgzNAnOX.js
import { fontStore as fontStore2 } from "unframer";
fontStore2.loadFonts([
	"GF;Playfair Display-italic",
	"GF;Playfair Display-700italic",
	"GF;Playfair Display-700italic",
	"GF;Playfair Display-italic",
]);
var fonts6 = [
	{
		explicitInter: true,
		fonts: [
			{
				family: "Playfair Display",
				openType: true,
				source: "google",
				style: "italic",
				url: "https://fonts.gstatic.com/s/playfairdisplay/v39/nuFRD-vYSZviVYUb_rj3ij__anPXDTnCjmHKM4nYO7KN_qiTbtPK-F2rA0s.woff2",
				weight: "400",
			},
			{
				family: "Playfair Display",
				openType: true,
				source: "google",
				style: "italic",
				url: "https://fonts.gstatic.com/s/playfairdisplay/v39/nuFRD-vYSZviVYUb_rj3ij__anPXDTnCjmHKM4nYO7KN_k-UbtPK-F2rA0s.woff2",
				weight: "700",
			},
		],
	},
];
var css6 = [
	`.framer-4b2Pu .framer-styles-preset-1r59ug4:not(.rich-text-wrapper), .framer-4b2Pu .framer-styles-preset-1r59ug4.rich-text-wrapper h2 { --framer-font-family: "Playfair Display", "Playfair Display Placeholder", serif; --framer-font-family-bold: "Playfair Display", "Playfair Display Placeholder", serif; --framer-font-family-bold-italic: "Playfair Display", "Playfair Display Placeholder", serif; --framer-font-family-italic: "Playfair Display", "Playfair Display Placeholder", serif; --framer-font-open-type-features: 'blwf' on, 'cv09' on, 'cv03' on, 'cv04' on, 'cv11' on; --framer-font-size: 114px; --framer-font-style: italic; --framer-font-style-bold: italic; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 400; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 400; --framer-letter-spacing: -0.06em; --framer-line-height: 90%; --framer-paragraph-spacing: 40px; --framer-text-alignment: start; --framer-text-color: var(--token-1ca63064-b503-4f13-8e66-ff201796eaf9, #ffffff); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; }`,
	`@media (max-width: 1199px) and (min-width: 810px) { .framer-4b2Pu .framer-styles-preset-1r59ug4:not(.rich-text-wrapper), .framer-4b2Pu .framer-styles-preset-1r59ug4.rich-text-wrapper h2 { --framer-font-family: "Playfair Display", "Playfair Display Placeholder", serif; --framer-font-family-bold: "Playfair Display", "Playfair Display Placeholder", serif; --framer-font-family-bold-italic: "Playfair Display", "Playfair Display Placeholder", serif; --framer-font-family-italic: "Playfair Display", "Playfair Display Placeholder", serif; --framer-font-open-type-features: 'blwf' on, 'cv09' on, 'cv03' on, 'cv04' on, 'cv11' on; --framer-font-size: 68px; --framer-font-style: italic; --framer-font-style-bold: italic; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 400; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 400; --framer-letter-spacing: -0.06em; --framer-line-height: 90%; --framer-paragraph-spacing: 40px; --framer-text-alignment: start; --framer-text-color: var(--token-1ca63064-b503-4f13-8e66-ff201796eaf9, #ffffff); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }`,
	`@media (max-width: 809px) and (min-width: 0px) { .framer-4b2Pu .framer-styles-preset-1r59ug4:not(.rich-text-wrapper), .framer-4b2Pu .framer-styles-preset-1r59ug4.rich-text-wrapper h2 { --framer-font-family: "Playfair Display", "Playfair Display Placeholder", serif; --framer-font-family-bold: "Playfair Display", "Playfair Display Placeholder", serif; --framer-font-family-bold-italic: "Playfair Display", "Playfair Display Placeholder", serif; --framer-font-family-italic: "Playfair Display", "Playfair Display Placeholder", serif; --framer-font-open-type-features: 'blwf' on, 'cv09' on, 'cv03' on, 'cv04' on, 'cv11' on; --framer-font-size: 42px; --framer-font-style: italic; --framer-font-style-bold: italic; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 400; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 400; --framer-letter-spacing: -0.03em; --framer-line-height: 90%; --framer-paragraph-spacing: 40px; --framer-text-alignment: start; --framer-text-color: var(--token-1ca63064-b503-4f13-8e66-ff201796eaf9, #ffffff); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }`,
];
var className6 = "framer-4b2Pu";

// /:https://framerusercontent.com/modules/8TMKk7Ybbzzv5fBsidUR/oYpIpnx1G9RYq5AlNZUM/DBmlL1xvz.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	getLoadingLazyAtYPosition,
	Image,
	Link,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var enabledGestures = {
	hC0LQWAPc: {
		hover: true,
	},
};
var serializationHash = "framer-5uRdg";
var variantClassNames = {
	hC0LQWAPc: "framer-v-1urq3dp",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider
			suppressHydrationWarning={true}
			value={contextValue}
		>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var getProps = ({ height, id, link, title, width, ...props }) => {
	return {
		...props,
		DDX1QhrKi: title ?? props.DDX1QhrKi ?? "Instagram",
		V5M8VmxTV: link ?? props.V5M8VmxTV,
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className7,
		layoutId,
		variant,
		DDX1QhrKi,
		V5M8VmxTV,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		defaultVariant: "hC0LQWAPc",
		enabledGestures,
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className2];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup
			suppressHydrationWarning={true}
			id={layoutId ?? defaultLayoutId}
		>
			<Variants
				suppressHydrationWarning={true}
				animate={variants}
				initial={false}
			>
				<Transition suppressHydrationWarning={true} value={transition1}>
					<Link
						suppressHydrationWarning={true}
						href={V5M8VmxTV}
						motionChild={true}
						nodeId={"hC0LQWAPc"}
						openInNewTab={false}
						scopeId={"DBmlL1xvz"}
					>
						<motion.a
							suppressHydrationWarning={true}
							{...restProps}
							{...gestureHandlers}
							className={`${cx(scopingClassNames, "framer-1urq3dp", className7, classNames)} framer-186ej6u`}
							data-border={true}
							data-framer-name={"Default"}
							layoutDependency={layoutDependency}
							layoutId={"hC0LQWAPc"}
							ref={refBinding}
							style={{
								"--border-bottom-width": "1px",
								"--border-color":
									"var(--token-aad9f953-7a89-4aa6-8b88-7994cb74103e, rgba(255, 255, 255, 0.1))",
								"--border-left-width": "0px",
								"--border-right-width": "0px",
								"--border-style": "solid",
								"--border-top-width": "0px",
								...style,
							}}
							variants={{
								"hC0LQWAPc-hover": {
									"--border-color":
										"var(--token-d0efb30f-1ca4-4318-a615-3c27c4e89f33, rgb(255, 31, 0))",
								},
							}}
							{...addPropertyOverrides(
								{
									"hC0LQWAPc-hover": {
										"data-framer-name": void 0,
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<RichText
								suppressHydrationWarning={true}
								__fromCanvasComponent={true}
								className={"framer-l6mgpa"}
								data-framer-name={"Instagram"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"cXpXsKV7b"}
								style={{
									"--framer-paragraph-spacing": "0px",
								}}
								text={DDX1QhrKi}
								variants={{
									"hC0LQWAPc-hover": {
										"--extracted-r6o4lv":
											"var(--token-d0efb30f-1ca4-4318-a615-3c27c4e89f33, rgb(255, 31, 0))",
									},
								}}
								verticalAlignment={"top"}
								withExternalLayout={true}
								{...addPropertyOverrides(
									{
										"hC0LQWAPc-hover": {
											children: (
												<React.Fragment>
													<motion.p
														suppressHydrationWarning={true}
														className={"framer-styles-preset-g7itge"}
														data-styles-preset={"YyydkF6BV"}
														style={{
															"--framer-text-color":
																"var(--extracted-r6o4lv, var(--token-d0efb30f-1ca4-4318-a615-3c27c4e89f33, rgb(255, 31, 0)))",
														}}
													>
														{"Instagram"}
													</motion.p>
												</React.Fragment>
											),
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<React.Fragment>
									<motion.p
										suppressHydrationWarning={true}
										className={"framer-styles-preset-g7itge"}
										data-styles-preset={"YyydkF6BV"}
									>
										{"Instagram"}
									</motion.p>
								</React.Fragment>
							</RichText>
							<motion.div
								suppressHydrationWarning={true}
								className={"framer-15rhicy"}
								data-framer-name={"Icon Wrap"}
								layoutDependency={layoutDependency}
								layoutId={"hrQoYUAax"}
							>
								<Image
									suppressHydrationWarning={true}
									background={{
										alt: "Icon",
										fit: "fill",
										loading: getLoadingLazyAtYPosition(
											(componentViewport?.y || 0) +
												(8 +
													((componentViewport?.height || 38) - 16 - 16) / 2) +
												0,
										),
										pixelHeight: 16,
										pixelWidth: 16,
										src: "https://framerusercontent.com/images/PmjCAJo5u9oeCyTwnACNgpHXU.svg",
									}}
									className={"framer-qbc8p7"}
									layoutDependency={layoutDependency}
									layoutId={"u8UYjBu9a"}
									{...addPropertyOverrides(
										{
											"hC0LQWAPc-hover": {
												background: {
													alt: "Icon",
													fit: "fill",
													loading: getLoadingLazyAtYPosition(
														(componentViewport?.y || 0) +
															(8 +
																((componentViewport?.height || 38) - 16 - 16) /
																	2) +
															-18,
													),
													pixelHeight: 16,
													pixelWidth: 16,
													src: "https://framerusercontent.com/images/PmjCAJo5u9oeCyTwnACNgpHXU.svg",
												},
											},
										},
										baseVariant,
										gestureVariant,
									)}
								/>
								<Image
									suppressHydrationWarning={true}
									background={{
										alt: "Icon",
										fit: "fill",
										loading: getLoadingLazyAtYPosition(
											(componentViewport?.y || 0) +
												(8 +
													((componentViewport?.height || 38) - 16 - 16) / 2) +
												16 -
												-2,
										),
										pixelHeight: 16,
										pixelWidth: 16,
										src: "https://framerusercontent.com/images/XSbNMjwOQEX6uzVqkadpKX9DDE.svg",
									}}
									className={"framer-1s42za5"}
									layoutDependency={layoutDependency}
									layoutId={"mOWOYjFHa"}
									{...addPropertyOverrides(
										{
											"hC0LQWAPc-hover": {
												background: {
													alt: "Icon",
													fit: "fill",
													loading: getLoadingLazyAtYPosition(
														(componentViewport?.y || 0) +
															(8 +
																((componentViewport?.height || 38) - 16 - 16) /
																	2) +
															0,
													),
													pixelHeight: 16,
													pixelWidth: 16,
													src: "https://framerusercontent.com/images/XSbNMjwOQEX6uzVqkadpKX9DDE.svg",
												},
											},
										},
										baseVariant,
										gestureVariant,
									)}
								/>
							</motion.div>
						</motion.a>
					</Link>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css7 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-5uRdg.framer-186ej6u, .framer-5uRdg .framer-186ej6u { display: block; }",
	".framer-5uRdg.framer-1urq3dp { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; height: min-content; justify-content: space-between; max-width: 305px; overflow: hidden; padding: 8px 0px 8px 0px; position: relative; text-decoration: none; width: 305px; }",
	".framer-5uRdg .framer-l6mgpa { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-5uRdg .framer-15rhicy { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: min-content; }",
	".framer-5uRdg .framer-qbc8p7 { flex: none; height: 16px; position: relative; width: 16px; }",
	".framer-5uRdg .framer-1s42za5 { bottom: -18px; flex: none; height: 16px; left: -18px; position: absolute; width: 16px; z-index: 1; }",
	".framer-5uRdg.framer-v-1urq3dp.hover .framer-qbc8p7 { position: absolute; right: -18px; top: -18px; z-index: 1; }",
	".framer-5uRdg.framer-v-1urq3dp.hover .framer-1s42za5 { bottom: unset; left: unset; position: relative; }",
	...css2,
	'.framer-5uRdg[data-border="true"]::after, .framer-5uRdg [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var FramerDBmlL1xvz = withCSS(Component, css7, "framer-5uRdg");
var stdin_default = FramerDBmlL1xvz;
FramerDBmlL1xvz.displayName = "Social Media";
FramerDBmlL1xvz.defaultProps = {
	height: 38,
	width: 305,
};
addPropertyControls(FramerDBmlL1xvz, {
	DDX1QhrKi: {
		defaultValue: "Instagram",
		displayTextArea: false,
		title: "Title",
		type: ControlType.String,
	},
	V5M8VmxTV: {
		title: "Link",
		type: ControlType.Link,
	},
});
addFonts(
	FramerDBmlL1xvz,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts2),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// /:https://framerusercontent.com/modules/j1jzf3UFtdTJ9EYrkksl/meRGL1yVvaXnQpmoW7ol/Vd2Twz8QN.js
var SocialMediaFonts = getFonts(stdin_default);
var MotionDivWithFX = withFX(motion2.div);
var cycleOrder = ["tzXpOvRTV", "UQbx5IqQh", "GHCqrw6t8"];
var serializationHash2 = "framer-5IOyp";
var variantClassNames2 = {
	GHCqrw6t8: "framer-v-1hb2eda",
	tzXpOvRTV: "framer-v-1etn416",
	UQbx5IqQh: "framer-v-108yuo0",
};
function addPropertyOverrides2(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition12 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var transformTemplate1 = (_, t) => `translateX(-50%) ${t}`;
var animation = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 60,
};
var transition2 = {
	damping: 80,
	delay: 0,
	mass: 1,
	stiffness: 400,
	type: "spring",
};
var transition3 = {
	damping: 80,
	delay: 0.2,
	mass: 1,
	stiffness: 400,
	type: "spring",
};
var Transition2 = ({ value, children }) => {
	const config = React2.useContext(MotionConfigContext2);
	const transition = value ?? config.transition;
	const contextValue = React2.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext2.Provider
			suppressHydrationWarning={true}
			value={contextValue}
		>
			{children}
		</MotionConfigContext2.Provider>
	);
};
var humanReadableVariantMap = {
	Desktop: "tzXpOvRTV",
	Phone: "GHCqrw6t8",
	Tablet: "UQbx5IqQh",
};
var Variants2 = motion2.create(React2.Fragment);
var getProps2 = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "tzXpOvRTV",
	};
};
var createLayoutDependency2 = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component2 = /* @__PURE__ */ React2.forwardRef(function (props, ref) {
	const fallbackRef = useRef2(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React2.useId();
	const { activeLocale, setLocale } = useLocaleInfo2();
	const componentViewport = useComponentViewport2();
	const {
		style,
		className: className7,
		layoutId,
		variant,
		...restProps
	} = getProps2(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState2({
		cycleOrder,
		defaultVariant: "tzXpOvRTV",
		ref: refBinding,
		variant,
		variantClassNames: variantClassNames2,
	});
	const layoutDependency = createLayoutDependency2(props, variants);
	const sharedStyleClassNames = [
		className5,
		className6,
		className4,
		className3,
		className,
	];
	const scopingClassNames = cx2(serializationHash2, ...sharedStyleClassNames);
	return (
		<LayoutGroup2
			suppressHydrationWarning={true}
			id={layoutId ?? defaultLayoutId}
		>
			<Variants2
				suppressHydrationWarning={true}
				animate={variants}
				initial={false}
			>
				<Transition2 suppressHydrationWarning={true} value={transition12}>
					<Image1
						suppressHydrationWarning={true}
						{...restProps}
						{...gestureHandlers}
						as={"footer"}
						background={{
							alt: "Bg Image",
							fit: "fill",
							loading: getLoadingLazyAtYPosition2(componentViewport?.y || 0),
							pixelHeight: 1350,
							pixelWidth: 2844,
							sizes: componentViewport?.width || "100vw",
							src: "https://framerusercontent.com/images/eEIO1zKX7p2sMKbFhj62UopB0LE.png?width=2844&height=1350",
							srcSet:
								"https://framerusercontent.com/images/eEIO1zKX7p2sMKbFhj62UopB0LE.png?scale-down-to=512&width=2844&height=1350 512w,https://framerusercontent.com/images/eEIO1zKX7p2sMKbFhj62UopB0LE.png?scale-down-to=1024&width=2844&height=1350 1024w,https://framerusercontent.com/images/eEIO1zKX7p2sMKbFhj62UopB0LE.png?scale-down-to=2048&width=2844&height=1350 2048w,https://framerusercontent.com/images/eEIO1zKX7p2sMKbFhj62UopB0LE.png?width=2844&height=1350 2844w",
						}}
						className={cx2(
							scopingClassNames,
							"framer-1etn416",
							className7,
							classNames,
						)}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"tzXpOvRTV"}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides2(
							{
								GHCqrw6t8: {
									"data-framer-name": "Phone",
								},
								UQbx5IqQh: {
									"data-framer-name": "Tablet",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion2.div
							suppressHydrationWarning={true}
							className={"framer-1f60a62"}
							data-framer-name={"Shape Top"}
							layoutDependency={layoutDependency}
							layoutId={"qr3uLfpWv"}
							style={{
								background:
									"linear-gradient(180deg, rgba(18, 18, 18, 0) 0%, rgb(18, 18, 18) 100%)",
								rotate: -180,
							}}
							transformTemplate={transformTemplate1}
						/>
						<motion2.div
							suppressHydrationWarning={true}
							className={"framer-d6c4xo"}
							data-framer-name={"Container"}
							layoutDependency={layoutDependency}
							layoutId={"E4U8a0zH0"}
						>
							<MotionDivWithFX
								suppressHydrationWarning={true}
								__framer__animate={{
									transition: transition2,
								}}
								__framer__animateOnce={true}
								__framer__enter={animation}
								__framer__styleAppearEffectEnabled={true}
								__framer__threshold={0.5}
								__perspectiveFX={false}
								__smartComponentFX={true}
								__targetOpacity={1}
								className={"framer-9p92ji"}
								data-framer-name={"Content Top"}
								layoutDependency={layoutDependency}
								layoutId={"DDwAm73uS"}
							>
								<motion2.div
									suppressHydrationWarning={true}
									className={"framer-1704do7"}
									data-framer-name={"Section TItle"}
									layoutDependency={layoutDependency}
									layoutId={"iJ1RIeGXJ"}
								>
									<RichText2
										suppressHydrationWarning={true}
										__fromCanvasComponent={true}
										className={"framer-1gawcvi"}
										data-framer-name={"Explore / Services"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"pBEOhUgL_"}
										style={{
											"--extracted-1of0zx5":
												"var(--token-d0efb30f-1ca4-4318-a615-3c27c4e89f33, rgb(255, 31, 0))",
											"--framer-paragraph-spacing": "0px",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React2.Fragment>
											<motion2.h2
												suppressHydrationWarning={true}
												className={"framer-styles-preset-o0c25d"}
												data-styles-preset={"DSuiubIBm"}
												style={{
													"--framer-text-color":
														"var(--extracted-1of0zx5, var(--token-d0efb30f-1ca4-4318-a615-3c27c4e89f33, rgb(255, 31, 0)))",
												}}
											>
												{"Let\u2019s"}
											</motion2.h2>
										</React2.Fragment>
									</RichText2>
									<RichText2
										suppressHydrationWarning={true}
										__fromCanvasComponent={true}
										className={"framer-48sg54"}
										data-framer-name={"Explore / Services"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"HkZnGCXTg"}
										style={{
											"--extracted-1of0zx5":
												"var(--token-d0efb30f-1ca4-4318-a615-3c27c4e89f33, rgb(255, 31, 0))",
											"--framer-paragraph-spacing": "0px",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React2.Fragment>
											<motion2.h2
												suppressHydrationWarning={true}
												className={"framer-styles-preset-1r59ug4"}
												data-styles-preset={"lPgzNAnOX"}
												style={{
													"--framer-text-color":
														"var(--extracted-1of0zx5, var(--token-d0efb30f-1ca4-4318-a615-3c27c4e89f33, rgb(255, 31, 0)))",
												}}
											>
												{"Talk"}
											</motion2.h2>
										</React2.Fragment>
									</RichText2>
									<div style={{ flexBasis: "100%", width: "100%", marginTop: "16px" }}>
									<a
										href="/contact"
										style={{
											display: "inline-flex",
											alignItems: "center",
											gap: "6px",
											width: "fit-content",
											textDecoration: "none",
											color: "#fff",
											fontSize: "14px",
											fontFamily: "Funnel Display, sans-serif",
											border: "1px solid rgba(255,255,255,0.3)",
											padding: "12px 24px",
										}}
									>
										[ Contact Us ]
									</a>
									</div>
								</motion2.div>
								<motion2.div
									suppressHydrationWarning={true}
									className={"framer-1kl8o5b"}
									data-framer-name={"List"}
									layoutDependency={layoutDependency}
									layoutId={"OpUrVHtTi"}
								>
									<ComponentViewportProvider
										suppressHydrationWarning={true}
										height={38}
										width={`min(max((min(max(${componentViewport?.width || "100vw"} - 60px, 1px), 1296px) - 10px) / 2, 1px), 305px)`}
										{...addPropertyOverrides2(
											{
												GHCqrw6t8: {
													width: `min(min(max(${componentViewport?.width || "100vw"} - 40px, 1px), 1296px), 305px)`,
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										<SmartComponentScopedContainer
											suppressHydrationWarning={true}
											className={"framer-1cma9oe-container"}
											layoutDependency={layoutDependency}
											layoutId={"Qoq49O8Cn-container"}
											nodeId={"Qoq49O8Cn"}
											rendersWithMotion={true}
											scopeId={"Vd2Twz8QN"}
										>
											{_jsx2(stdin_default, {
												suppressHydrationWarning: true,
												DDX1QhrKi: "Instagram",
												height: "100%",
												id: "Qoq49O8Cn",
												layoutId: "Qoq49O8Cn",
												style: {
													width: "100%",
												},
												V5M8VmxTV: "https://www.instagram.com/blimpykenya/",
												width: "100%",
											})}
										</SmartComponentScopedContainer>
									</ComponentViewportProvider>
									<ComponentViewportProvider
										suppressHydrationWarning={true}
										height={38}
										width={`min(max((min(max(${componentViewport?.width || "100vw"} - 60px, 1px), 1296px) - 10px) / 2, 1px), 305px)`}
										{...addPropertyOverrides2(
											{
												GHCqrw6t8: {
													width: `min(min(max(${componentViewport?.width || "100vw"} - 40px, 1px), 1296px), 305px)`,
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										<SmartComponentScopedContainer
											suppressHydrationWarning={true}
											className={"framer-1pzwml6-container"}
											layoutDependency={layoutDependency}
											layoutId={"RZkeduis8-container"}
											nodeId={"RZkeduis8"}
											rendersWithMotion={true}
											scopeId={"Vd2Twz8QN"}
										>
											{_jsx2(stdin_default, {
												suppressHydrationWarning: true,
												DDX1QhrKi: "Facebook",
												height: "100%",
												id: "RZkeduis8",
												layoutId: "RZkeduis8",
												style: {
													width: "100%",
												},
												V5M8VmxTV: "https://www.facebook.com/blimpyke",
												width: "100%",
											})}
										</SmartComponentScopedContainer>
									</ComponentViewportProvider>
									<ComponentViewportProvider
										suppressHydrationWarning={true}
										height={38}
										width={`min(max((min(max(${componentViewport?.width || "100vw"} - 60px, 1px), 1296px) - 10px) / 2, 1px), 305px)`}
										{...addPropertyOverrides2(
											{
												GHCqrw6t8: {
													width: `min(min(max(${componentViewport?.width || "100vw"} - 40px, 1px), 1296px), 305px)`,
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										<SmartComponentScopedContainer
											suppressHydrationWarning={true}
											className={"framer-1i2pwqa-container"}
											layoutDependency={layoutDependency}
											layoutId={"tgZEACz87-container"}
											nodeId={"tgZEACz87"}
											rendersWithMotion={true}
											scopeId={"Vd2Twz8QN"}
										>
											{_jsx2(stdin_default, {
												suppressHydrationWarning: true,
												DDX1QhrKi: "LinkedIN",
												height: "100%",
												id: "tgZEACz87",
												layoutId: "tgZEACz87",
												style: {
													width: "100%",
												},
												V5M8VmxTV:
													"https://www.linkedin.com/company/blimpy-kenya/?viewAsMember=true",
												width: "100%",
											})}
										</SmartComponentScopedContainer>
									</ComponentViewportProvider>
								</motion2.div>
							</MotionDivWithFX>
							<MotionDivWithFX
								suppressHydrationWarning={true}
								__framer__animate={{
									transition: transition3,
								}}
								__framer__animateOnce={true}
								__framer__enter={animation}
								__framer__styleAppearEffectEnabled={true}
								__framer__threshold={0.5}
								__perspectiveFX={false}
								__smartComponentFX={true}
								__targetOpacity={1}
								className={"framer-1sxf1m1"}
								data-framer-name={"Content Bottom"}
								layoutDependency={layoutDependency}
								layoutId={"W7gT6vPj1"}
							>
								<motion2.div
									suppressHydrationWarning={true}
									className={"framer-cajq3t"}
									data-border={true}
									data-framer-name={"Navitem Wrapper"}
									layoutDependency={layoutDependency}
									layoutId={"UxSsWL1ct"}
									style={{
										"--border-bottom-width": "1px",
										"--border-color":
											"var(--token-aad9f953-7a89-4aa6-8b88-7994cb74103e, rgba(255, 255, 255, 0.1))",
										"--border-left-width": "0px",
										"--border-right-width": "0px",
										"--border-style": "solid",
										"--border-top-width": "0px",
									}}
								>
									<RichText2
										suppressHydrationWarning={true}
										__fromCanvasComponent={true}
										className={"framer-88874l"}
										data-framer-name={"About"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"BJNzhgp68"}
										style={{
											"--framer-paragraph-spacing": "0px",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React2.Fragment>
											<motion2.h4
												suppressHydrationWarning={true}
												className={"framer-styles-preset-18sh6u4"}
												data-styles-preset={"irLh2xjGn"}
											>
												<Link2
													suppressHydrationWarning={true}
													href={{
														webPageId: "RQDxPx6hw",
													}}
													motionChild={true}
													nodeId={"BJNzhgp68"}
													openInNewTab={false}
													relValues={[]}
													scopeId={"Vd2Twz8QN"}
													smoothScroll={false}
												>
													<motion2.a
														suppressHydrationWarning={true}
														className={"framer-styles-preset-1bttbk4"}
														data-styles-preset={"fIzGNCa20"}
													>
														{"About"}
													</motion2.a>
												</Link2>
											</motion2.h4>
										</React2.Fragment>
									</RichText2>
									<RichText2
										suppressHydrationWarning={true}
										__fromCanvasComponent={true}
										className={"framer-w5zdq9"}
										data-framer-name={"About"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"hbkyYDp_K"}
										style={{
											"--framer-paragraph-spacing": "0px",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React2.Fragment>
											<motion2.h4
												suppressHydrationWarning={true}
												className={"framer-styles-preset-18sh6u4"}
												data-styles-preset={"irLh2xjGn"}
											>
												<Link2
													suppressHydrationWarning={true}
													href={{
														webPageId: "u9OaG82Gv",
													}}
													motionChild={true}
													nodeId={"hbkyYDp_K"}
													openInNewTab={false}
													relValues={[]}
													scopeId={"Vd2Twz8QN"}
													smoothScroll={false}
												>
													<motion2.a
														suppressHydrationWarning={true}
														className={"framer-styles-preset-1bttbk4"}
														data-styles-preset={"fIzGNCa20"}
													>
														{"Pricing"}
													</motion2.a>
												</Link2>
											</motion2.h4>
										</React2.Fragment>
									</RichText2>
									<RichText2
										suppressHydrationWarning={true}
										__fromCanvasComponent={true}
										className={"framer-1bjr7nb"}
										data-framer-name={"About"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"dH7cQlCdH"}
										style={{
											"--framer-paragraph-spacing": "0px",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React2.Fragment>
											<motion2.h4
												suppressHydrationWarning={true}
												className={"framer-styles-preset-18sh6u4"}
												data-styles-preset={"irLh2xjGn"}
											>
												<Link2
													suppressHydrationWarning={true}
													href={{
														webPageId: "cSNrfMpv9",
													}}
													motionChild={true}
													nodeId={"dH7cQlCdH"}
													openInNewTab={false}
													relValues={[]}
													scopeId={"Vd2Twz8QN"}
													smoothScroll={false}
												>
													<motion2.a
														suppressHydrationWarning={true}
														className={"framer-styles-preset-1bttbk4"}
														data-styles-preset={"fIzGNCa20"}
													>
														{"Work"}
													</motion2.a>
												</Link2>
											</motion2.h4>
										</React2.Fragment>
									</RichText2>
									<RichText2
										suppressHydrationWarning={true}
										__fromCanvasComponent={true}
										className={"framer-1hwpanj"}
										data-framer-name={"About"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"tni3ChPQe"}
										style={{
											"--framer-paragraph-spacing": "0px",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React2.Fragment>
											<motion2.h4
												suppressHydrationWarning={true}
												className={"framer-styles-preset-18sh6u4"}
												data-styles-preset={"irLh2xjGn"}
											>
												<Link2
													suppressHydrationWarning={true}
													href={{
														webPageId: "UTLV1yaoB",
													}}
													motionChild={true}
													nodeId={"tni3ChPQe"}
													openInNewTab={false}
													relValues={[]}
													scopeId={"Vd2Twz8QN"}
													smoothScroll={false}
												>
													<motion2.a
														suppressHydrationWarning={true}
														className={"framer-styles-preset-1bttbk4"}
														data-styles-preset={"fIzGNCa20"}
													>
														{"Blogs"}
													</motion2.a>
												</Link2>
											</motion2.h4>
										</React2.Fragment>
									</RichText2>
									<RichText2
										suppressHydrationWarning={true}
										__fromCanvasComponent={true}
										className={"framer-t1hdsd"}
										data-framer-name={"About"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"Pok5gviRq"}
										style={{
											"--framer-paragraph-spacing": "0px",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React2.Fragment>
											<motion2.h4
												suppressHydrationWarning={true}
												className={"framer-styles-preset-18sh6u4"}
												data-styles-preset={"irLh2xjGn"}
											>
												<Link2
													suppressHydrationWarning={true}
													href={{
														webPageId: "scp6P2hi5",
													}}
													motionChild={true}
													nodeId={"Pok5gviRq"}
													openInNewTab={false}
													relValues={[]}
													scopeId={"Vd2Twz8QN"}
													smoothScroll={false}
												>
													<motion2.a
														suppressHydrationWarning={true}
														className={"framer-styles-preset-1bttbk4"}
														data-styles-preset={"fIzGNCa20"}
													>
														{"Contact"}
													</motion2.a>
												</Link2>
											</motion2.h4>
										</React2.Fragment>
									</RichText2>
								</motion2.div>
								<motion2.div
									suppressHydrationWarning={true}
									className={"framer-7gc67r"}
									data-framer-name={"Bottom Text"}
									layoutDependency={layoutDependency}
									layoutId={"jZ3ViZFR0"}
								>
									<RichText2
										suppressHydrationWarning={true}
										__fromCanvasComponent={true}
										className={"framer-ayqxet"}
										data-framer-name={"\xA9 2025 Copyright - Logo"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"EPbr5iCsx"}
										style={{
											"--extracted-r6o4lv":
												"var(--token-1ca63064-b503-4f13-8e66-ff201796eaf9, rgb(255, 255, 255))",
											"--framer-paragraph-spacing": "0px",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
										{...addPropertyOverrides2(
											{
												GHCqrw6t8: {
													children: (
														<React2.Fragment>
															<motion2.p
																suppressHydrationWarning={true}
																className={"framer-styles-preset-1pqja7q"}
																data-styles-preset={"NjephaS6C"}
																dir={"auto"}
																style={{
																	"--framer-text-alignment": "center",
																	"--framer-text-color":
																		"var(--extracted-r6o4lv, var(--token-1ca63064-b503-4f13-8e66-ff201796eaf9, rgb(255, 255, 255)))",
																}}
															>
																{"\xA9 2026 Copyright - Blimpy"}
															</motion2.p>
														</React2.Fragment>
													),
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										<React2.Fragment>
											<motion2.p
												suppressHydrationWarning={true}
												className={"framer-styles-preset-1pqja7q"}
												data-styles-preset={"NjephaS6C"}
												dir={"auto"}
												style={{
													"--framer-text-color":
														"var(--extracted-r6o4lv, var(--token-1ca63064-b503-4f13-8e66-ff201796eaf9, rgb(255, 255, 255)))",
												}}
											>
												{"\xA9 2026 Copyright - Blimpy"}
											</motion2.p>
										</React2.Fragment>
									</RichText2>
									<RichText2
										suppressHydrationWarning={true}
										__fromCanvasComponent={true}
										className={"framer-pfwt54"}
										data-framer-name={"\xA9 2025 Copyright - Logo"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"EqV1xXugE"}
										style={{
											"--extracted-r6o4lv":
												"var(--token-1ca63064-b503-4f13-8e66-ff201796eaf9, rgb(255, 255, 255))",
											"--framer-paragraph-spacing": "0px",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
										{...addPropertyOverrides2(
											{
												GHCqrw6t8: {
													children: (
														<React2.Fragment>
															<motion2.p
																suppressHydrationWarning={true}
																className={"framer-styles-preset-1pqja7q"}
																data-styles-preset={"NjephaS6C"}
																style={{
																	"--framer-text-alignment": "center",
																	"--framer-text-color":
																		"var(--extracted-r6o4lv, var(--token-1ca63064-b503-4f13-8e66-ff201796eaf9, rgb(255, 255, 255)))",
																}}
															>
																{"All rights reserved."}
															</motion2.p>
														</React2.Fragment>
													),
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										<React2.Fragment>
											<motion2.p
												suppressHydrationWarning={true}
												className={"framer-styles-preset-1pqja7q"}
												data-styles-preset={"NjephaS6C"}
												style={{
													"--framer-text-color":
														"var(--extracted-r6o4lv, var(--token-1ca63064-b503-4f13-8e66-ff201796eaf9, rgb(255, 255, 255)))",
												}}
											>
												{"All rights reserved."}
											</motion2.p>
										</React2.Fragment>
									</RichText2>
								</motion2.div>
							</MotionDivWithFX>
						</motion2.div>
					</Image1>
				</Transition2>
			</Variants2>
		</LayoutGroup2>
	);
});
var css8 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-5IOyp.framer-n2qw5c, .framer-5IOyp .framer-n2qw5c { display: block; }",
	".framer-5IOyp.framer-1etn416 { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 80px 30px 30px 30px; position: relative; width: 1200px; will-change: var(--framer-will-change-filter-override, filter); }",
	".framer-5IOyp .framer-1f60a62 { aspect-ratio: 9.35064935064935 / 1; flex: none; gap: 0px; height: var(--framer-aspect-ratio-supported, 128px); left: 50%; overflow: hidden; position: absolute; top: 0px; width: 100%; z-index: 1; }",
	".framer-5IOyp .framer-d6c4xo { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 144px; height: min-content; justify-content: center; max-width: 1296px; overflow: hidden; padding: 0px; position: relative; width: 1px; z-index: 3; }",
	".framer-5IOyp .framer-9p92ji { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; height: min-content; justify-content: space-between; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-5IOyp .framer-1704do7 { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: wrap; gap: 10px; height: min-content; justify-content: flex-start; max-width: 500px; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	".framer-5IOyp .framer-1gawcvi, .framer-5IOyp .framer-48sg54, .framer-5IOyp .framer-88874l, .framer-5IOyp .framer-w5zdq9, .framer-5IOyp .framer-1bjr7nb, .framer-5IOyp .framer-1hwpanj, .framer-5IOyp .framer-t1hdsd, .framer-5IOyp .framer-ayqxet, .framer-5IOyp .framer-pfwt54 { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-5IOyp .framer-1kl8o5b { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; max-width: 305px; overflow: hidden; padding: 0px; position: relative; width: 1px; }",
	".framer-5IOyp .framer-1cma9oe-container, .framer-5IOyp .framer-1pzwml6-container, .framer-5IOyp .framer-1i2pwqa-container { flex: none; height: auto; position: relative; width: 100%; }",
	".framer-5IOyp .framer-1sxf1m1 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 48px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-5IOyp .framer-cajq3t { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; height: min-content; justify-content: space-between; overflow: hidden; padding: 0px 0px 40px 0px; position: relative; width: 100%; }",
	".framer-5IOyp .framer-7gc67r { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; height: min-content; justify-content: space-between; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-5IOyp.framer-v-108yuo0.framer-1etn416 { width: 810px; }",
	".framer-5IOyp.framer-v-108yuo0 .framer-1f60a62 { height: var(--framer-aspect-ratio-supported, 87px); }",
	".framer-5IOyp.framer-v-108yuo0 .framer-d6c4xo { gap: 80px; }",
	".framer-5IOyp.framer-v-1hb2eda.framer-1etn416 { padding: 60px 20px 30px 20px; width: 390px; }",
	".framer-5IOyp.framer-v-1hb2eda .framer-1f60a62 { height: var(--framer-aspect-ratio-supported, 42px); }",
	".framer-5IOyp.framer-v-1hb2eda .framer-d6c4xo { gap: 40px; }",
	".framer-5IOyp.framer-v-1hb2eda .framer-9p92ji { flex-direction: column; gap: 24px; justify-content: center; }",
	".framer-5IOyp.framer-v-1hb2eda .framer-1704do7, .framer-5IOyp.framer-v-1hb2eda .framer-1kl8o5b { flex: none; width: 100%; }",
	".framer-5IOyp.framer-v-1hb2eda .framer-1sxf1m1 { gap: 30px; }",
	".framer-5IOyp.framer-v-1hb2eda .framer-cajq3t { align-content: unset; align-items: unset; display: grid; gap: 20px 10px; grid-auto-rows: minmax(0, 1fr); grid-template-columns: repeat(2, minmax(50px, 1fr)); grid-template-rows: repeat(2, minmax(0, 1fr)); justify-content: center; }",
	".framer-5IOyp.framer-v-1hb2eda .framer-88874l, .framer-5IOyp.framer-v-1hb2eda .framer-w5zdq9, .framer-5IOyp.framer-v-1hb2eda .framer-1bjr7nb, .framer-5IOyp.framer-v-1hb2eda .framer-1hwpanj, .framer-5IOyp.framer-v-1hb2eda .framer-t1hdsd { align-self: start; justify-self: start; width: 100%; }",
	".framer-5IOyp.framer-v-1hb2eda .framer-7gc67r { flex-direction: column; gap: 15px; justify-content: center; }",
	".framer-5IOyp.framer-v-1hb2eda .framer-ayqxet, .framer-5IOyp.framer-v-1hb2eda .framer-pfwt54 { white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	...css5,
	...css6,
	...css4,
	...css3,
	...css,
	'.framer-5IOyp[data-border="true"]::after, .framer-5IOyp [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; corner-shape: inherit; pointer-events: none; }',
];
var FramerVd2Twz8QN = withCSS2(Component2, css8, "framer-5IOyp");
var stdin_default2 = FramerVd2Twz8QN;
FramerVd2Twz8QN.displayName = "Footer";
FramerVd2Twz8QN.defaultProps = {
	height: 521,
	width: 1200,
};
addPropertyControls2(FramerVd2Twz8QN, {
	variant: {
		options: ["tzXpOvRTV", "UQbx5IqQh", "GHCqrw6t8"],
		optionTitles: ["Desktop", "Tablet", "Phone"],
		title: "Variant",
		type: ControlType2.Enum,
	},
});
addFonts2(
	FramerVd2Twz8QN,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...SocialMediaFonts,
		...getFontsFromSharedStyle2(fonts5),
		...getFontsFromSharedStyle2(fonts6),
		...getFontsFromSharedStyle2(fonts4),
		...getFontsFromSharedStyle2(fonts3),
		...getFontsFromSharedStyle2(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);
FramerVd2Twz8QN.loader = {
	load: (props, context) => {
		const locale = context.locale;
		return Promise.allSettled([forwardLoader(stdin_default, {}, context)]);
	},
};

// virtual:footer
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"1907350542b7624112d99063e9127837bac05866cdf3676335c1d928983f49a3"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				suppressHydrationWarning: true,
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders FooterFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"1907350542b7624112d99063e9127837bac05866cdf3676335c1d928983f49a3"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				suppressHydrationWarning={true}
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var footer_default = ComponentWithRoot;
export { footer_default as default };
