// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 1907350542b76241 "Blimpy", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Active Black' | 'Hover Black' // Variant
 * text?: string // Text
 * link?: string // Link
 * newTab?: boolean // New Tab
 * click?: Function // Click
}} Props

 */
import { className, css, fonts } from "./chunks/chunk-3BMQMX7N.js";
import { routes } from "./chunks/chunk-RHU4XTMM.js";

// virtual:header-link
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/5gIkYVvrgrE2wrUQlBsV/Cvw3LU4sdAGhe4mIQxfk/Hp3dwTyz8.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	Link,
	RichText,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var cycleOrder = ["F94DFXEoR", "Tb01XJFc1"];
var serializationHash = "framer-lLQ91";
var variantClassNames = {
	F94DFXEoR: "framer-v-50409y",
	Tb01XJFc1: "framer-v-1lbt9kn",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	delay: 0,
	duration: 0.3,
	ease: [0.44, 0, 0.56, 1],
	type: "tween",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider
			suppressHydrationWarning={true}
			value={contextValue}
		>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	"Active Black": "F94DFXEoR",
	"Hover Black": "Tb01XJFc1",
};
var getProps = ({ click, height, id, link, newTab, text, width, ...props }) => {
	return {
		...props,
		FnN7QMPPn: link ?? props.FnN7QMPPn,
		mI6oZRx4O: newTab ?? props.mI6oZRx4O,
		u6xJQL7IM: click ?? props.u6xJQL7IM,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "F94DFXEoR",
		vGXE0kCu3: text ?? props.vGXE0kCu3 ?? "Home",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		vGXE0kCu3,
		FnN7QMPPn,
		mI6oZRx4O,
		u6xJQL7IM,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "F94DFXEoR",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onTap163hbfu = activeVariantCallback(async (...args) => {
		setGestureState({
			isPressed: false,
		});
		if (u6xJQL7IM) {
			const res = await u6xJQL7IM(...args);
			if (res === false) return false;
		}
	});
	const onMouseEnter5m2j9e = activeVariantCallback(async (...args) => {
		setGestureState({
			isHovered: true,
		});
		setVariant("Tb01XJFc1");
	});
	const onMouseLeave2toyvj = activeVariantCallback(async (...args) => {
		setGestureState({
			isHovered: false,
		});
		setVariant("F94DFXEoR");
	});
	const sharedStyleClassNames = [className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup
			suppressHydrationWarning={true}
			id={layoutId ?? defaultLayoutId}
		>
			<Variants
				suppressHydrationWarning={true}
				animate={variants}
				initial={false}
			>
				<Transition suppressHydrationWarning={true} value={transition1}>
					<Link
						suppressHydrationWarning={true}
						href={FnN7QMPPn}
						motionChild={true}
						nodeId={"F94DFXEoR"}
						openInNewTab={mI6oZRx4O}
						scopeId={"Hp3dwTyz8"}
						smoothScroll={true}
					>
						<motion.a
							suppressHydrationWarning={true}
							{...restProps}
							{...gestureHandlers}
							className={`${cx(scopingClassNames, "framer-50409y", className2, classNames)} framer-17aar40`}
							data-framer-name={"Active Black"}
							data-highlight={true}
							layoutDependency={layoutDependency}
							layoutId={"F94DFXEoR"}
							onMouseEnter={onMouseEnter5m2j9e}
							onTap={onTap163hbfu}
							ref={refBinding}
							style={{
								...style,
							}}
							{...addPropertyOverrides(
								{
									Tb01XJFc1: {
										"data-framer-name": "Hover Black",
										onMouseEnter: void 0,
										onMouseLeave: onMouseLeave2toyvj,
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<motion.div
								suppressHydrationWarning={true}
								className={"framer-1xqumx6"}
								data-framer-name={"Text Wrapper"}
								layoutDependency={layoutDependency}
								layoutId={"UmnUBudJi"}
							>
								<RichText
									suppressHydrationWarning={true}
									__fromCanvasComponent={true}
									className={"framer-11z5042"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"kaWn5bCpq"}
									style={{
										"--extracted-a0htzi":
											"var(--token-1ca63064-b503-4f13-8e66-ff201796eaf9, rgb(255, 255, 255))",
										"--framer-paragraph-spacing": "0px",
									}}
									text={vGXE0kCu3}
									variants={{
										Tb01XJFc1: {
											"--extracted-a0htzi":
												"var(--token-d0efb30f-1ca4-4318-a615-3c27c4e89f33, rgb(255, 31, 0))",
										},
									}}
									verticalAlignment={"center"}
									withExternalLayout={true}
									{...addPropertyOverrides(
										{
											Tb01XJFc1: {
												children: (
													<React.Fragment>
														<motion.h3
															suppressHydrationWarning={true}
															className={"framer-styles-preset-a2lo6d"}
															data-styles-preset={"ktfEo2_Aj"}
															style={{
																"--framer-text-alignment": "center",
																"--framer-text-color":
																	"var(--extracted-a0htzi, var(--token-d0efb30f-1ca4-4318-a615-3c27c4e89f33, rgb(255, 31, 0)))",
															}}
														>
															{"Home"}
														</motion.h3>
													</React.Fragment>
												),
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<React.Fragment>
										<motion.h3
											suppressHydrationWarning={true}
											className={"framer-styles-preset-a2lo6d"}
											data-styles-preset={"ktfEo2_Aj"}
											style={{
												"--framer-text-alignment": "center",
												"--framer-text-color":
													"var(--extracted-a0htzi, var(--token-1ca63064-b503-4f13-8e66-ff201796eaf9, rgb(255, 255, 255)))",
											}}
										>
											{"Home"}
										</motion.h3>
									</React.Fragment>
								</RichText>
							</motion.div>
							<motion.div
								suppressHydrationWarning={true}
								className={"framer-l4zedd"}
								data-framer-name={"Line Wrapper"}
								layoutDependency={layoutDependency}
								layoutId={"M54ngJI6A"}
							>
								<motion.div
									suppressHydrationWarning={true}
									className={"framer-17j5tyh"}
									data-framer-name={"Horizontal Divider"}
									layoutDependency={layoutDependency}
									layoutId={"yS2MkTIGo"}
									style={{
										backgroundColor:
											"var(--token-d0efb30f-1ca4-4318-a615-3c27c4e89f33, rgb(255, 31, 0))",
										opacity: 0,
									}}
									variants={{
										Tb01XJFc1: {
											opacity: 1,
										},
									}}
								/>
							</motion.div>
						</motion.a>
					</Link>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css2 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-lLQ91.framer-17aar40, .framer-lLQ91 .framer-17aar40 { display: block; }",
	".framer-lLQ91.framer-50409y { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 3px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; text-decoration: none; width: min-content; }",
	".framer-lLQ91 .framer-1xqumx6 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: min-content; }",
	".framer-lLQ91 .framer-11z5042 { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-lLQ91 .framer-l4zedd { align-content: center; align-items: center; align-self: stretch; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 1px; justify-content: center; overflow: visible; padding: 0px; position: relative; width: auto; }",
	".framer-lLQ91 .framer-17j5tyh { bottom: 0px; flex: none; height: 1px; left: calc(50.476190476190496% - 1px / 2); position: absolute; width: 1px; z-index: 1; }",
	".framer-lLQ91.framer-v-1lbt9kn .framer-1xqumx6 { justify-content: flex-end; }",
	".framer-lLQ91.framer-v-1lbt9kn .framer-17j5tyh { left: calc(49.52380952380955% - 100% / 2); width: 100%; }",
	...css,
];
var FramerHp3dwTyz8 = withCSS(Component, css2, "framer-lLQ91");
var stdin_default = FramerHp3dwTyz8;
FramerHp3dwTyz8.displayName = "Header Link";
FramerHp3dwTyz8.defaultProps = {
	height: 66,
	width: 162,
};
addPropertyControls(FramerHp3dwTyz8, {
	variant: {
		options: ["F94DFXEoR", "Tb01XJFc1"],
		optionTitles: ["Active Black", "Hover Black"],
		title: "Variant",
		type: ControlType.Enum,
	},
	vGXE0kCu3: {
		defaultValue: "Home",
		displayTextArea: false,
		title: "Text",
		type: ControlType.String,
	},
	FnN7QMPPn: {
		title: "Link",
		type: ControlType.Link,
	},
	mI6oZRx4O: {
		defaultValue: false,
		title: "New Tab",
		type: ControlType.Boolean,
	},
	u6xJQL7IM: {
		title: "Click",
		type: ControlType.EventHandler,
	},
});
addFonts(
	FramerHp3dwTyz8,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:header-link
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"1907350542b7624112d99063e9127837bac05866cdf3676335c1d928983f49a3"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				suppressHydrationWarning: true,
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders HeaderLinkFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"1907350542b7624112d99063e9127837bac05866cdf3676335c1d928983f49a3"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				suppressHydrationWarning={true}
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var header_link_default = ComponentWithRoot;
export { header_link_default as default };
