// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 1907350542b76241 "Blimpy", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Line Inactive' | 'Line Active' // Variant
 * fill?: string // Fill
}} Props

 */
import { routes } from "./chunks/chunk-RHU4XTMM.js";

// virtual:line
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/7I4tMLw9Ok9NVuZm0F62/GPVWtYcTDTAMj61Jrbf7/veQWYc4l0.js
import { jsx as _jsx } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var cycleOrder = ["gP9_qiu9b", "MjvYzj7Y5"];
var serializationHash = "framer-vT2k1";
var variantClassNames = {
	gP9_qiu9b: "framer-v-17zutcw",
	MjvYzj7Y5: "framer-v-f2n5b8",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	damping: 60,
	delay: 0,
	mass: 1,
	stiffness: 400,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider
			suppressHydrationWarning={true}
			value={contextValue}
		>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	"Line Active": "MjvYzj7Y5",
	"Line Inactive": "gP9_qiu9b",
};
var getProps = ({ fill, height, id, width, ...props }) => {
	return {
		...props,
		ecP1TkFsy:
			fill ??
			props.ecP1TkFsy ??
			"var(--token-1ca63064-b503-4f13-8e66-ff201796eaf9, rgb(255, 255, 255))",
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "gP9_qiu9b",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const { style, className, layoutId, variant, ecP1TkFsy, ...restProps } =
		getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "gP9_qiu9b",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup
			suppressHydrationWarning={true}
			id={layoutId ?? defaultLayoutId}
		>
			<Variants
				suppressHydrationWarning={true}
				animate={variants}
				initial={false}
			>
				<Transition suppressHydrationWarning={true} value={transition1}>
					<motion.div
						suppressHydrationWarning={true}
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-17zutcw",
							className,
							classNames,
						)}
						data-framer-name={"Line Inactive"}
						layoutDependency={layoutDependency}
						layoutId={"gP9_qiu9b"}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								MjvYzj7Y5: {
									"data-framer-name": "Line Active",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							suppressHydrationWarning={true}
							className={"framer-3t5668"}
							data-framer-name={"Fill"}
							layoutDependency={layoutDependency}
							layoutId={"LDx1OB3o7"}
							style={{
								backgroundColor: ecP1TkFsy,
							}}
						/>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-vT2k1.framer-kvslh6, .framer-vT2k1 .framer-kvslh6 { display: block; }",
	".framer-vT2k1.framer-17zutcw { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; width: 1200px; }",
	".framer-vT2k1 .framer-3t5668 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 1px; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 0%; }",
	".framer-vT2k1.framer-v-f2n5b8 .framer-3t5668 { width: 100%; }",
];
var FramerveQWYc4l0 = withCSS(Component, css, "framer-vT2k1");
var stdin_default = FramerveQWYc4l0;
FramerveQWYc4l0.displayName = "Line";
FramerveQWYc4l0.defaultProps = {
	height: 1,
	width: 1200,
};
addPropertyControls(FramerveQWYc4l0, {
	variant: {
		options: ["gP9_qiu9b", "MjvYzj7Y5"],
		optionTitles: ["Line Inactive", "Line Active"],
		title: "Variant",
		type: ControlType.Enum,
	},
	ecP1TkFsy: {
		defaultValue:
			'var(--token-1ca63064-b503-4f13-8e66-ff201796eaf9, rgb(255, 255, 255)) /* {"name":"White"} */',
		title: "Fill",
		type: ControlType.Color,
	},
});
addFonts(
	FramerveQWYc4l0,
	[
		{
			explicitInter: true,
			fonts: [],
		},
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:line
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"1907350542b7624112d99063e9127837bac05866cdf3676335c1d928983f49a3"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				suppressHydrationWarning: true,
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders LineFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"1907350542b7624112d99063e9127837bac05866cdf3676335c1d928983f49a3"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				suppressHydrationWarning={true}
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var line_default = ComponentWithRoot;
export { line_default as default };
