// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 1907350542b76241 "Blimpy", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * text?: string // Text
 * fontFamily?: string // Font Family
 * fontSize?: number // Font Size
 * lineHeight?: number // Line Height
 * letterSpacing?: number // Letter Spacing
 * paragraphAlign?: 'Left' | 'Center' | 'Right' // Paragraph Align
 * duration?: number // Duration
 * easing?: 'Ease In Out' | 'Ease In' | 'Ease Out' | 'Linear' // Easing
 * transitionStartIndex?: number // Transition Start Index
}} Props

 */
import { routes } from "./chunks/chunk-RHU4XTMM.js";

// virtual:reveal-text
import { Fragment } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/j0R2lw3h1L0AKhqK4yze/lsAx0B6dg2Pg10Was2ik/Reveal_Text.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { addPropertyControls, ControlType } from "unframer";
import { motion, useScroll, useTransform } from "unframer";
import { useRef, useEffect } from "react";
var EachCharacter = ({
	char,
	start,
	end,
	progress,
	duration,
	easing,
	index,
	transitionStartIndex,
}) => {
	const colorProgress = useTransform(
		progress,
		[start, end],
		["#818181", "#FFFFFF"],
	);
	const initialColor = index < transitionStartIndex ? "#FFFFFF" : "#66818181";
	return (
		<motion.span
			suppressHydrationWarning={true}
			style={{
				color: index < transitionStartIndex ? initialColor : colorProgress,
			}}
			transition={{
				duration,
				ease: easing,
			}}
		>
			{char}
		</motion.span>
	);
};
var EachWord = ({
	word,
	progress,
	starting,
	ending,
	duration,
	easing,
	transitionStartIndex,
	currentCharacterIndex,
}) => {
	const characters = word.split("");
	const wordLength = word.length;
	const amount = ending - starting;
	const step = amount / wordLength;
	return (
		<motion.span suppressHydrationWarning={true}>
			{characters.map((char, idx) => {
				const charStart = starting + step * idx;
				const charEnd = starting + step * (idx + 1);
				return (
					<EachCharacter
						suppressHydrationWarning={true}
						char={char}
						start={charStart}
						end={charEnd}
						progress={progress}
						duration={duration}
						easing={easing}
						index={currentCharacterIndex + idx}
						transitionStartIndex={transitionStartIndex}
					/>
				);
			})}
			{"\xA0"}
		</motion.span>
	);
};
function Text_Color_Letters(props) {
	const {
		text,
		duration,
		easing,
		fontSize,
		lineHeight,
		letterSpacing,
		paragraphAlign,
		transitionStartIndex,
		fontFamily,
	} = props;
	const words = text.split(" ");
	const totalWords = words.length;
	const ref = useRef(null);
	const { scrollYProgress } = useScroll({
		target: ref,
		offset: ["start 0.75", "start 0.15"],
	});
	useEffect(() => {
		const style = document.createElement("style");
		style.appendChild(
			document.createTextNode(`
            @import url('https://fonts.googleapis.com/css2?family=${fontFamily.replace(/ /g, "+")}:wght@400&display=swap');
        `),
		);
		document.head.appendChild(style);
		return () => {
			document.head.removeChild(style);
		};
	}, [fontFamily]);
	let currentCharacterIndex = 0;
	return (
		<p
			suppressHydrationWarning={true}
			ref={ref}
			style={{
				fontFamily: `${fontFamily}, sans-serif`,
				fontSize: `${fontSize}px`,
				color: "#666666",
				display: "flex",
				flexWrap: "wrap",
				lineHeight: `${lineHeight}px`,
				letterSpacing: `${letterSpacing}px`,
				justifyContent: paragraphAlign,
				margin: 0,
			}}
		>
			{words.map((word, idx) => {
				const starting = idx / totalWords;
				const ending = (idx + 1) / totalWords;
				const wordLength = word.length;
				const startIdx = currentCharacterIndex;
				currentCharacterIndex += wordLength + 1;
				return (
					<EachWord
						suppressHydrationWarning={true}
						word={word}
						progress={scrollYProgress}
						starting={starting}
						ending={ending}
						duration={duration}
						easing={easing}
						transitionStartIndex={transitionStartIndex}
						currentCharacterIndex={startIdx}
					/>
				);
			})}
		</p>
	);
}
addPropertyControls(Text_Color_Letters, {
	text: {
		title: "Text",
		type: ControlType.String,
		defaultValue: "Hello Text",
	},
	fontFamily: {
		title: "Font Family",
		type: ControlType.String,
		defaultValue: "Urbanist",
	},
	fontSize: {
		title: "Font Size",
		type: ControlType.Number,
		defaultValue: 48,
		min: 10,
		max: 100,
	},
	lineHeight: {
		title: "Line Height",
		type: ControlType.Number,
		defaultValue: 60,
		min: 10,
		max: 100,
	},
	letterSpacing: {
		title: "Letter Spacing",
		type: ControlType.Number,
		defaultValue: -3,
		min: -10,
		max: 10,
	},
	paragraphAlign: {
		title: "Paragraph Align",
		type: ControlType.Enum,
		options: ["flex-start", "center", "flex-end"],
		optionTitles: ["Left", "Center", "Right"],
		defaultValue: "center",
	},
	duration: {
		title: "Duration",
		type: ControlType.Number,
		defaultValue: 0.3,
		min: 0.1,
		max: 3,
		step: 0.1,
	},
	easing: {
		title: "Easing",
		type: ControlType.Enum,
		options: ["easeInOut", "easeIn", "easeOut", "linear"],
		optionTitles: ["Ease In Out", "Ease In", "Ease Out", "Linear"],
		defaultValue: "easeInOut",
	},
	transitionStartIndex: {
		title: "Transition Start Index",
		type: ControlType.Number,
		defaultValue: 22,
		min: 0,
		max: 1e3,
	},
});

// virtual:reveal-text
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"1907350542b7624112d99063e9127837bac05866cdf3676335c1d928983f49a3"
			}
			locale={locale}
			locales={locales}
		>
			<Text_Color_Letters suppressHydrationWarning={true} {...rest} />
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders RevealTextFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"1907350542b7624112d99063e9127837bac05866cdf3676335c1d928983f49a3"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				suppressHydrationWarning={true}
				Component={Text_Color_Letters}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, Text_Color_Letters);
var reveal_text_default = ComponentWithRoot;
export { reveal_text_default as default };
