// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 1907350542b76241 "Blimpy", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop 01' | 'Desktop 02' | 'Desktop 03' | 'Desktop 04' | 'Tablet 01' | 'Tablet 02' | 'Tablet 03' | 'Tablet 04' | 'Phone 01' | 'Phone 02' | 'Phone 03' | 'Phone 04' // Variant
}} Props

 */
import {
	className as className3,
	css as css3,
	fonts as fonts3,
} from "./chunks/chunk-NXR4X5IX.js";
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-FNAFLMXC.js";
import {
	className,
	css,
	fonts,
	stdin_default,
	stdin_default2,
} from "./chunks/chunk-XRT6IGV4.js";
import { routes } from "./chunks/chunk-RHU4XTMM.js";

// virtual:service-card-wrapper
import { Fragment as Fragment4 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/vjS3unkPaVvYwpChMZ99/9UaMuIBNa3U65XLS43yr/dgJgDbddj.js
import { jsx as _jsx3, jsxs as _jsxs2 } from "react/jsx-runtime";
import {
	addFonts as addFonts3,
	addPropertyControls as addPropertyControls3,
	ComponentViewportProvider,
	ControlType as ControlType3,
	cx as cx3,
	forwardLoader,
	getFonts,
	SmartComponentScopedContainer,
	useActiveVariantCallback as useActiveVariantCallback2,
	useComponentViewport as useComponentViewport3,
	useLocaleInfo as useLocaleInfo3,
	useVariantState as useVariantState3,
	withCSS as withCSS3,
	withVariantAppearEffect,
} from "unframer";
import {
	LayoutGroup as LayoutGroup3,
	motion as motion3,
	MotionConfigContext as MotionConfigContext3,
} from "unframer";
import * as React3 from "react";
import { useRef as useRef3 } from "react";

// /:https://framerusercontent.com/modules/5ZIWd2YuYxy5oAuDIiAQ/urSo03T055HHZ1bUog5r/cur9GZ0QD.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	getLoadingLazyAtYPosition,
	Image,
	Instance,
	RichText,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var cycleOrder = [
	"ebies0UJf",
	"iYvm_teWy",
	"bsaUq_sxi",
	"xIDFABIL6",
	"i7ExtuCiy",
	"bXjwysvDb",
];
var serializationHash = "framer-BdbZ4";
var variantClassNames = {
	bsaUq_sxi: "framer-v-1hp4xih",
	bXjwysvDb: "framer-v-1wqvje6",
	ebies0UJf: "framer-v-1uhgqcp",
	i7ExtuCiy: "framer-v-7fjybf",
	iYvm_teWy: "framer-v-1s7sopz",
	xIDFABIL6: "framer-v-lwyd33",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	damping: 50,
	delay: 0,
	mass: 1,
	stiffness: 400,
	type: "spring",
};
var toResponsiveImage = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider
			suppressHydrationWarning={true}
			value={contextValue}
		>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	"Desktop Close": "iYvm_teWy",
	"Desktop Open": "ebies0UJf",
	"Phone Close": "bXjwysvDb",
	"Phone Open": "i7ExtuCiy",
	"Tablet Close": "xIDFABIL6",
	"Tablet Open": "bsaUq_sxi",
};
var getProps = ({
	click,
	height,
	id,
	image,
	number,
	paragraph,
	text,
	text2,
	text3,
	text4,
	title,
	width,
	...props
}) => {
	return {
		...props,
		b4x1S95yl: number ?? props.b4x1S95yl ?? "002",
		cJN5npylT: text2 ?? props.cJN5npylT ?? "Tool",
		nw1uBaV6t: text4 ?? props.nw1uBaV6t ?? "Brand Identity Design",
		q11frw_6a:
			paragraph ??
			props.q11frw_6a ??
			"Our mission is to develop innovative marketing strategies that seamlessly blend data-driven insights.",
		QAmPNlhZE: image ??
			props.QAmPNlhZE ?? {
				alt: "Image",
				pixelHeight: 495,
				pixelWidth: 1248,
				src: "https://framerusercontent.com/images/04ICgFkIEUErI0uT19fOfIOe0.png",
				srcSet:
					"https://framerusercontent.com/images/04ICgFkIEUErI0uT19fOfIOe0.png?scale-down-to=512 512w,https://framerusercontent.com/images/04ICgFkIEUErI0uT19fOfIOe0.png?scale-down-to=1024 1024w,https://framerusercontent.com/images/04ICgFkIEUErI0uT19fOfIOe0.png 1248w",
			},
		TDgHPEQwH: text3 ?? props.TDgHPEQwH ?? "Brand Strategy",
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "ebies0UJf",
		VbzDQR2gK: text ?? props.VbzDQR2gK ?? "What We Do",
		wosVXczZ8: click ?? props.wosVXczZ8,
		zlPOMfz7O: title ?? props.zlPOMfz7O ?? "UI/UX Design",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className4,
		layoutId,
		variant,
		b4x1S95yl,
		zlPOMfz7O,
		QAmPNlhZE,
		VbzDQR2gK,
		q11frw_6a,
		cJN5npylT,
		TDgHPEQwH,
		nw1uBaV6t,
		wosVXczZ8,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "ebies0UJf",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onTap1gbas1f = activeVariantCallback(async (...args) => {
		setGestureState({
			isPressed: false,
		});
		if (wosVXczZ8) {
			const res = await wosVXczZ8(...args);
			if (res === false) return false;
		}
		setVariant("iYvm_teWy");
	});
	const onTap1gkrnku = activeVariantCallback(async (...args) => {
		setGestureState({
			isPressed: false,
		});
		if (wosVXczZ8) {
			const res = await wosVXczZ8(...args);
			if (res === false) return false;
		}
		setVariant("ebies0UJf");
	});
	const onTap1hla8n2 = activeVariantCallback(async (...args) => {
		setGestureState({
			isPressed: false,
		});
		if (wosVXczZ8) {
			const res = await wosVXczZ8(...args);
			if (res === false) return false;
		}
		setVariant("xIDFABIL6");
	});
	const onTapuykhg6 = activeVariantCallback(async (...args) => {
		setGestureState({
			isPressed: false,
		});
		if (wosVXczZ8) {
			const res = await wosVXczZ8(...args);
			if (res === false) return false;
		}
		setVariant("bsaUq_sxi");
	});
	const onTapbhw72 = activeVariantCallback(async (...args) => {
		setGestureState({
			isPressed: false,
		});
		if (wosVXczZ8) {
			const res = await wosVXczZ8(...args);
			if (res === false) return false;
		}
		setVariant("bXjwysvDb");
	});
	const onTap1ttobha = activeVariantCallback(async (...args) => {
		setGestureState({
			isPressed: false,
		});
		if (wosVXczZ8) {
			const res = await wosVXczZ8(...args);
			if (res === false) return false;
		}
		setVariant("i7ExtuCiy");
	});
	const sharedStyleClassNames = [className, className3, className2];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const isDisplayed = () => {
		if (["iYvm_teWy", "xIDFABIL6", "bXjwysvDb"].includes(baseVariant))
			return false;
		return true;
	};
	return (
		<LayoutGroup
			suppressHydrationWarning={true}
			id={layoutId ?? defaultLayoutId}
		>
			<Variants
				suppressHydrationWarning={true}
				animate={variants}
				initial={false}
			>
				<Transition suppressHydrationWarning={true} value={transition1}>
					<motion.div
						suppressHydrationWarning={true}
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-1uhgqcp",
							className4,
							classNames,
						)}
						data-border={true}
						data-framer-name={"Desktop Open"}
						data-highlight={true}
						layoutDependency={layoutDependency}
						layoutId={"ebies0UJf"}
						onTap={onTap1gbas1f}
						ref={refBinding}
						style={{
							"--border-bottom-width": "1px",
							"--border-color":
								"var(--token-aad9f953-7a89-4aa6-8b88-7994cb74103e, rgba(255, 255, 255, 0.1))",
							"--border-left-width": "0px",
							"--border-right-width": "0px",
							"--border-style": "solid",
							"--border-top-width": "0px",
							...style,
						}}
						{...addPropertyOverrides(
							{
								bsaUq_sxi: {
									"data-framer-name": "Tablet Open",
									onTap: onTap1hla8n2,
								},
								bXjwysvDb: {
									"data-framer-name": "Phone Close",
									onTap: onTap1ttobha,
								},
								i7ExtuCiy: {
									"data-framer-name": "Phone Open",
									onTap: onTapbhw72,
								},
								iYvm_teWy: {
									"data-framer-name": "Desktop Close",
									onTap: onTap1gkrnku,
								},
								xIDFABIL6: {
									"data-framer-name": "Tablet Close",
									onTap: onTapuykhg6,
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							suppressHydrationWarning={true}
							className={"framer-uoycmw"}
							data-framer-name={"Service TItle Wrap"}
							layoutDependency={layoutDependency}
							layoutId={"W7I3yn4ZN"}
						>
							<RichText
								suppressHydrationWarning={true}
								__fromCanvasComponent={true}
								className={"framer-292y1c"}
								data-framer-name={"002"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"W7FjPKudi"}
								style={{
									"--framer-paragraph-spacing": "0px",
								}}
								text={b4x1S95yl}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.h4
										suppressHydrationWarning={true}
										className={"framer-styles-preset-txuqj2"}
										data-styles-preset={"HnFuI95b_"}
									>
										{"002"}
									</motion.h4>
								</React.Fragment>
							</RichText>
							<motion.div
								suppressHydrationWarning={true}
								className={"framer-s1sax6"}
								data-framer-name={"TItle"}
								layoutDependency={layoutDependency}
								layoutId={"ri6LkG8t4"}
							>
								<RichText
									suppressHydrationWarning={true}
									__fromCanvasComponent={true}
									className={"framer-197qi3l"}
									data-framer-name={"UI/UX Design"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"jhrh74yNf"}
									style={{
										"--framer-paragraph-spacing": "0px",
									}}
									text={zlPOMfz7O}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.h3
											suppressHydrationWarning={true}
											className={"framer-styles-preset-in3o60"}
											data-styles-preset={"PiAFu8lfe"}
										>
											{"UI/UX Design"}
										</motion.h3>
									</React.Fragment>
								</RichText>
								<Instance
									suppressHydrationWarning={true}
									animated={true}
									className={"framer-1eoe68v"}
									Component={stdin_default}
									layoutDependency={layoutDependency}
									layoutId={"Iylc1WPW3"}
									style={{
										"--43q7um":
											"var(--token-d0efb30f-1ca4-4318-a615-3c27c4e89f33, rgb(255, 31, 0))",
									}}
									variants={{
										bXjwysvDb: {
											"--43q7um":
												"var(--token-1ca63064-b503-4f13-8e66-ff201796eaf9, rgb(255, 255, 255))",
										},
										iYvm_teWy: {
											"--43q7um":
												"var(--token-1ca63064-b503-4f13-8e66-ff201796eaf9, rgb(255, 255, 255))",
										},
										xIDFABIL6: {
											"--43q7um":
												"var(--token-1ca63064-b503-4f13-8e66-ff201796eaf9, rgb(255, 255, 255))",
										},
									}}
									{...addPropertyOverrides(
										{
											bXjwysvDb: {
												Component: stdin_default2,
											},
											iYvm_teWy: {
												Component: stdin_default2,
											},
											xIDFABIL6: {
												Component: stdin_default2,
											},
										},
										baseVariant,
										gestureVariant,
									)}
								/>
							</motion.div>
						</motion.div>
						{isDisplayed() && (
							<motion.div
								suppressHydrationWarning={true}
								className={"framer-o21slr"}
								data-framer-name={"Content Wrap"}
								layoutDependency={layoutDependency}
								layoutId={"YUpjT01n4"}
							>
								<motion.div
									suppressHydrationWarning={true}
									className={"framer-1fanzp5"}
									data-framer-name={"Service Content"}
									layoutDependency={layoutDependency}
									layoutId={"zXPRHvkls"}
								>
									<motion.div
										suppressHydrationWarning={true}
										className={"framer-1mlabqg"}
										data-framer-name={"Content"}
										layoutDependency={layoutDependency}
										layoutId={"VfWBcKDV1"}
									>
										<Image
											suppressHydrationWarning={true}
											background={{
												alt: "",
												fit: "fill",
												loading: getLoadingLazyAtYPosition(
													(componentViewport?.y || 0) +
														52 +
														(((componentViewport?.height || 539) -
															104 -
															512.2) /
															2 +
															57.6 +
															60) +
														0 +
														0 +
														0 +
														0 +
														0,
												),
												pixelHeight: 495,
												pixelWidth: 1248,
												sizes: `min(max((min(max(${componentViewport?.width || "100vw"}, 1px), 795px) - 10px) / 2, 1px), 416px)`,
												...toResponsiveImage(QAmPNlhZE),
											}}
											className={"framer-25sb9o"}
											layoutDependency={layoutDependency}
											layoutId={"rAMKkTYfQ"}
											{...addPropertyOverrides(
												{
													bsaUq_sxi: {
														background: {
															alt: "",
															fit: "fill",
															loading: getLoadingLazyAtYPosition(
																(componentViewport?.y || 0) +
																	40 +
																	(((componentViewport?.height || 515) -
																		80 -
																		512.2) /
																		2 +
																		57.6 +
																		60) +
																	0 +
																	0 +
																	0 +
																	0 +
																	0,
															),
															pixelHeight: 495,
															pixelWidth: 1248,
															sizes: `min(max((min(max(${componentViewport?.width || "100vw"}, 1px), 650px) - 10px) / 2, 1px), 416px)`,
															...toResponsiveImage(QAmPNlhZE),
														},
													},
													i7ExtuCiy: {
														background: {
															alt: "",
															fit: "fill",
															loading: getLoadingLazyAtYPosition(
																(componentViewport?.y || 0) +
																	24 +
																	(((componentViewport?.height || 613) -
																		48 -
																		789.8) /
																		2 +
																		57.6 +
																		30) +
																	0 +
																	0 +
																	0 +
																	0 +
																	0,
															),
															pixelHeight: 495,
															pixelWidth: 1248,
															sizes: `min(min(max(${componentViewport?.width || "100vw"}, 1px), 650px), 416px)`,
															...toResponsiveImage(QAmPNlhZE),
														},
													},
												},
												baseVariant,
												gestureVariant,
											)}
										/>
										<motion.div
											suppressHydrationWarning={true}
											className={"framer-fzs4hi"}
											data-framer-name={"Title"}
											layoutDependency={layoutDependency}
											layoutId={"vv6FJppdB"}
										>
											<RichText
												suppressHydrationWarning={true}
												__fromCanvasComponent={true}
												className={"framer-ufiw8i"}
												data-framer-name={"What We Do"}
												fonts={["Inter"]}
												layoutDependency={layoutDependency}
												layoutId={"EgyH8FxJB"}
												style={{
													"--framer-paragraph-spacing": "0px",
												}}
												text={VbzDQR2gK}
												verticalAlignment={"top"}
												withExternalLayout={true}
											>
												<React.Fragment>
													<motion.h4
														suppressHydrationWarning={true}
														className={"framer-styles-preset-txuqj2"}
														data-styles-preset={"HnFuI95b_"}
													>
														{"What We Do"}
													</motion.h4>
												</React.Fragment>
											</RichText>
											<RichText
												suppressHydrationWarning={true}
												__fromCanvasComponent={true}
												className={"framer-iat2aa"}
												data-framer-name={
													"Our mission is to develop innovative marketing strategies that seamlessly blend data-driven insights."
												}
												fonts={["Inter"]}
												layoutDependency={layoutDependency}
												layoutId={"F3pX8i737"}
												style={{
													"--extracted-r6o4lv":
														"var(--token-1ca63064-b503-4f13-8e66-ff201796eaf9, rgb(255, 255, 255))",
													"--framer-paragraph-spacing": "0px",
													opacity: 0.6,
												}}
												text={q11frw_6a}
												verticalAlignment={"top"}
												withExternalLayout={true}
											>
												<React.Fragment>
													<motion.p
														suppressHydrationWarning={true}
														className={"framer-styles-preset-1me9qdm"}
														data-styles-preset={"DH9ENh_0Z"}
														style={{
															"--framer-text-color":
																"var(--extracted-r6o4lv, var(--token-1ca63064-b503-4f13-8e66-ff201796eaf9, rgb(255, 255, 255)))",
														}}
													>
														{
															"Our mission is to develop innovative marketing strategies that seamlessly blend data-driven insights."
														}
													</motion.p>
												</React.Fragment>
											</RichText>
										</motion.div>
									</motion.div>
									<motion.div
										suppressHydrationWarning={true}
										className={"framer-x03eda"}
										data-framer-name={"Text Wrap"}
										layoutDependency={layoutDependency}
										layoutId={"pcZo0G9_B"}
									>
										<RichText
											suppressHydrationWarning={true}
											__fromCanvasComponent={true}
											className={"framer-1xz0ol2"}
											data-framer-name={"Tool"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"IPmHzgqlA"}
											style={{
												"--framer-paragraph-spacing": "0px",
											}}
											text={cJN5npylT}
											verticalAlignment={"top"}
											withExternalLayout={true}
											{...addPropertyOverrides(
												{
													i7ExtuCiy: {
														children: (
															<React.Fragment>
																<motion.h4
																	suppressHydrationWarning={true}
																	className={"framer-styles-preset-txuqj2"}
																	data-styles-preset={"HnFuI95b_"}
																	style={{
																		"--framer-text-alignment": "left",
																	}}
																>
																	{"Tool"}
																</motion.h4>
															</React.Fragment>
														),
													},
												},
												baseVariant,
												gestureVariant,
											)}
										>
											<React.Fragment>
												<motion.h4
													suppressHydrationWarning={true}
													className={"framer-styles-preset-txuqj2"}
													data-styles-preset={"HnFuI95b_"}
													style={{
														"--framer-text-alignment": "right",
													}}
												>
													{"Tool"}
												</motion.h4>
											</React.Fragment>
										</RichText>
										<motion.div
											suppressHydrationWarning={true}
											className={"framer-xy1yak"}
											data-framer-name={"Text"}
											layoutDependency={layoutDependency}
											layoutId={"XrRBX1EHn"}
										>
											<RichText
												suppressHydrationWarning={true}
												__fromCanvasComponent={true}
												className={"framer-17hfxko"}
												data-framer-name={"Brand Strategy"}
												fonts={["Inter"]}
												layoutDependency={layoutDependency}
												layoutId={"p3JaYqXuE"}
												style={{
													"--extracted-r6o4lv":
														"var(--token-1ca63064-b503-4f13-8e66-ff201796eaf9, rgb(255, 255, 255))",
													"--framer-paragraph-spacing": "0px",
													opacity: 0.6,
												}}
												text={TDgHPEQwH}
												verticalAlignment={"top"}
												withExternalLayout={true}
												{...addPropertyOverrides(
													{
														i7ExtuCiy: {
															children: (
																<React.Fragment>
																	<motion.p
																		suppressHydrationWarning={true}
																		className={"framer-styles-preset-1me9qdm"}
																		data-styles-preset={"DH9ENh_0Z"}
																		style={{
																			"--framer-text-alignment": "left",
																			"--framer-text-color":
																				"var(--extracted-r6o4lv, var(--token-1ca63064-b503-4f13-8e66-ff201796eaf9, rgb(255, 255, 255)))",
																		}}
																	>
																		{"Brand Strategy"}
																	</motion.p>
																</React.Fragment>
															),
														},
													},
													baseVariant,
													gestureVariant,
												)}
											>
												<React.Fragment>
													<motion.p
														suppressHydrationWarning={true}
														className={"framer-styles-preset-1me9qdm"}
														data-styles-preset={"DH9ENh_0Z"}
														style={{
															"--framer-text-alignment": "right",
															"--framer-text-color":
																"var(--extracted-r6o4lv, var(--token-1ca63064-b503-4f13-8e66-ff201796eaf9, rgb(255, 255, 255)))",
														}}
													>
														{"Brand Strategy"}
													</motion.p>
												</React.Fragment>
											</RichText>
											<RichText
												suppressHydrationWarning={true}
												__fromCanvasComponent={true}
												className={"framer-1jianlp"}
												data-framer-name={"Brand Strategy"}
												fonts={["Inter"]}
												layoutDependency={layoutDependency}
												layoutId={"WEPI4tY_c"}
												style={{
													"--extracted-r6o4lv":
														"var(--token-1ca63064-b503-4f13-8e66-ff201796eaf9, rgb(255, 255, 255))",
													"--framer-paragraph-spacing": "0px",
													opacity: 0.6,
												}}
												text={nw1uBaV6t}
												verticalAlignment={"top"}
												withExternalLayout={true}
												{...addPropertyOverrides(
													{
														i7ExtuCiy: {
															children: (
																<React.Fragment>
																	<motion.p
																		suppressHydrationWarning={true}
																		className={"framer-styles-preset-1me9qdm"}
																		data-styles-preset={"DH9ENh_0Z"}
																		style={{
																			"--framer-text-alignment": "left",
																			"--framer-text-color":
																				"var(--extracted-r6o4lv, var(--token-1ca63064-b503-4f13-8e66-ff201796eaf9, rgb(255, 255, 255)))",
																		}}
																	>
																		{"Brand Identity Design"}
																	</motion.p>
																</React.Fragment>
															),
														},
													},
													baseVariant,
													gestureVariant,
												)}
											>
												<React.Fragment>
													<motion.p
														suppressHydrationWarning={true}
														className={"framer-styles-preset-1me9qdm"}
														data-styles-preset={"DH9ENh_0Z"}
														style={{
															"--framer-text-alignment": "right",
															"--framer-text-color":
																"var(--extracted-r6o4lv, var(--token-1ca63064-b503-4f13-8e66-ff201796eaf9, rgb(255, 255, 255)))",
														}}
													>
														{"Brand Identity Design"}
													</motion.p>
												</React.Fragment>
											</RichText>
										</motion.div>
									</motion.div>
								</motion.div>
							</motion.div>
						)}
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css4 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-BdbZ4.framer-bd7o17, .framer-BdbZ4 .framer-bd7o17 { display: block; }",
	".framer-BdbZ4.framer-1uhgqcp { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 60px; height: min-content; justify-content: center; overflow: hidden; padding: 52px 0px 52px 0px; position: relative; width: 1140px; }",
	".framer-BdbZ4 .framer-uoycmw { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; height: min-content; justify-content: space-between; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-BdbZ4 .framer-292y1c { flex: 1 0 0px; height: auto; max-width: 200px; position: relative; white-space: pre-wrap; width: 1px; word-break: break-word; word-wrap: break-word; }",
	".framer-BdbZ4 .framer-s1sax6 { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; height: min-content; justify-content: space-between; max-width: 795px; overflow: hidden; padding: 0px; position: relative; width: 1px; }",
	".framer-BdbZ4 .framer-197qi3l { flex: 1 0 0px; height: auto; max-width: 350px; position: relative; white-space: pre-wrap; width: 1px; word-break: break-word; word-wrap: break-word; }",
	".framer-BdbZ4 .framer-1eoe68v { flex: none; height: var(--framer-aspect-ratio-supported, 24px); position: relative; width: 24px; }",
	".framer-BdbZ4 .framer-o21slr { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-end; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-BdbZ4 .framer-1fanzp5 { align-content: flex-end; align-items: flex-end; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; height: min-content; justify-content: space-between; max-width: 795px; overflow: hidden; padding: 0px; position: relative; width: 1px; }",
	".framer-BdbZ4 .framer-1mlabqg { align-content: flex-start; align-items: flex-start; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 52px; height: min-content; justify-content: flex-start; max-width: 416px; overflow: hidden; padding: 0px; position: relative; width: 1px; }",
	".framer-BdbZ4 .framer-25sb9o { aspect-ratio: 2.521212121212121 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 165px); position: relative; width: 100%; }",
	".framer-BdbZ4 .framer-fzs4hi { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-BdbZ4 .framer-ufiw8i, .framer-BdbZ4 .framer-iat2aa, .framer-BdbZ4 .framer-1xz0ol2, .framer-BdbZ4 .framer-17hfxko, .framer-BdbZ4 .framer-1jianlp { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-BdbZ4 .framer-x03eda { align-content: flex-end; align-items: flex-end; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: flex-start; max-width: 165px; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	".framer-BdbZ4 .framer-xy1yak { align-content: flex-end; align-items: flex-end; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-BdbZ4.framer-v-1hp4xih.framer-1uhgqcp, .framer-BdbZ4.framer-v-lwyd33.framer-1uhgqcp { padding: 40px 0px 40px 0px; width: 750px; }",
	".framer-BdbZ4.framer-v-1hp4xih .framer-292y1c, .framer-BdbZ4.framer-v-lwyd33 .framer-292y1c { max-width: 100px; }",
	".framer-BdbZ4.framer-v-1hp4xih .framer-s1sax6, .framer-BdbZ4.framer-v-1hp4xih .framer-1fanzp5, .framer-BdbZ4.framer-v-lwyd33 .framer-s1sax6 { max-width: 650px; }",
	".framer-BdbZ4.framer-v-7fjybf.framer-1uhgqcp, .framer-BdbZ4.framer-v-1wqvje6.framer-1uhgqcp { gap: 30px; padding: 24px 0px 24px 0px; width: 350px; }",
	".framer-BdbZ4.framer-v-7fjybf .framer-uoycmw, .framer-BdbZ4.framer-v-1wqvje6 .framer-uoycmw { align-content: flex-start; align-items: flex-start; }",
	".framer-BdbZ4.framer-v-7fjybf .framer-292y1c, .framer-BdbZ4.framer-v-1wqvje6 .framer-292y1c { max-width: 80px; }",
	".framer-BdbZ4.framer-v-7fjybf .framer-s1sax6, .framer-BdbZ4.framer-v-1wqvje6 .framer-s1sax6 { align-content: flex-start; align-items: flex-start; max-width: 650px; }",
	".framer-BdbZ4.framer-v-7fjybf .framer-1fanzp5 { align-content: flex-start; align-items: flex-start; flex-direction: column; gap: 24px; justify-content: center; max-width: 650px; }",
	".framer-BdbZ4.framer-v-7fjybf .framer-1mlabqg { flex: none; gap: 30px; width: 100%; }",
	".framer-BdbZ4.framer-v-7fjybf .framer-25sb9o { height: var(--framer-aspect-ratio-supported, 139px); }",
	".framer-BdbZ4.framer-v-7fjybf .framer-x03eda { align-content: flex-start; align-items: flex-start; flex: none; width: 100%; }",
	...css,
	...css3,
	...css2,
	'.framer-BdbZ4[data-border="true"]::after, .framer-BdbZ4 [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var Framercur9GZ0QD = withCSS(Component, css4, "framer-BdbZ4");
var stdin_default3 = Framercur9GZ0QD;
Framercur9GZ0QD.displayName = "Service Card";
Framercur9GZ0QD.defaultProps = {
	height: 539,
	width: 1140,
};
addPropertyControls(Framercur9GZ0QD, {
	variant: {
		options: [
			"ebies0UJf",
			"iYvm_teWy",
			"bsaUq_sxi",
			"xIDFABIL6",
			"i7ExtuCiy",
			"bXjwysvDb",
		],
		optionTitles: [
			"Desktop Open",
			"Desktop Close",
			"Tablet Open",
			"Tablet Close",
			"Phone Open",
			"Phone Close",
		],
		title: "Variant",
		type: ControlType.Enum,
	},
	b4x1S95yl: {
		defaultValue: "002",
		displayTextArea: false,
		title: "Number",
		type: ControlType.String,
	},
	zlPOMfz7O: {
		defaultValue: "UI/UX Design",
		displayTextArea: false,
		title: "Title",
		type: ControlType.String,
	},
	QAmPNlhZE: {
		__defaultAssetReference:
			"data:framer/asset-reference,04ICgFkIEUErI0uT19fOfIOe0.png?originalFilename=Frame+1948753927+%282%29.png&preferredSize=auto",
		__vekterDefault: {
			alt: "Image",
			assetReference:
				"data:framer/asset-reference,04ICgFkIEUErI0uT19fOfIOe0.png?originalFilename=Frame+1948753927+%282%29.png&preferredSize=auto",
		},
		title: "Image",
		type: ControlType.ResponsiveImage,
	},
	VbzDQR2gK: {
		defaultValue: "What We Do",
		displayTextArea: false,
		title: "Text",
		type: ControlType.String,
	},
	q11frw_6a: {
		defaultValue:
			"Our mission is to develop innovative marketing strategies that seamlessly blend data-driven insights.",
		displayTextArea: false,
		title: "Paragraph",
		type: ControlType.String,
	},
	cJN5npylT: {
		defaultValue: "Tool",
		displayTextArea: false,
		title: "Text 2",
		type: ControlType.String,
	},
	TDgHPEQwH: {
		defaultValue: "Brand Strategy",
		displayTextArea: false,
		title: "Text 3",
		type: ControlType.String,
	},
	nw1uBaV6t: {
		defaultValue: "Brand Identity Design",
		displayTextArea: false,
		title: "Text 4",
		type: ControlType.String,
	},
	wosVXczZ8: {
		title: "Click",
		type: ControlType.EventHandler,
	},
});
addFonts(
	Framercur9GZ0QD,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts),
		...getFontsFromSharedStyle(fonts3),
		...getFontsFromSharedStyle(fonts2),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// /:https://framerusercontent.com/modules/2Wft0jefty02aRAe6pMH/xahzfkFnXTsTK3XnNuPX/veQWYc4l0.js
import { jsx as _jsx2 } from "react/jsx-runtime";
import {
	addFonts as addFonts2,
	addPropertyControls as addPropertyControls2,
	ControlType as ControlType2,
	cx as cx2,
	useComponentViewport as useComponentViewport2,
	useLocaleInfo as useLocaleInfo2,
	useVariantState as useVariantState2,
	withCSS as withCSS2,
} from "unframer";
import {
	LayoutGroup as LayoutGroup2,
	motion as motion2,
	MotionConfigContext as MotionConfigContext2,
} from "unframer";
import * as React2 from "react";
import { useRef as useRef2 } from "react";
var cycleOrder2 = ["gP9_qiu9b", "MjvYzj7Y5"];
var serializationHash2 = "framer-vT2k1";
var variantClassNames2 = {
	gP9_qiu9b: "framer-v-17zutcw",
	MjvYzj7Y5: "framer-v-f2n5b8",
};
function addPropertyOverrides2(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition12 = {
	damping: 60,
	delay: 0,
	mass: 1,
	stiffness: 400,
	type: "spring",
};
var Transition2 = ({ value, children }) => {
	const config = React2.useContext(MotionConfigContext2);
	const transition = value ?? config.transition;
	const contextValue = React2.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext2.Provider
			suppressHydrationWarning={true}
			value={contextValue}
		>
			{children}
		</MotionConfigContext2.Provider>
	);
};
var Variants2 = motion2.create(React2.Fragment);
var humanReadableVariantMap2 = {
	"Line Active": "MjvYzj7Y5",
	"Line Inactive": "gP9_qiu9b",
};
var getProps2 = ({ fill, height, id, width, ...props }) => {
	return {
		...props,
		ecP1TkFsy:
			fill ??
			props.ecP1TkFsy ??
			"var(--token-1ca63064-b503-4f13-8e66-ff201796eaf9, rgb(255, 255, 255))",
		variant:
			humanReadableVariantMap2[props.variant] ?? props.variant ?? "gP9_qiu9b",
	};
};
var createLayoutDependency2 = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component2 = /* @__PURE__ */ React2.forwardRef(function (props, ref) {
	const fallbackRef = useRef2(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React2.useId();
	const { activeLocale, setLocale } = useLocaleInfo2();
	const componentViewport = useComponentViewport2();
	const {
		style,
		className: className4,
		layoutId,
		variant,
		ecP1TkFsy,
		...restProps
	} = getProps2(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState2({
		cycleOrder: cycleOrder2,
		defaultVariant: "gP9_qiu9b",
		ref: refBinding,
		variant,
		variantClassNames: variantClassNames2,
	});
	const layoutDependency = createLayoutDependency2(props, variants);
	const sharedStyleClassNames = [];
	const scopingClassNames = cx2(serializationHash2, ...sharedStyleClassNames);
	return (
		<LayoutGroup2
			suppressHydrationWarning={true}
			id={layoutId ?? defaultLayoutId}
		>
			<Variants2
				suppressHydrationWarning={true}
				animate={variants}
				initial={false}
			>
				<Transition2 suppressHydrationWarning={true} value={transition12}>
					<motion2.div
						suppressHydrationWarning={true}
						{...restProps}
						{...gestureHandlers}
						className={cx2(
							scopingClassNames,
							"framer-17zutcw",
							className4,
							classNames,
						)}
						data-framer-name={"Line Inactive"}
						layoutDependency={layoutDependency}
						layoutId={"gP9_qiu9b"}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides2(
							{
								MjvYzj7Y5: {
									"data-framer-name": "Line Active",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion2.div
							suppressHydrationWarning={true}
							className={"framer-3t5668"}
							data-framer-name={"Fill"}
							layoutDependency={layoutDependency}
							layoutId={"LDx1OB3o7"}
							style={{
								backgroundColor: ecP1TkFsy,
							}}
						/>
					</motion2.div>
				</Transition2>
			</Variants2>
		</LayoutGroup2>
	);
});
var css5 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-vT2k1.framer-kvslh6, .framer-vT2k1 .framer-kvslh6 { display: block; }",
	".framer-vT2k1.framer-17zutcw { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; width: 1200px; }",
	".framer-vT2k1 .framer-3t5668 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 1px; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 0%; }",
	".framer-vT2k1.framer-v-f2n5b8 .framer-3t5668 { width: 100%; }",
];
var FramerveQWYc4l0 = withCSS2(Component2, css5, "framer-vT2k1");
var stdin_default4 = FramerveQWYc4l0;
FramerveQWYc4l0.displayName = "Line";
FramerveQWYc4l0.defaultProps = {
	height: 1,
	width: 1200,
};
addPropertyControls2(FramerveQWYc4l0, {
	variant: {
		options: ["gP9_qiu9b", "MjvYzj7Y5"],
		optionTitles: ["Line Inactive", "Line Active"],
		title: "Variant",
		type: ControlType2.Enum,
	},
	ecP1TkFsy: {
		defaultValue:
			'var(--token-1ca63064-b503-4f13-8e66-ff201796eaf9, rgb(255, 255, 255)) /* {"name":"White"} */',
		title: "Fill",
		type: ControlType2.Color,
	},
});
addFonts2(
	FramerveQWYc4l0,
	[
		{
			explicitInter: true,
			fonts: [],
		},
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// /:https://framerusercontent.com/modules/vjS3unkPaVvYwpChMZ99/9UaMuIBNa3U65XLS43yr/dgJgDbddj.js
var LineFonts = getFonts(stdin_default4);
var LineWithVariantAppearEffect = withVariantAppearEffect(stdin_default4);
var ServiceCardFonts = getFonts(stdin_default3);
var cycleOrder3 = [
	"s3BRDnDV3",
	"c7l66Iuz3",
	"diJpg71nc",
	"DSU7R5rXG",
	"aqDZcY3HY",
	"pZ2xXWQV8",
	"CRDBQA8Ni",
	"HnQjsRIb5",
	"bsbqcBHjk",
	"YLbpgkMIK",
	"KW98uve0H",
	"TP9pnK002",
];
var serializationHash3 = "framer-7Q4cq";
var variantClassNames3 = {
	aqDZcY3HY: "framer-v-bavduv",
	bsbqcBHjk: "framer-v-1ud0pif",
	c7l66Iuz3: "framer-v-s8emur",
	CRDBQA8Ni: "framer-v-qda8ct",
	diJpg71nc: "framer-v-t5sfm5",
	DSU7R5rXG: "framer-v-1fzo8s2",
	HnQjsRIb5: "framer-v-1l2t64g",
	KW98uve0H: "framer-v-17pp67b",
	pZ2xXWQV8: "framer-v-4103c2",
	s3BRDnDV3: "framer-v-bomeh3",
	TP9pnK002: "framer-v-znh65v",
	YLbpgkMIK: "framer-v-1tt65mz",
};
function addPropertyOverrides3(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition13 = {
	damping: 100,
	delay: 0,
	mass: 1,
	stiffness: 400,
	type: "spring",
};
var matchVariant = (...args) => {
	for (const arg of args) {
		if (arg && typeof arg === "string") return arg;
	}
	return void 0;
};
var addImageAlt = (image, alt) => {
	if (!image || typeof image !== "object") {
		return;
	}
	return {
		...image,
		alt,
	};
};
var Transition3 = ({ value, children }) => {
	const config = React3.useContext(MotionConfigContext3);
	const transition = value ?? config.transition;
	const contextValue = React3.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext3.Provider
			suppressHydrationWarning={true}
			value={contextValue}
		>
			{children}
		</MotionConfigContext3.Provider>
	);
};
var humanReadableVariantMap3 = {
	"Desktop 01": "s3BRDnDV3",
	"Desktop 02": "c7l66Iuz3",
	"Desktop 03": "diJpg71nc",
	"Desktop 04": "DSU7R5rXG",
	"Phone 01": "bsbqcBHjk",
	"Phone 02": "YLbpgkMIK",
	"Phone 03": "KW98uve0H",
	"Phone 04": "TP9pnK002",
	"Tablet 01": "aqDZcY3HY",
	"Tablet 02": "pZ2xXWQV8",
	"Tablet 03": "CRDBQA8Ni",
	"Tablet 04": "HnQjsRIb5",
};
var Variants3 = motion3.create(React3.Fragment);
var getProps3 = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap3[props.variant] ?? props.variant ?? "s3BRDnDV3",
	};
};
var createLayoutDependency3 = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component3 = /* @__PURE__ */ React3.forwardRef(function (props, ref) {
	const fallbackRef = useRef3(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React3.useId();
	const { activeLocale, setLocale } = useLocaleInfo3();
	const componentViewport = useComponentViewport3();
	const {
		style,
		className: className4,
		layoutId,
		variant,
		...restProps
	} = getProps3(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState3({
		cycleOrder: cycleOrder3,
		defaultVariant: "s3BRDnDV3",
		ref: refBinding,
		variant,
		variantClassNames: variantClassNames3,
	});
	const layoutDependency = createLayoutDependency3(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback2(baseVariant);
	const wosVXczZ8182nkrt = activeVariantCallback(async (...args) => {
		setVariant("s3BRDnDV3");
	});
	const wosVXczZ8j22lm4 = activeVariantCallback(async (...args) => {
		setVariant("aqDZcY3HY");
	});
	const wosVXczZ81fq4b78 = activeVariantCallback(async (...args) => {
		setVariant("bsbqcBHjk");
	});
	const wosVXczZ8e4v2tb = activeVariantCallback(async (...args) => {
		setVariant("c7l66Iuz3");
	});
	const wosVXczZ81js2cfs = activeVariantCallback(async (...args) => {
		setVariant("pZ2xXWQV8");
	});
	const wosVXczZ8lcpf15 = activeVariantCallback(async (...args) => {
		setVariant("YLbpgkMIK");
	});
	const wosVXczZ8fsx9u6 = activeVariantCallback(async (...args) => {
		setVariant("diJpg71nc");
	});
	const wosVXczZ8l09aup = activeVariantCallback(async (...args) => {
		setVariant("CRDBQA8Ni");
	});
	const wosVXczZ8b9tzhz = activeVariantCallback(async (...args) => {
		setVariant("KW98uve0H");
	});
	const wosVXczZ8cm6zyx = activeVariantCallback(async (...args) => {
		setVariant("DSU7R5rXG");
	});
	const wosVXczZ8oezqps = activeVariantCallback(async (...args) => {
		setVariant("HnQjsRIb5");
	});
	const wosVXczZ8b4i9zq = activeVariantCallback(async (...args) => {
		setVariant("TP9pnK002");
	});
	const sharedStyleClassNames = [];
	const scopingClassNames = cx3(serializationHash3, ...sharedStyleClassNames);
	return (
		<LayoutGroup3
			suppressHydrationWarning={true}
			id={layoutId ?? defaultLayoutId}
		>
			<Variants3
				suppressHydrationWarning={true}
				animate={variants}
				initial={false}
			>
				<Transition3 suppressHydrationWarning={true} value={transition13}>
					<motion3.section
						suppressHydrationWarning={true}
						{...restProps}
						{...gestureHandlers}
						className={cx3(
							scopingClassNames,
							"framer-bomeh3",
							className4,
							classNames,
						)}
						data-framer-name={"Desktop 01"}
						layoutDependency={layoutDependency}
						layoutId={"s3BRDnDV3"}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides3(
							{
								aqDZcY3HY: {
									"data-framer-name": "Tablet 01",
								},
								bsbqcBHjk: {
									"data-framer-name": "Phone 01",
								},
								c7l66Iuz3: {
									"data-framer-name": "Desktop 02",
								},
								CRDBQA8Ni: {
									"data-framer-name": "Tablet 03",
								},
								diJpg71nc: {
									"data-framer-name": "Desktop 03",
								},
								DSU7R5rXG: {
									"data-framer-name": "Desktop 04",
								},
								HnQjsRIb5: {
									"data-framer-name": "Tablet 04",
								},
								KW98uve0H: {
									"data-framer-name": "Phone 03",
								},
								pZ2xXWQV8: {
									"data-framer-name": "Tablet 02",
								},
								TP9pnK002: {
									"data-framer-name": "Phone 04",
								},
								YLbpgkMIK: {
									"data-framer-name": "Phone 02",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<ComponentViewportProvider
							suppressHydrationWarning={true}
							height={1}
							width={componentViewport?.width || "100vw"}
							y={
								(componentViewport?.y || 0) +
								0 +
								(((componentViewport?.height || 200) - 0 - 2157) / 2 + 0 + 0)
							}
						>
							<SmartComponentScopedContainer
								suppressHydrationWarning={true}
								className={"framer-ugzwx8-container"}
								layoutDependency={layoutDependency}
								layoutId={"UezcRm9LV-container"}
								nodeId={"UezcRm9LV"}
								rendersWithMotion={true}
								scopeId={"dgJgDbddj"}
								style={{
									opacity: 0.1,
								}}
							>
								<LineWithVariantAppearEffect
									suppressHydrationWarning={true}
									__framer__animateOnce={true}
									__framer__obscuredVariantId={"gP9_qiu9b"}
									__framer__threshold={0.5}
									__framer__variantAppearEffectEnabled={true}
									__framer__visibleVariantId={"MjvYzj7Y5"}
									ecP1TkFsy={
										"var(--token-1ca63064-b503-4f13-8e66-ff201796eaf9, rgb(255, 255, 255))"
									}
									height={"100%"}
									id={"UezcRm9LV"}
									layoutId={"UezcRm9LV"}
									style={{
										width: "100%",
									}}
									variant={matchVariant("MjvYzj7Y5")}
									width={"100%"}
								/>
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
						<ComponentViewportProvider
							suppressHydrationWarning={true}
							height={539}
							width={componentViewport?.width || "100vw"}
							y={
								(componentViewport?.y || 0) +
								0 +
								(((componentViewport?.height || 200) - 0 - 2157) / 2 + 1 + 0)
							}
						>
							<SmartComponentScopedContainer
								suppressHydrationWarning={true}
								className={"framer-192ipgt-container"}
								layoutDependency={layoutDependency}
								layoutId={"sUoThKVTY-container"}
								nodeId={"sUoThKVTY"}
								rendersWithMotion={true}
								scopeId={"dgJgDbddj"}
							>
								{_jsx3(stdin_default3, {
									suppressHydrationWarning: true,
									b4x1S95yl: "001",
									cJN5npylT: "Tool",
									height: "100%",
									id: "sUoThKVTY",
									layoutId: "sUoThKVTY",
									nw1uBaV6t: "Brand Identity Design",
									q11frw_6a:
										"We CONNECT your scattered marketing platforms\u2014socials, website, and CRM\u2014into one reliable hub (GA4). We fix your tracking infrastructure so you always know exactly where your leads come from.",
									QAmPNlhZE: addImageAlt(
										{
											pixelHeight: 265,
											pixelWidth: 341,
											src: "https://framerusercontent.com/images/uQaRujCdcvawmrP5nJY0eAM4c.jpeg?width=341&height=265",
										},
										"Image",
									),
									style: {
										width: "100%",
									},
									TDgHPEQwH: "Brand Strategy",
									variant: matchVariant("ebies0UJf"),
									VbzDQR2gK: "How We Help",
									width: "100%",
									wosVXczZ8: wosVXczZ8182nkrt,
									zlPOMfz7O: "Data Integration",
									...addPropertyOverrides3(
										{
											aqDZcY3HY: {
												variant: matchVariant("bsaUq_sxi"),
												wosVXczZ8: wosVXczZ8j22lm4,
											},
											bsbqcBHjk: {
												variant: matchVariant("i7ExtuCiy"),
												wosVXczZ8: wosVXczZ81fq4b78,
											},
											c7l66Iuz3: {
												nw1uBaV6t: "Tracking",
												TDgHPEQwH: "Tagging",
												variant: matchVariant("iYvm_teWy"),
											},
											CRDBQA8Ni: {
												variant: matchVariant("xIDFABIL6"),
												wosVXczZ8: wosVXczZ8j22lm4,
											},
											diJpg71nc: {
												variant: matchVariant("iYvm_teWy"),
											},
											DSU7R5rXG: {
												variant: matchVariant("iYvm_teWy"),
											},
											HnQjsRIb5: {
												variant: matchVariant("xIDFABIL6"),
												wosVXczZ8: wosVXczZ8j22lm4,
											},
											KW98uve0H: {
												variant: matchVariant("bXjwysvDb"),
												wosVXczZ8: wosVXczZ81fq4b78,
											},
											pZ2xXWQV8: {
												variant: matchVariant("xIDFABIL6"),
												wosVXczZ8: wosVXczZ8j22lm4,
											},
											TP9pnK002: {
												variant: matchVariant("bXjwysvDb"),
												wosVXczZ8: wosVXczZ81fq4b78,
											},
											YLbpgkMIK: {
												variant: matchVariant("bXjwysvDb"),
												wosVXczZ8: wosVXczZ81fq4b78,
											},
										},
										baseVariant,
										gestureVariant,
									),
								})}
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
						<ComponentViewportProvider
							suppressHydrationWarning={true}
							height={539}
							width={componentViewport?.width || "100vw"}
							y={
								(componentViewport?.y || 0) +
								0 +
								(((componentViewport?.height || 200) - 0 - 2157) / 2 + 540 + 0)
							}
						>
							<SmartComponentScopedContainer
								suppressHydrationWarning={true}
								className={"framer-1l5eqpy-container"}
								layoutDependency={layoutDependency}
								layoutId={"cvmU37lSi-container"}
								nodeId={"cvmU37lSi"}
								rendersWithMotion={true}
								scopeId={"dgJgDbddj"}
							>
								{_jsx3(stdin_default3, {
									suppressHydrationWarning: true,
									b4x1S95yl: "002",
									cJN5npylT: "Tool",
									height: "100%",
									id: "cvmU37lSi",
									layoutId: "cvmU37lSi",
									nw1uBaV6t: "Brand Identity Design",
									q11frw_6a:
										"We turn messy, overwhelming numbers into clean, real-time dashboards . You get total visibility over your performance at a glance",
									QAmPNlhZE: addImageAlt(
										{
											pixelHeight: 3100,
											pixelWidth: 2067,
											src: "https://framerusercontent.com/images/4leZXqgXA37Wrhvh6oGZ18no.jpeg?width=2067&height=3100",
											srcSet:
												"https://framerusercontent.com/images/4leZXqgXA37Wrhvh6oGZ18no.jpeg?scale-down-to=1024&width=2067&height=3100 682w,https://framerusercontent.com/images/4leZXqgXA37Wrhvh6oGZ18no.jpeg?scale-down-to=2048&width=2067&height=3100 1365w,https://framerusercontent.com/images/4leZXqgXA37Wrhvh6oGZ18no.jpeg?width=2067&height=3100 2067w",
										},
										"Image",
									),
									style: {
										width: "100%",
									},
									TDgHPEQwH: "Brand Strategy",
									variant: matchVariant("iYvm_teWy"),
									VbzDQR2gK: "What We Do",
									width: "100%",
									wosVXczZ8: wosVXczZ8e4v2tb,
									zlPOMfz7O: "Data Visualization",
									...addPropertyOverrides3(
										{
											aqDZcY3HY: {
												variant: matchVariant("xIDFABIL6"),
												wosVXczZ8: wosVXczZ81js2cfs,
											},
											bsbqcBHjk: {
												variant: matchVariant("bXjwysvDb"),
												wosVXczZ8: wosVXczZ8lcpf15,
											},
											c7l66Iuz3: {
												QAmPNlhZE: addImageAlt(
													{
														pixelHeight: 1816,
														pixelWidth: 2067,
														src: "https://framerusercontent.com/images/2P73aCIGjwK6TVyFtXdvZYomRAg.jpeg?width=2067&height=1816",
														srcSet:
															"https://framerusercontent.com/images/2P73aCIGjwK6TVyFtXdvZYomRAg.jpeg?scale-down-to=512&width=2067&height=1816 512w,https://framerusercontent.com/images/2P73aCIGjwK6TVyFtXdvZYomRAg.jpeg?scale-down-to=1024&width=2067&height=1816 1024w,https://framerusercontent.com/images/2P73aCIGjwK6TVyFtXdvZYomRAg.jpeg?scale-down-to=2048&width=2067&height=1816 2048w,https://framerusercontent.com/images/2P73aCIGjwK6TVyFtXdvZYomRAg.jpeg?width=2067&height=1816 2067w",
													},
													"Image",
												),
												variant: matchVariant("ebies0UJf"),
											},
											CRDBQA8Ni: {
												variant: matchVariant("xIDFABIL6"),
												wosVXczZ8: wosVXczZ81js2cfs,
											},
											DSU7R5rXG: {
												nw1uBaV6t: "Graphs",
												TDgHPEQwH: "Dashboards",
											},
											HnQjsRIb5: {
												variant: matchVariant("xIDFABIL6"),
												wosVXczZ8: wosVXczZ81js2cfs,
											},
											KW98uve0H: {
												variant: matchVariant("bXjwysvDb"),
												wosVXczZ8: wosVXczZ8lcpf15,
											},
											pZ2xXWQV8: {
												variant: matchVariant("bsaUq_sxi"),
												wosVXczZ8: wosVXczZ81js2cfs,
											},
											TP9pnK002: {
												variant: matchVariant("bXjwysvDb"),
												wosVXczZ8: wosVXczZ8lcpf15,
											},
											YLbpgkMIK: {
												variant: matchVariant("i7ExtuCiy"),
												wosVXczZ8: wosVXczZ8lcpf15,
											},
										},
										baseVariant,
										gestureVariant,
									),
								})}
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
						<ComponentViewportProvider
							suppressHydrationWarning={true}
							height={539}
							width={componentViewport?.width || "100vw"}
							y={
								(componentViewport?.y || 0) +
								0 +
								(((componentViewport?.height || 200) - 0 - 2157) / 2 + 1079 + 0)
							}
						>
							<SmartComponentScopedContainer
								suppressHydrationWarning={true}
								className={"framer-17l00rh-container"}
								layoutDependency={layoutDependency}
								layoutId={"FOHIrSS4e-container"}
								nodeId={"FOHIrSS4e"}
								rendersWithMotion={true}
								scopeId={"dgJgDbddj"}
							>
								{_jsx3(stdin_default3, {
									suppressHydrationWarning: true,
									b4x1S95yl: "003",
									cJN5npylT: "Tool",
									height: "100%",
									id: "FOHIrSS4e",
									layoutId: "FOHIrSS4e",
									nw1uBaV6t: "Brand Identity Design",
									q11frw_6a:
										"We go beyond the numbers to tell you what they mean. We monitor your funnels and Cost Per Lead (CPL) to extract actionable insights that stop wasted ad spend and increase your ROI.",
									QAmPNlhZE: addImageAlt(
										{
											pixelHeight: 652,
											pixelWidth: 614,
											src: "https://framerusercontent.com/images/HZNX64mZrWqrMbpQRIt7YNePNM0.png?width=614&height=652",
											srcSet:
												"https://framerusercontent.com/images/HZNX64mZrWqrMbpQRIt7YNePNM0.png?width=614&height=652 614w",
										},
										"Image",
									),
									style: {
										width: "100%",
									},
									TDgHPEQwH: "Brand Strategy",
									variant: matchVariant("iYvm_teWy"),
									VbzDQR2gK: "How We Work",
									width: "100%",
									wosVXczZ8: wosVXczZ8fsx9u6,
									zlPOMfz7O: "Data Analysis",
									...addPropertyOverrides3(
										{
											aqDZcY3HY: {
												variant: matchVariant("xIDFABIL6"),
												wosVXczZ8: wosVXczZ8l09aup,
											},
											bsbqcBHjk: {
												variant: matchVariant("bXjwysvDb"),
												wosVXczZ8: wosVXczZ8b9tzhz,
											},
											CRDBQA8Ni: {
												variant: matchVariant("bsaUq_sxi"),
												wosVXczZ8: wosVXczZ8l09aup,
											},
											diJpg71nc: {
												nw1uBaV6t: "Funnel",
												QAmPNlhZE: addImageAlt(
													{
														pixelHeight: 3264,
														pixelWidth: 4764,
														src: "https://framerusercontent.com/images/0eMZxBxgIDx0zeicAr7s66iQPSg.jpeg?width=4764&height=3264",
														srcSet:
															"https://framerusercontent.com/images/0eMZxBxgIDx0zeicAr7s66iQPSg.jpeg?scale-down-to=512&width=4764&height=3264 512w,https://framerusercontent.com/images/0eMZxBxgIDx0zeicAr7s66iQPSg.jpeg?scale-down-to=1024&width=4764&height=3264 1024w,https://framerusercontent.com/images/0eMZxBxgIDx0zeicAr7s66iQPSg.jpeg?scale-down-to=2048&width=4764&height=3264 2048w,https://framerusercontent.com/images/0eMZxBxgIDx0zeicAr7s66iQPSg.jpeg?scale-down-to=4096&width=4764&height=3264 4096w,https://framerusercontent.com/images/0eMZxBxgIDx0zeicAr7s66iQPSg.jpeg?width=4764&height=3264 4764w",
													},
													"Image",
												),
												TDgHPEQwH: "Optimization",
												variant: matchVariant("ebies0UJf"),
											},
											HnQjsRIb5: {
												variant: matchVariant("xIDFABIL6"),
												wosVXczZ8: wosVXczZ8l09aup,
											},
											KW98uve0H: {
												variant: matchVariant("i7ExtuCiy"),
												wosVXczZ8: wosVXczZ8b9tzhz,
											},
											pZ2xXWQV8: {
												variant: matchVariant("xIDFABIL6"),
												wosVXczZ8: wosVXczZ8l09aup,
											},
											TP9pnK002: {
												variant: matchVariant("bXjwysvDb"),
												wosVXczZ8: wosVXczZ8b9tzhz,
											},
											YLbpgkMIK: {
												variant: matchVariant("bXjwysvDb"),
												wosVXczZ8: wosVXczZ8b9tzhz,
											},
										},
										baseVariant,
										gestureVariant,
									),
								})}
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
						<ComponentViewportProvider
							suppressHydrationWarning={true}
							height={539}
							width={componentViewport?.width || "100vw"}
							y={
								(componentViewport?.y || 0) +
								0 +
								(((componentViewport?.height || 200) - 0 - 2157) / 2 + 1618 + 0)
							}
						>
							<SmartComponentScopedContainer
								suppressHydrationWarning={true}
								className={"framer-1um8l4p-container"}
								layoutDependency={layoutDependency}
								layoutId={"uTo7mYQuu-container"}
								nodeId={"uTo7mYQuu"}
								rendersWithMotion={true}
								scopeId={"dgJgDbddj"}
							>
								{_jsx3(stdin_default3, {
									suppressHydrationWarning: true,
									b4x1S95yl: "004",
									cJN5npylT: "Tool",
									height: "100%",
									id: "uTo7mYQuu",
									layoutId: "uTo7mYQuu",
									nw1uBaV6t: "Brand Identity Design",
									q11frw_6a:
										"We replace guesswork with a data-driven system. We use your hard data to guide your brand strategy, website, socials, and email marketing to ensure every piece of creative actually converts.",
									QAmPNlhZE: addImageAlt(
										{
											pixelHeight: 1038,
											pixelWidth: 1908,
											src: "https://framerusercontent.com/images/jhk7pbQqXjP3pz7o1dSbjyG4eoY.png?width=1908&height=1038",
											srcSet:
												"https://framerusercontent.com/images/jhk7pbQqXjP3pz7o1dSbjyG4eoY.png?scale-down-to=512&width=1908&height=1038 512w,https://framerusercontent.com/images/jhk7pbQqXjP3pz7o1dSbjyG4eoY.png?scale-down-to=1024&width=1908&height=1038 1024w,https://framerusercontent.com/images/jhk7pbQqXjP3pz7o1dSbjyG4eoY.png?width=1908&height=1038 1908w",
										},
										"Image",
									),
									style: {
										width: "100%",
									},
									TDgHPEQwH: "Brand Strategy",
									variant: matchVariant("iYvm_teWy"),
									VbzDQR2gK: "How We Add Value",
									width: "100%",
									wosVXczZ8: wosVXczZ8cm6zyx,
									zlPOMfz7O: "Creative Marketing",
									...addPropertyOverrides3(
										{
											aqDZcY3HY: {
												variant: matchVariant("xIDFABIL6"),
												wosVXczZ8: wosVXczZ8oezqps,
											},
											bsbqcBHjk: {
												variant: matchVariant("bXjwysvDb"),
												wosVXczZ8: wosVXczZ8b4i9zq,
											},
											CRDBQA8Ni: {
												variant: matchVariant("xIDFABIL6"),
												wosVXczZ8: wosVXczZ8oezqps,
											},
											DSU7R5rXG: {
												variant: matchVariant("ebies0UJf"),
											},
											HnQjsRIb5: {
												variant: matchVariant("bsaUq_sxi"),
												wosVXczZ8: wosVXczZ8l09aup,
											},
											KW98uve0H: {
												variant: matchVariant("bXjwysvDb"),
												wosVXczZ8: wosVXczZ8b4i9zq,
											},
											pZ2xXWQV8: {
												variant: matchVariant("xIDFABIL6"),
												wosVXczZ8: wosVXczZ8oezqps,
											},
											TP9pnK002: {
												variant: matchVariant("i7ExtuCiy"),
												wosVXczZ8: wosVXczZ8b4i9zq,
											},
											YLbpgkMIK: {
												variant: matchVariant("bXjwysvDb"),
												wosVXczZ8: wosVXczZ8b4i9zq,
											},
										},
										baseVariant,
										gestureVariant,
									),
								})}
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
					</motion3.section>
				</Transition3>
			</Variants3>
		</LayoutGroup3>
	);
});
var css6 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-7Q4cq.framer-3cc6zv, .framer-7Q4cq .framer-3cc6zv { display: block; }",
	".framer-7Q4cq.framer-bomeh3 { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 1140px; }",
	".framer-7Q4cq .framer-ugzwx8-container, .framer-7Q4cq .framer-192ipgt-container, .framer-7Q4cq .framer-1l5eqpy-container, .framer-7Q4cq .framer-17l00rh-container, .framer-7Q4cq .framer-1um8l4p-container { flex: none; height: auto; position: relative; width: 100%; }",
	".framer-7Q4cq.framer-v-bavduv.framer-bomeh3, .framer-7Q4cq.framer-v-4103c2.framer-bomeh3, .framer-7Q4cq.framer-v-qda8ct.framer-bomeh3, .framer-7Q4cq.framer-v-1l2t64g.framer-bomeh3 { width: 750px; }",
	".framer-7Q4cq.framer-v-1ud0pif.framer-bomeh3, .framer-7Q4cq.framer-v-1tt65mz.framer-bomeh3, .framer-7Q4cq.framer-v-17pp67b.framer-bomeh3, .framer-7Q4cq.framer-v-znh65v.framer-bomeh3 { width: 350px; }",
];
var FramerdgJgDbddj = withCSS3(Component3, css6, "framer-7Q4cq");
var stdin_default5 = FramerdgJgDbddj;
FramerdgJgDbddj.displayName = "Service Card Wrapper";
FramerdgJgDbddj.defaultProps = {
	height: 1185,
	width: 1140,
};
addPropertyControls3(FramerdgJgDbddj, {
	variant: {
		options: [
			"s3BRDnDV3",
			"c7l66Iuz3",
			"diJpg71nc",
			"DSU7R5rXG",
			"aqDZcY3HY",
			"pZ2xXWQV8",
			"CRDBQA8Ni",
			"HnQjsRIb5",
			"bsbqcBHjk",
			"YLbpgkMIK",
			"KW98uve0H",
			"TP9pnK002",
		],
		optionTitles: [
			"Desktop 01",
			"Desktop 02",
			"Desktop 03",
			"Desktop 04",
			"Tablet 01",
			"Tablet 02",
			"Tablet 03",
			"Tablet 04",
			"Phone 01",
			"Phone 02",
			"Phone 03",
			"Phone 04",
		],
		title: "Variant",
		type: ControlType3.Enum,
	},
});
addFonts3(
	FramerdgJgDbddj,
	[
		{
			explicitInter: true,
			fonts: [],
		},
		...LineFonts,
		...ServiceCardFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);
FramerdgJgDbddj.loader = {
	load: (props, context) => {
		const locale = context.locale;
		return Promise.allSettled([
			forwardLoader(stdin_default4, {}, context),
			forwardLoader(stdin_default3, {}, context),
		]);
	},
};

// virtual:service-card-wrapper
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "bsbqcBHjk",
	md: "aqDZcY3HY",
	xl: "s3BRDnDV3",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"1907350542b7624112d99063e9127837bac05866cdf3676335c1d928983f49a3"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default5, {
				suppressHydrationWarning: true,
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders ServiceCardWrapperFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"1907350542b7624112d99063e9127837bac05866cdf3676335c1d928983f49a3"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				suppressHydrationWarning={true}
				Component={stdin_default5}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default5);
var service_card_wrapper_default = ComponentWithRoot;
export { service_card_wrapper_default as default };
