// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 1907350542b76241 "Blimpy", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * title?: string // Title
 * link?: string // Link
}} Props

 */
import { className, css, fonts } from "./chunks/chunk-CM7YMXDZ.js";
import { routes } from "./chunks/chunk-RHU4XTMM.js";

// virtual:social-media
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/XG4RDJW08XScwzr5slEZ/uMRvc7mCShjal4JEyd8B/DBmlL1xvz.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	getLoadingLazyAtYPosition,
	Image,
	Link,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var enabledGestures = {
	hC0LQWAPc: {
		hover: true,
	},
};
var serializationHash = "framer-5uRdg";
var variantClassNames = {
	hC0LQWAPc: "framer-v-1urq3dp",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider
			suppressHydrationWarning={true}
			value={contextValue}
		>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var getProps = ({ height, id, link, title, width, ...props }) => {
	return {
		...props,
		DDX1QhrKi: title ?? props.DDX1QhrKi ?? "Instagram",
		V5M8VmxTV: link ?? props.V5M8VmxTV,
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		DDX1QhrKi,
		V5M8VmxTV,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		defaultVariant: "hC0LQWAPc",
		enabledGestures,
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup
			suppressHydrationWarning={true}
			id={layoutId ?? defaultLayoutId}
		>
			<Variants
				suppressHydrationWarning={true}
				animate={variants}
				initial={false}
			>
				<Transition suppressHydrationWarning={true} value={transition1}>
					<Link
						suppressHydrationWarning={true}
						href={V5M8VmxTV}
						motionChild={true}
						nodeId={"hC0LQWAPc"}
						openInNewTab={false}
						scopeId={"DBmlL1xvz"}
					>
						<motion.a
							suppressHydrationWarning={true}
							{...restProps}
							{...gestureHandlers}
							className={`${cx(scopingClassNames, "framer-1urq3dp", className2, classNames)} framer-186ej6u`}
							data-border={true}
							data-framer-name={"Default"}
							layoutDependency={layoutDependency}
							layoutId={"hC0LQWAPc"}
							ref={refBinding}
							style={{
								"--border-bottom-width": "1px",
								"--border-color":
									"var(--token-aad9f953-7a89-4aa6-8b88-7994cb74103e, rgba(255, 255, 255, 0.1))",
								"--border-left-width": "0px",
								"--border-right-width": "0px",
								"--border-style": "solid",
								"--border-top-width": "0px",
								...style,
							}}
							variants={{
								"hC0LQWAPc-hover": {
									"--border-color":
										"var(--token-d0efb30f-1ca4-4318-a615-3c27c4e89f33, rgb(255, 31, 0))",
								},
							}}
							{...addPropertyOverrides(
								{
									"hC0LQWAPc-hover": {
										"data-framer-name": void 0,
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<RichText
								suppressHydrationWarning={true}
								__fromCanvasComponent={true}
								className={"framer-l6mgpa"}
								data-framer-name={"Instagram"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"cXpXsKV7b"}
								style={{
									"--framer-paragraph-spacing": "0px",
								}}
								text={DDX1QhrKi}
								variants={{
									"hC0LQWAPc-hover": {
										"--extracted-r6o4lv":
											"var(--token-d0efb30f-1ca4-4318-a615-3c27c4e89f33, rgb(255, 31, 0))",
									},
								}}
								verticalAlignment={"top"}
								withExternalLayout={true}
								{...addPropertyOverrides(
									{
										"hC0LQWAPc-hover": {
											children: (
												<React.Fragment>
													<motion.p
														suppressHydrationWarning={true}
														className={"framer-styles-preset-g7itge"}
														data-styles-preset={"YyydkF6BV"}
														style={{
															"--framer-text-color":
																"var(--extracted-r6o4lv, var(--token-d0efb30f-1ca4-4318-a615-3c27c4e89f33, rgb(255, 31, 0)))",
														}}
													>
														{"Instagram"}
													</motion.p>
												</React.Fragment>
											),
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<React.Fragment>
									<motion.p
										suppressHydrationWarning={true}
										className={"framer-styles-preset-g7itge"}
										data-styles-preset={"YyydkF6BV"}
									>
										{"Instagram"}
									</motion.p>
								</React.Fragment>
							</RichText>
							<motion.div
								suppressHydrationWarning={true}
								className={"framer-15rhicy"}
								data-framer-name={"Icon Wrap"}
								layoutDependency={layoutDependency}
								layoutId={"hrQoYUAax"}
							>
								<Image
									suppressHydrationWarning={true}
									background={{
										alt: "Icon",
										fit: "fill",
										loading: getLoadingLazyAtYPosition(
											(componentViewport?.y || 0) +
												(8 +
													((componentViewport?.height || 38) - 16 - 16) / 2) +
												0,
										),
										pixelHeight: 16,
										pixelWidth: 16,
										src: "https://framerusercontent.com/images/PmjCAJo5u9oeCyTwnACNgpHXU.svg",
									}}
									className={"framer-qbc8p7"}
									layoutDependency={layoutDependency}
									layoutId={"u8UYjBu9a"}
									{...addPropertyOverrides(
										{
											"hC0LQWAPc-hover": {
												background: {
													alt: "Icon",
													fit: "fill",
													loading: getLoadingLazyAtYPosition(
														(componentViewport?.y || 0) +
															(8 +
																((componentViewport?.height || 38) - 16 - 16) /
																	2) +
															-18,
													),
													pixelHeight: 16,
													pixelWidth: 16,
													src: "https://framerusercontent.com/images/PmjCAJo5u9oeCyTwnACNgpHXU.svg",
												},
											},
										},
										baseVariant,
										gestureVariant,
									)}
								/>
								<Image
									suppressHydrationWarning={true}
									background={{
										alt: "Icon",
										fit: "fill",
										loading: getLoadingLazyAtYPosition(
											(componentViewport?.y || 0) +
												(8 +
													((componentViewport?.height || 38) - 16 - 16) / 2) +
												16 -
												-2,
										),
										pixelHeight: 16,
										pixelWidth: 16,
										src: "https://framerusercontent.com/images/XSbNMjwOQEX6uzVqkadpKX9DDE.svg",
									}}
									className={"framer-1s42za5"}
									layoutDependency={layoutDependency}
									layoutId={"mOWOYjFHa"}
									{...addPropertyOverrides(
										{
											"hC0LQWAPc-hover": {
												background: {
													alt: "Icon",
													fit: "fill",
													loading: getLoadingLazyAtYPosition(
														(componentViewport?.y || 0) +
															(8 +
																((componentViewport?.height || 38) - 16 - 16) /
																	2) +
															0,
													),
													pixelHeight: 16,
													pixelWidth: 16,
													src: "https://framerusercontent.com/images/XSbNMjwOQEX6uzVqkadpKX9DDE.svg",
												},
											},
										},
										baseVariant,
										gestureVariant,
									)}
								/>
							</motion.div>
						</motion.a>
					</Link>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css2 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-5uRdg.framer-186ej6u, .framer-5uRdg .framer-186ej6u { display: block; }",
	".framer-5uRdg.framer-1urq3dp { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; height: min-content; justify-content: space-between; max-width: 305px; overflow: hidden; padding: 8px 0px 8px 0px; position: relative; text-decoration: none; width: 305px; }",
	".framer-5uRdg .framer-l6mgpa { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-5uRdg .framer-15rhicy { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: min-content; }",
	".framer-5uRdg .framer-qbc8p7 { flex: none; height: 16px; position: relative; width: 16px; }",
	".framer-5uRdg .framer-1s42za5 { bottom: -18px; flex: none; height: 16px; left: -18px; position: absolute; width: 16px; z-index: 1; }",
	".framer-5uRdg.framer-v-1urq3dp.hover .framer-qbc8p7 { position: absolute; right: -18px; top: -18px; z-index: 1; }",
	".framer-5uRdg.framer-v-1urq3dp.hover .framer-1s42za5 { bottom: unset; left: unset; position: relative; }",
	...css,
	'.framer-5uRdg[data-border="true"]::after, .framer-5uRdg [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var FramerDBmlL1xvz = withCSS(Component, css2, "framer-5uRdg");
var stdin_default = FramerDBmlL1xvz;
FramerDBmlL1xvz.displayName = "Social Media";
FramerDBmlL1xvz.defaultProps = {
	height: 38,
	width: 305,
};
addPropertyControls(FramerDBmlL1xvz, {
	DDX1QhrKi: {
		defaultValue: "Instagram",
		displayTextArea: false,
		title: "Title",
		type: ControlType.String,
	},
	V5M8VmxTV: {
		title: "Link",
		type: ControlType.Link,
	},
});
addFonts(
	FramerDBmlL1xvz,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:social-media
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"1907350542b7624112d99063e9127837bac05866cdf3676335c1d928983f49a3"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				suppressHydrationWarning: true,
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders SocialMediaFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"1907350542b7624112d99063e9127837bac05866cdf3676335c1d928983f49a3"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				suppressHydrationWarning={true}
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var social_media_default = ComponentWithRoot;
export { social_media_default as default };
