// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 1907350542b76241 "Blimpy", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop 01' | 'Desktop 02' | 'Desktop 03' | 'Phone 01' | 'Phone 02' | 'Phone 03' // Variant
}} Props

 */
import { stdin_default } from "./chunks/chunk-ERJ7FTR5.js";
import "./chunks/chunk-S5VMJNA7.js";
import { routes } from "./chunks/chunk-RHU4XTMM.js";

// virtual:testimonial-slider
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/awFGMdfuPi5ssaaKuv1G/0rDEq1dvJlXBGErWY2vf/tBrVeUFNs.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	forwardLoader,
	getFonts,
	getFontsFromSharedStyle,
	getLoadingLazyAtYPosition,
	Image,
	RichText,
	SmartComponentScopedContainer,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";

// /:https://framerusercontent.com/modules/ep7s5zGzXdZhzh5mpxg3/UAcIUNbjkkwgusdM37oa/WuyqCLdzP.js
import { fontStore } from "unframer";
fontStore.loadFonts([
	"Inter",
	"Inter-Bold",
	"Inter-BoldItalic",
	"Inter-Italic",
]);
var fonts = [
	{
		explicitInter: true,
		fonts: [
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
				url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
				url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange: "U+1F00-1FFF",
				url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange: "U+0370-03FF",
				url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
				url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
				url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
				url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
				url: "https://framerusercontent.com/assets/DpPBYI0sL4fYLgAkX8KXOPVt7c.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
				url: "https://framerusercontent.com/assets/4RAEQdEOrcnDkhHiiCbJOw92Lk.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange: "U+1F00-1FFF",
				url: "https://framerusercontent.com/assets/1K3W8DizY3v4emK8Mb08YHxTbs.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange: "U+0370-03FF",
				url: "https://framerusercontent.com/assets/tUSCtfYVM1I1IchuyCwz9gDdQ.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
				url: "https://framerusercontent.com/assets/VgYFWiwsAC5OYxAycRXXvhze58.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
				url: "https://framerusercontent.com/assets/DXD0Q7LSl7HEvDzucnyLnGBHM.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
				url: "https://framerusercontent.com/assets/GIryZETIX4IFypco5pYZONKhJIo.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
				url: "https://framerusercontent.com/assets/H89BbHkbHDzlxZzxi8uPzTsp90.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
				url: "https://framerusercontent.com/assets/u6gJwDuwB143kpNK1T1MDKDWkMc.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+1F00-1FFF",
				url: "https://framerusercontent.com/assets/43sJ6MfOPh1LCJt46OvyDuSbA6o.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+0370-03FF",
				url: "https://framerusercontent.com/assets/wccHG0r4gBDAIRhfHiOlq6oEkqw.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
				url: "https://framerusercontent.com/assets/WZ367JPwf9bRW6LdTHN8rXgSjw.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
				url: "https://framerusercontent.com/assets/QxmhnWTzLtyjIiZcfaLIJ8EFBXU.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
				url: "https://framerusercontent.com/assets/2A4Xx7CngadFGlVV4xrO06OBHY.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
				url: "https://framerusercontent.com/assets/CfMzU8w2e7tHgF4T4rATMPuWosA.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
				url: "https://framerusercontent.com/assets/867QObYax8ANsfX4TGEVU9YiCM.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+1F00-1FFF",
				url: "https://framerusercontent.com/assets/Oyn2ZbENFdnW7mt2Lzjk1h9Zb9k.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+0370-03FF",
				url: "https://framerusercontent.com/assets/cdAe8hgZ1cMyLu9g005pAW3xMo.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
				url: "https://framerusercontent.com/assets/DOfvtmE1UplCq161m6Hj8CSQYg.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
				url: "https://framerusercontent.com/assets/vFzuJY0c65av44uhEKB6vyjFMg.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
				url: "https://framerusercontent.com/assets/tKtBcDnBMevsEEJKdNGhhkLzYo.woff2",
				weight: "400",
			},
		],
	},
];
var css = [
	`.framer-wo5Us .framer-styles-preset-2aypun:not(.rich-text-wrapper), .framer-wo5Us .framer-styles-preset-2aypun.rich-text-wrapper p { --framer-font-family: "Inter", sans-serif; --framer-font-family-bold: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-bold-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-open-type-features: 'blwf' on, 'cv09' on, 'cv03' on, 'cv04' on, 'cv11' on; --framer-font-size: 12px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 400; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 400; --framer-letter-spacing: 1em; --framer-line-height: 1.2em; --framer-paragraph-spacing: 20px; --framer-text-alignment: start; --framer-text-color: var(--token-1ca63064-b503-4f13-8e66-ff201796eaf9, #ffffff); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; }`,
];
var className = "framer-wo5Us";

// /:https://framerusercontent.com/modules/awFGMdfuPi5ssaaKuv1G/0rDEq1dvJlXBGErWY2vf/tBrVeUFNs.js
var TestimonialCardFonts = getFonts(stdin_default);
var cycleOrder = [
	"d1YZz2RkZ",
	"FW7nM1M9g",
	"Jkarm6NYz",
	"pKN98hdhU",
	"uYhzLTjBi",
	"VDxAFIZpl",
];
var serializationHash = "framer-kfORU";
var variantClassNames = {
	d1YZz2RkZ: "framer-v-12nsmg7",
	FW7nM1M9g: "framer-v-1om9vg2",
	Jkarm6NYz: "framer-v-8ty6mj",
	pKN98hdhU: "framer-v-102cxdk",
	uYhzLTjBi: "framer-v-1o12xxq",
	VDxAFIZpl: "framer-v-3nvegh",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	delay: 0,
	duration: 0.3,
	ease: [0.44, 0, 0.56, 1],
	type: "tween",
};
var addImageAlt = (image, alt) => {
	if (!image || typeof image !== "object") {
		return;
	}
	return {
		...image,
		alt,
	};
};
var transformTemplate1 = (_, t) => `translateY(-50%) ${t}`;
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider
			suppressHydrationWarning={true}
			value={contextValue}
		>
			{children}
		</MotionConfigContext.Provider>
	);
};
var humanReadableVariantMap = {
	"Desktop 01": "d1YZz2RkZ",
	"Desktop 02": "FW7nM1M9g",
	"Desktop 03": "Jkarm6NYz",
	"Phone 01": "pKN98hdhU",
	"Phone 02": "uYhzLTjBi",
	"Phone 03": "VDxAFIZpl",
};
var Variants = motion.create(React.Fragment);
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "d1YZz2RkZ",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "d1YZz2RkZ",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onTap1mbzsy = activeVariantCallback(async (...args) => {
		setVariant("Jkarm6NYz");
	});
	const onTap1od0571 = activeVariantCallback(async (...args) => {
		setVariant("d1YZz2RkZ");
	});
	const onTap1s2ygtq = activeVariantCallback(async (...args) => {
		setVariant("FW7nM1M9g");
	});
	const onTap1hq9rgt = activeVariantCallback(async (...args) => {
		setVariant("VDxAFIZpl");
	});
	const onTap3jdxvc = activeVariantCallback(async (...args) => {
		setVariant("pKN98hdhU");
	});
	const onTapwgftql = activeVariantCallback(async (...args) => {
		setVariant("uYhzLTjBi");
	});
	const sharedStyleClassNames = [className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup
			suppressHydrationWarning={true}
			id={layoutId ?? defaultLayoutId}
		>
			<Variants
				suppressHydrationWarning={true}
				animate={variants}
				initial={false}
			>
				<Transition suppressHydrationWarning={true} value={transition1}>
					<motion.div
						suppressHydrationWarning={true}
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-12nsmg7",
							className2,
							classNames,
						)}
						data-framer-name={"Desktop 01"}
						layoutDependency={layoutDependency}
						layoutId={"d1YZz2RkZ"}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								FW7nM1M9g: {
									"data-framer-name": "Desktop 02",
								},
								Jkarm6NYz: {
									"data-framer-name": "Desktop 03",
								},
								pKN98hdhU: {
									"data-framer-name": "Phone 01",
								},
								uYhzLTjBi: {
									"data-framer-name": "Phone 02",
								},
								VDxAFIZpl: {
									"data-framer-name": "Phone 03",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							suppressHydrationWarning={true}
							className={"framer-17w7bd9"}
							data-framer-name={"Testimonial Card"}
							layoutDependency={layoutDependency}
							layoutId={"IUPi6Rdr4"}
						>
							<motion.div
								suppressHydrationWarning={true}
								className={"framer-1j0qf9e"}
								data-framer-name={"Icon Wrappper"}
								layoutDependency={layoutDependency}
								layoutId={"CCL9NQINM"}
							>
								<motion.div
									suppressHydrationWarning={true}
									className={"framer-492kw6"}
									data-framer-name={"Round"}
									layoutDependency={layoutDependency}
									layoutId={"sx20Rl5HJ"}
								>
									<Image
										suppressHydrationWarning={true}
										background={{
											alt: "Profile Image",
											fit: "fill",
											loading: getLoadingLazyAtYPosition(
												(componentViewport?.y || 0) +
													(0 +
														((componentViewport?.height || 376) - 0 - 376) /
															2) +
													0 +
													238 +
													0 +
													0 +
													0,
											),
											pixelHeight: 154,
											pixelWidth: 154,
											sizes: "60px",
											src: "https://framerusercontent.com/images/DGjSNMB1BIWkMxKap1Fw3Dvz1uA.png?width=154&height=154",
										}}
										className={"framer-r6zf38"}
										data-framer-name={"Active"}
										layoutDependency={layoutDependency}
										layoutId={"lwy0Kzk43"}
										style={{
											backgroundColor: "rgba(0, 0, 0, 0)",
											borderBottomLeftRadius: 70,
											borderBottomRightRadius: 70,
											borderTopLeftRadius: 70,
											borderTopRightRadius: 70,
										}}
										variants={{
											FW7nM1M9g: {
												backgroundColor:
													"var(--token-687c2cb1-72a4-49d6-83df-e200278f840d, rgb(178, 158, 158))",
											},
											Jkarm6NYz: {
												backgroundColor:
													"var(--token-1ca63064-b503-4f13-8e66-ff201796eaf9, rgb(255, 255, 255))",
											},
											pKN98hdhU: {
												backgroundColor: "rgba(0, 0, 0, 0)",
											},
											uYhzLTjBi: {
												backgroundColor:
													"var(--token-687c2cb1-72a4-49d6-83df-e200278f840d, rgb(178, 158, 158))",
											},
											VDxAFIZpl: {
												backgroundColor:
													"var(--token-1ca63064-b503-4f13-8e66-ff201796eaf9, rgb(255, 255, 255))",
											},
										}}
										{...addPropertyOverrides(
											{
												FW7nM1M9g: {
													background: void 0,
												},
												Jkarm6NYz: {
													background: void 0,
												},
												pKN98hdhU: {
													background: {
														alt: "Profile Image",
														fit: "fill",
														loading: getLoadingLazyAtYPosition(
															(componentViewport?.y || 0) +
																(0 +
																	((componentViewport?.height || 805) -
																		0 -
																		532) /
																		2) +
																0 +
																406 +
																0 +
																0 +
																0,
														),
														pixelHeight: 154,
														pixelWidth: 154,
														sizes: "60px",
														src: "https://framerusercontent.com/images/DGjSNMB1BIWkMxKap1Fw3Dvz1uA.png?width=154&height=154",
													},
												},
												uYhzLTjBi: {
													background: void 0,
												},
												VDxAFIZpl: {
													background: void 0,
												},
											},
											baseVariant,
											gestureVariant,
										)}
									/>
									<Image
										suppressHydrationWarning={true}
										className={"framer-pt0gdm"}
										data-framer-name={"Active"}
										layoutDependency={layoutDependency}
										layoutId={"VMEQ7zqI8"}
										style={{
											backgroundColor:
												"var(--token-687c2cb1-72a4-49d6-83df-e200278f840d, rgb(178, 158, 158))",
											borderBottomLeftRadius: 70,
											borderBottomRightRadius: 70,
											borderTopLeftRadius: 70,
											borderTopRightRadius: 70,
										}}
										variants={{
											FW7nM1M9g: {
												backgroundColor: "rgba(0, 0, 0, 0)",
											},
											uYhzLTjBi: {
												backgroundColor: "rgba(0, 0, 0, 0)",
											},
										}}
										{...addPropertyOverrides(
											{
												FW7nM1M9g: {
													background: {
														alt: "",
														fit: "fill",
														loading: getLoadingLazyAtYPosition(
															(componentViewport?.y || 0) +
																(0 +
																	((componentViewport?.height || 415) -
																		0 -
																		376) /
																		2) +
																0 +
																238 +
																0 +
																0 +
																0,
														),
														pixelHeight: 128,
														pixelWidth: 128,
														sizes: "60px",
														src: "https://framerusercontent.com/images/JVW5GhwINTocQZTgn4vPooaHE.png?width=128&height=128",
													},
												},
												uYhzLTjBi: {
													background: {
														alt: "",
														fit: "fill",
														loading: getLoadingLazyAtYPosition(
															(componentViewport?.y || 0) +
																(0 +
																	((componentViewport?.height || 572) -
																		0 -
																		572) /
																		2) +
																0 +
																446 +
																0 +
																0 +
																0,
														),
														pixelHeight: 128,
														pixelWidth: 128,
														sizes: "60px",
														src: "https://framerusercontent.com/images/JVW5GhwINTocQZTgn4vPooaHE.png?width=128&height=128",
													},
												},
											},
											baseVariant,
											gestureVariant,
										)}
									/>
									<Image
										suppressHydrationWarning={true}
										className={"framer-gemftp"}
										data-framer-name={"Active"}
										layoutDependency={layoutDependency}
										layoutId={"R5CCyNsvx"}
										style={{
											backgroundColor:
												"var(--token-1ca63064-b503-4f13-8e66-ff201796eaf9, rgb(255, 255, 255))",
											borderBottomLeftRadius: 70,
											borderBottomRightRadius: 70,
											borderTopLeftRadius: 70,
											borderTopRightRadius: 70,
										}}
										variants={{
											Jkarm6NYz: {
												backgroundColor: "rgba(0, 0, 0, 0)",
											},
											VDxAFIZpl: {
												backgroundColor: "rgba(0, 0, 0, 0)",
											},
										}}
										{...addPropertyOverrides(
											{
												Jkarm6NYz: {
													background: {
														alt: "",
														fit: "fill",
														loading: getLoadingLazyAtYPosition(
															(componentViewport?.y || 0) +
																(0 +
																	((componentViewport?.height || 415) -
																		0 -
																		376) /
																		2) +
																0 +
																238 +
																0 +
																0 +
																0,
														),
														pixelHeight: 128,
														pixelWidth: 128,
														sizes: "60px",
														src: "https://framerusercontent.com/images/AuyxBwUZ0oPMjSst7uDG1I0Dj4.png?width=128&height=128",
													},
												},
												VDxAFIZpl: {
													background: {
														alt: "",
														fit: "fill",
														loading: getLoadingLazyAtYPosition(
															(componentViewport?.y || 0) +
																(0 +
																	((componentViewport?.height || 200) -
																		0 -
																		532) /
																		2) +
																0 +
																406 +
																0 +
																0 +
																0,
														),
														pixelHeight: 128,
														pixelWidth: 128,
														sizes: "60px",
														src: "https://framerusercontent.com/images/AuyxBwUZ0oPMjSst7uDG1I0Dj4.png?width=128&height=128",
													},
												},
											},
											baseVariant,
											gestureVariant,
										)}
									/>
								</motion.div>
								<motion.div
									suppressHydrationWarning={true}
									className={"framer-3iax6t"}
									data-framer-name={"Icon Wrapper"}
									layoutDependency={layoutDependency}
									layoutId={"HwOBfLtR6"}
								>
									<Image
										suppressHydrationWarning={true}
										background={{
											alt: "Icon",
											fit: "fill",
											loading: getLoadingLazyAtYPosition(
												(componentViewport?.y || 0) +
													(0 +
														((componentViewport?.height || 376) - 0 - 376) /
															2) +
													0 +
													238 +
													0 +
													102 +
													0,
											),
											pixelHeight: 36,
											pixelWidth: 36,
											sizes: "36px",
											src: "https://framerusercontent.com/images/nlcpDdQe23aA3ehDFLUIMpAK9yk.svg?width=36&height=36",
										}}
										className={"framer-16mxhei"}
										data-highlight={true}
										layoutDependency={layoutDependency}
										layoutId={"v9wlrtb8J"}
										onTap={onTap1mbzsy}
										{...addPropertyOverrides(
											{
												FW7nM1M9g: {
													background: {
														alt: "Icon",
														fit: "fill",
														loading: getLoadingLazyAtYPosition(
															(componentViewport?.y || 0) +
																(0 +
																	((componentViewport?.height || 415) -
																		0 -
																		376) /
																		2) +
																0 +
																238 +
																0 +
																102 +
																0,
														),
														pixelHeight: 36,
														pixelWidth: 36,
														sizes: "36px",
														src: "https://framerusercontent.com/images/nlcpDdQe23aA3ehDFLUIMpAK9yk.svg?width=36&height=36",
													},
													onTap: onTap1od0571,
												},
												Jkarm6NYz: {
													background: {
														alt: "Icon",
														fit: "fill",
														loading: getLoadingLazyAtYPosition(
															(componentViewport?.y || 0) +
																(0 +
																	((componentViewport?.height || 415) -
																		0 -
																		376) /
																		2) +
																0 +
																238 +
																0 +
																102 +
																0,
														),
														pixelHeight: 36,
														pixelWidth: 36,
														sizes: "36px",
														src: "https://framerusercontent.com/images/nlcpDdQe23aA3ehDFLUIMpAK9yk.svg?width=36&height=36",
													},
													onTap: onTap1s2ygtq,
												},
												pKN98hdhU: {
													background: {
														alt: "Icon",
														fit: "fill",
														loading: getLoadingLazyAtYPosition(
															(componentViewport?.y || 0) +
																(0 +
																	((componentViewport?.height || 805) -
																		0 -
																		532) /
																		2) +
																0 +
																406 +
																0 +
																90 +
																0,
														),
														pixelHeight: 36,
														pixelWidth: 36,
														sizes: "36px",
														src: "https://framerusercontent.com/images/nlcpDdQe23aA3ehDFLUIMpAK9yk.svg?width=36&height=36",
													},
													onTap: onTap1hq9rgt,
												},
												uYhzLTjBi: {
													background: {
														alt: "Icon",
														fit: "fill",
														loading: getLoadingLazyAtYPosition(
															(componentViewport?.y || 0) +
																(0 +
																	((componentViewport?.height || 572) -
																		0 -
																		572) /
																		2) +
																0 +
																446 +
																0 +
																90 +
																0,
														),
														pixelHeight: 36,
														pixelWidth: 36,
														sizes: "36px",
														src: "https://framerusercontent.com/images/nlcpDdQe23aA3ehDFLUIMpAK9yk.svg?width=36&height=36",
													},
													onTap: onTap3jdxvc,
												},
												VDxAFIZpl: {
													background: {
														alt: "Icon",
														fit: "fill",
														loading: getLoadingLazyAtYPosition(
															(componentViewport?.y || 0) +
																(0 +
																	((componentViewport?.height || 200) -
																		0 -
																		532) /
																		2) +
																0 +
																406 +
																0 +
																90 +
																0,
														),
														pixelHeight: 36,
														pixelWidth: 36,
														sizes: "36px",
														src: "https://framerusercontent.com/images/nlcpDdQe23aA3ehDFLUIMpAK9yk.svg?width=36&height=36",
													},
													onTap: onTapwgftql,
												},
											},
											baseVariant,
											gestureVariant,
										)}
									/>
									<motion.div
										suppressHydrationWarning={true}
										className={"framer-unl5lv"}
										data-framer-name={"Number"}
										layoutDependency={layoutDependency}
										layoutId={"Y7B3hSmyb"}
									>
										<RichText
											suppressHydrationWarning={true}
											__fromCanvasComponent={true}
											className={"framer-o4gc0k"}
											data-framer-name={"1/3"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"I61:134;11:98"}
											style={{
												"--extracted-r6o4lv":
													"var(--token-1bf6603a-51fd-49de-92b2-631d3644fb40, rgb(250, 250, 250))",
												"--framer-paragraph-spacing": "0px",
											}}
											verticalAlignment={"center"}
											withExternalLayout={true}
											{...addPropertyOverrides(
												{
													FW7nM1M9g: {
														children: (
															<React.Fragment>
																<motion.p
																	suppressHydrationWarning={true}
																	className={"framer-styles-preset-2aypun"}
																	data-styles-preset={"WuyqCLdzP"}
																	style={{
																		"--framer-text-color":
																			"var(--extracted-r6o4lv, var(--token-1bf6603a-51fd-49de-92b2-631d3644fb40, rgb(250, 250, 250)))",
																	}}
																>
																	{"2/3"}
																</motion.p>
															</React.Fragment>
														),
													},
													Jkarm6NYz: {
														children: (
															<React.Fragment>
																<motion.p
																	suppressHydrationWarning={true}
																	className={"framer-styles-preset-2aypun"}
																	data-styles-preset={"WuyqCLdzP"}
																	style={{
																		"--framer-text-color":
																			"var(--extracted-r6o4lv, var(--token-1bf6603a-51fd-49de-92b2-631d3644fb40, rgb(250, 250, 250)))",
																	}}
																>
																	{"3/3"}
																</motion.p>
															</React.Fragment>
														),
													},
													uYhzLTjBi: {
														children: (
															<React.Fragment>
																<motion.p
																	suppressHydrationWarning={true}
																	className={"framer-styles-preset-2aypun"}
																	data-styles-preset={"WuyqCLdzP"}
																	style={{
																		"--framer-text-color":
																			"var(--extracted-r6o4lv, var(--token-1bf6603a-51fd-49de-92b2-631d3644fb40, rgb(250, 250, 250)))",
																	}}
																>
																	{"2/3"}
																</motion.p>
															</React.Fragment>
														),
													},
													VDxAFIZpl: {
														children: (
															<React.Fragment>
																<motion.p
																	suppressHydrationWarning={true}
																	className={"framer-styles-preset-2aypun"}
																	data-styles-preset={"WuyqCLdzP"}
																	style={{
																		"--framer-text-color":
																			"var(--extracted-r6o4lv, var(--token-1bf6603a-51fd-49de-92b2-631d3644fb40, rgb(250, 250, 250)))",
																	}}
																>
																	{"3/3"}
																</motion.p>
															</React.Fragment>
														),
													},
												},
												baseVariant,
												gestureVariant,
											)}
										>
											<React.Fragment>
												<motion.p
													suppressHydrationWarning={true}
													className={"framer-styles-preset-2aypun"}
													data-styles-preset={"WuyqCLdzP"}
													style={{
														"--framer-text-color":
															"var(--extracted-r6o4lv, var(--token-1bf6603a-51fd-49de-92b2-631d3644fb40, rgb(250, 250, 250)))",
													}}
												>
													{"1/3"}
												</motion.p>
											</React.Fragment>
										</RichText>
									</motion.div>
									<Image
										suppressHydrationWarning={true}
										background={{
											alt: "Icon",
											fit: "fill",
											loading: getLoadingLazyAtYPosition(
												(componentViewport?.y || 0) +
													(0 +
														((componentViewport?.height || 376) - 0 - 376) /
															2) +
													0 +
													238 +
													0 +
													102 +
													0,
											),
											pixelHeight: 36,
											pixelWidth: 36,
											sizes: "36px",
											src: "https://framerusercontent.com/images/4tK9E3TjyRxSTIWEmHJWgYKDQY.svg?width=36&height=36",
										}}
										className={"framer-am93m6"}
										data-highlight={true}
										layoutDependency={layoutDependency}
										layoutId={"Bje474aay"}
										onTap={onTap1s2ygtq}
										{...addPropertyOverrides(
											{
												FW7nM1M9g: {
													background: {
														alt: "Icon",
														fit: "fill",
														loading: getLoadingLazyAtYPosition(
															(componentViewport?.y || 0) +
																(0 +
																	((componentViewport?.height || 415) -
																		0 -
																		376) /
																		2) +
																0 +
																238 +
																0 +
																102 +
																0,
														),
														pixelHeight: 36,
														pixelWidth: 36,
														sizes: "36px",
														src: "https://framerusercontent.com/images/4tK9E3TjyRxSTIWEmHJWgYKDQY.svg?width=36&height=36",
													},
													onTap: onTap1mbzsy,
												},
												Jkarm6NYz: {
													background: {
														alt: "Icon",
														fit: "fill",
														loading: getLoadingLazyAtYPosition(
															(componentViewport?.y || 0) +
																(0 +
																	((componentViewport?.height || 415) -
																		0 -
																		376) /
																		2) +
																0 +
																238 +
																0 +
																102 +
																0,
														),
														pixelHeight: 36,
														pixelWidth: 36,
														sizes: "36px",
														src: "https://framerusercontent.com/images/4tK9E3TjyRxSTIWEmHJWgYKDQY.svg?width=36&height=36",
													},
													onTap: onTap1od0571,
												},
												pKN98hdhU: {
													background: {
														alt: "Icon",
														fit: "fill",
														loading: getLoadingLazyAtYPosition(
															(componentViewport?.y || 0) +
																(0 +
																	((componentViewport?.height || 805) -
																		0 -
																		532) /
																		2) +
																0 +
																406 +
																0 +
																90 +
																0,
														),
														pixelHeight: 36,
														pixelWidth: 36,
														sizes: "36px",
														src: "https://framerusercontent.com/images/4tK9E3TjyRxSTIWEmHJWgYKDQY.svg?width=36&height=36",
													},
													onTap: onTapwgftql,
												},
												uYhzLTjBi: {
													background: {
														alt: "Icon",
														fit: "fill",
														loading: getLoadingLazyAtYPosition(
															(componentViewport?.y || 0) +
																(0 +
																	((componentViewport?.height || 572) -
																		0 -
																		572) /
																		2) +
																0 +
																446 +
																0 +
																90 +
																0,
														),
														pixelHeight: 36,
														pixelWidth: 36,
														sizes: "36px",
														src: "https://framerusercontent.com/images/4tK9E3TjyRxSTIWEmHJWgYKDQY.svg?width=36&height=36",
													},
													onTap: onTap1hq9rgt,
												},
												VDxAFIZpl: {
													background: {
														alt: "Icon",
														fit: "fill",
														loading: getLoadingLazyAtYPosition(
															(componentViewport?.y || 0) +
																(0 +
																	((componentViewport?.height || 200) -
																		0 -
																		532) /
																		2) +
																0 +
																406 +
																0 +
																90 +
																0,
														),
														pixelHeight: 36,
														pixelWidth: 36,
														sizes: "36px",
														src: "https://framerusercontent.com/images/4tK9E3TjyRxSTIWEmHJWgYKDQY.svg?width=36&height=36",
													},
													onTap: onTap3jdxvc,
												},
											},
											baseVariant,
											gestureVariant,
										)}
									/>
								</motion.div>
							</motion.div>
							<motion.div
								suppressHydrationWarning={true}
								className={"framer-15nin34"}
								data-framer-name={"Testimonial Content Wrapper"}
								layoutDependency={layoutDependency}
								layoutId={"oGVNxVbAB"}
							>
								<ComponentViewportProvider
									suppressHydrationWarning={true}
									height={376}
									width={`max(min(max((max(${componentViewport?.width || "100vw"}, 1px) - 10px) / 2, 1px), 662px), 1px)`}
									y={
										(componentViewport?.y || 0) +
										(0 + ((componentViewport?.height || 376) - 0 - 376) / 2) +
										0 +
										0 +
										0
									}
									{...addPropertyOverrides(
										{
											FW7nM1M9g: {
												width: "662px",
												y:
													(componentViewport?.y || 0) +
													(0 +
														((componentViewport?.height || 415) - 0 - 376) /
															2) +
													0 +
													0 +
													-0.7148,
											},
											Jkarm6NYz: {
												width: "662px",
												y:
													(componentViewport?.y || 0) +
													(0 +
														((componentViewport?.height || 415) - 0 - 376) /
															2) +
													0 +
													0 +
													-0.7148,
											},
											pKN98hdhU: {
												width: `max(min(max(${componentViewport?.width || "100vw"}, 1px), 662px), 1px)`,
												y:
													(componentViewport?.y || 0) +
													(0 +
														((componentViewport?.height || 805) - 0 - 532) /
															2) +
													0 +
													0 +
													0,
											},
											uYhzLTjBi: {
												width: `min(max(${componentViewport?.width || "100vw"}, 1px), 662px)`,
												y:
													(componentViewport?.y || 0) +
													(0 +
														((componentViewport?.height || 572) - 0 - 572) /
															2) +
													0 +
													0 +
													0,
											},
											VDxAFIZpl: {
												width: `min(max(${componentViewport?.width || "100vw"}, 1px), 662px)`,
												y:
													(componentViewport?.y || 0) +
													(0 +
														((componentViewport?.height || 200) - 0 - 532) /
															2) +
													0 +
													0 +
													0,
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<SmartComponentScopedContainer
										suppressHydrationWarning={true}
										className={"framer-dp1m58-container"}
										layoutDependency={layoutDependency}
										layoutId={"indGBAGBw-container"}
										nodeId={"indGBAGBw"}
										rendersWithMotion={true}
										scopeId={"tBrVeUFNs"}
										{...addPropertyOverrides(
											{
												FW7nM1M9g: {
													transformTemplate: transformTemplate1,
												},
												Jkarm6NYz: {
													transformTemplate: transformTemplate1,
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										{_jsx(stdin_default, {
											suppressHydrationWarning: true,
											B2pvC37F9: addImageAlt(
												{
													pixelHeight: 154,
													pixelWidth: 154,
													src: "https://framerusercontent.com/images/DGjSNMB1BIWkMxKap1Fw3Dvz1uA.png?width=154&height=154",
												},
												"Profile image",
											),
											bUnsOCPJF: "CEO, VunaChain",
											height: "100%",
											i_tVP08iy: "Mohammed A Alsayed",
											id: "indGBAGBw",
											layoutId: "indGBAGBw",
											style: {
												width: "100%",
											},
											unaRgGiHA:
												"Before Blimpy, our marketing spend was a complete black box. They rebuilt our tracking architecture from the ground up, integrating all our platforms into one reliable system so we finally know exactly which campaigns are driving revenue",
											width: "100%",
										})}
									</SmartComponentScopedContainer>
								</ComponentViewportProvider>
								<ComponentViewportProvider
									suppressHydrationWarning={true}
									height={376}
									width={`min(max((max(${componentViewport?.width || "100vw"}, 1px) - 10px) / 2, 1px), 662px)`}
									y={
										(componentViewport?.y || 0) +
										(0 + ((componentViewport?.height || 376) - 0 - 376) / 2) +
										0 +
										0 +
										0
									}
									{...addPropertyOverrides(
										{
											FW7nM1M9g: {
												width: `max(min(max((max(${componentViewport?.width || "100vw"}, 1px) - 10px) / 2, 1px), 662px), 1px)`,
												y:
													(componentViewport?.y || 0) +
													(0 +
														((componentViewport?.height || 415) - 0 - 376) /
															2) +
													0 +
													0 +
													0,
											},
											Jkarm6NYz: {
												y:
													(componentViewport?.y || 0) +
													(0 +
														((componentViewport?.height || 415) - 0 - 376) /
															2) +
													0 +
													0 +
													0,
											},
											pKN98hdhU: {
												width: `min(max(${componentViewport?.width || "100vw"}, 1px), 662px)`,
												y:
													(componentViewport?.y || 0) +
													(0 +
														((componentViewport?.height || 805) - 0 - 532) /
															2) +
													0 +
													0 +
													0,
											},
											uYhzLTjBi: {
												width: `min(max(${componentViewport?.width || "100vw"}, 1px), 662px)`,
												y:
													(componentViewport?.y || 0) +
													(0 +
														((componentViewport?.height || 572) - 0 - 572) /
															2) +
													0 +
													0 +
													0,
											},
											VDxAFIZpl: {
												width: `min(max(${componentViewport?.width || "100vw"}, 1px), 662px)`,
												y:
													(componentViewport?.y || 0) +
													(0 +
														((componentViewport?.height || 200) - 0 - 532) /
															2) +
													0 +
													0 +
													0,
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<SmartComponentScopedContainer
										suppressHydrationWarning={true}
										className={"framer-89d9dz-container"}
										layoutDependency={layoutDependency}
										layoutId={"AXNqzzRu2-container"}
										nodeId={"AXNqzzRu2"}
										rendersWithMotion={true}
										scopeId={"tBrVeUFNs"}
									>
										{_jsx(stdin_default, {
											suppressHydrationWarning: true,
											B2pvC37F9: addImageAlt(
												{
													pixelHeight: 128,
													pixelWidth: 128,
													src: "https://framerusercontent.com/images/JVW5GhwINTocQZTgn4vPooaHE.png?width=128&height=128",
												},
												"Image",
											),
											bUnsOCPJF: "Product Developer",
											height: "100%",
											i_tVP08iy: "Daniel Grayson",
											id: "AXNqzzRu2",
											layoutId: "AXNqzzRu2",
											style: {
												width: "100%",
											},
											unaRgGiHA:
												"Experience a bold fusion of heritage and high-tech design, shaping a limitless future for fashion tomorrow\u2019s fashion.",
											width: "100%",
											...addPropertyOverrides(
												{
													FW7nM1M9g: {
														bUnsOCPJF: "Chief Operations Officer",
														unaRgGiHA:
															"Blimpy eliminated our manual reporting bottlenecks by building tailored, real-time dashboards for our executive team. The clarity this brought is invaluable, allowing us to spend our time making strategic decisions rather than debating whose numbers are correct",
													},
												},
												baseVariant,
												gestureVariant,
											),
										})}
									</SmartComponentScopedContainer>
								</ComponentViewportProvider>
								<ComponentViewportProvider
									suppressHydrationWarning={true}
									height={376}
									width={`min(max((max(${componentViewport?.width || "100vw"}, 1px) - 10px) / 2, 1px), 662px)`}
									y={
										(componentViewport?.y || 0) +
										(0 + ((componentViewport?.height || 376) - 0 - 376) / 2) +
										0 +
										0 +
										0
									}
									{...addPropertyOverrides(
										{
											FW7nM1M9g: {
												y:
													(componentViewport?.y || 0) +
													(0 +
														((componentViewport?.height || 415) - 0 - 376) /
															2) +
													0 +
													0 +
													0,
											},
											Jkarm6NYz: {
												width: `max(min(max((max(${componentViewport?.width || "100vw"}, 1px) - 10px) / 2, 1px), 662px), 1px)`,
												y:
													(componentViewport?.y || 0) +
													(0 +
														((componentViewport?.height || 415) - 0 - 376) /
															2) +
													0 +
													0 +
													0,
											},
											pKN98hdhU: {
												width: `min(max(${componentViewport?.width || "100vw"}, 1px), 662px)`,
												y:
													(componentViewport?.y || 0) +
													(0 +
														((componentViewport?.height || 805) - 0 - 532) /
															2) +
													0 +
													0 +
													0,
											},
											uYhzLTjBi: {
												width: `min(max(${componentViewport?.width || "100vw"}, 1px), 662px)`,
												y:
													(componentViewport?.y || 0) +
													(0 +
														((componentViewport?.height || 572) - 0 - 572) /
															2) +
													0 +
													0 +
													0,
											},
											VDxAFIZpl: {
												width: `max(min(max(${componentViewport?.width || "100vw"}, 1px), 662px), 1px)`,
												y:
													(componentViewport?.y || 0) +
													(0 +
														((componentViewport?.height || 200) - 0 - 532) /
															2) +
													0 +
													0 +
													0,
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<SmartComponentScopedContainer
										suppressHydrationWarning={true}
										className={"framer-1yhiq8d-container"}
										layoutDependency={layoutDependency}
										layoutId={"ggyZayk6C-container"}
										nodeId={"ggyZayk6C"}
										rendersWithMotion={true}
										scopeId={"tBrVeUFNs"}
									>
										{_jsx(stdin_default, {
											suppressHydrationWarning: true,
											B2pvC37F9: addImageAlt(
												{
													pixelHeight: 128,
													pixelWidth: 128,
													src: "https://framerusercontent.com/images/AuyxBwUZ0oPMjSst7uDG1I0Dj4.png?width=128&height=128",
												},
												"Image",
											),
											bUnsOCPJF: "CEO & Founder",
											height: "100%",
											i_tVP08iy: "Michael Lawson",
											id: "ggyZayk6C",
											layoutId: "ggyZayk6C",
											style: {
												width: "100%",
											},
											unaRgGiHA:
												"Blending cultural roots with modern technology, we create fashion that pushes the edge of imagination unlock new creative dimensions.",
											width: "100%",
											...addPropertyOverrides(
												{
													Jkarm6NYz: {
														i_tVP08iy: "Beverly Senda",
														unaRgGiHA:
															"We used to rely heavily on intuition for our creative direction, but Blimpy shifted our approach by tethering our output directly to hard performance metrics. Their ongoing analysis pinpointed exactly where our funnel was leaking, significantly dropping our cost per lead",
													},
												},
												baseVariant,
												gestureVariant,
											),
										})}
									</SmartComponentScopedContainer>
								</ComponentViewportProvider>
							</motion.div>
						</motion.div>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css2 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-kfORU.framer-1ui40i9, .framer-kfORU .framer-1ui40i9 { display: block; }",
	".framer-kfORU.framer-12nsmg7 { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 1140px; }",
	".framer-kfORU .framer-17w7bd9 { align-content: flex-end; align-items: flex-end; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; height: min-content; justify-content: space-between; overflow: hidden; padding: 0px; position: relative; width: 1px; }",
	".framer-kfORU .framer-1j0qf9e { align-content: flex-start; align-items: flex-start; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 42px; height: min-content; justify-content: center; max-width: 250px; overflow: hidden; padding: 0px; position: relative; width: 1px; }",
	".framer-kfORU .framer-492kw6 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 15px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-kfORU .framer-r6zf38, .framer-kfORU .framer-pt0gdm, .framer-kfORU .framer-gemftp { aspect-ratio: 1 / 1; flex: none; gap: 0px; height: var(--framer-aspect-ratio-supported, 60px); overflow: hidden; position: relative; width: 60px; will-change: var(--framer-will-change-override, transform); }",
	".framer-kfORU .framer-3iax6t { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 47px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-kfORU .framer-16mxhei, .framer-kfORU .framer-am93m6 { cursor: pointer; flex: none; height: 36px; position: relative; width: 36px; }",
	".framer-kfORU .framer-unl5lv { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: min-content; }",
	".framer-kfORU .framer-o4gc0k { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-kfORU .framer-15nin34 { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; max-width: 662px; overflow: hidden; padding: 0px; position: relative; width: 1px; }",
	".framer-kfORU .framer-dp1m58-container { flex: 1 0 0px; height: auto; position: relative; width: 1px; }",
	".framer-kfORU .framer-89d9dz-container, .framer-kfORU .framer-1yhiq8d-container { flex: none; height: auto; position: absolute; right: -665px; top: 0px; width: 100%; z-index: 1; }",
	".framer-kfORU.framer-v-1om9vg2 .framer-dp1m58-container, .framer-kfORU.framer-v-8ty6mj .framer-dp1m58-container { flex: none; left: -665px; position: absolute; top: 50%; width: 662px; z-index: 1; }",
	".framer-kfORU.framer-v-1om9vg2 .framer-89d9dz-container, .framer-kfORU.framer-v-8ty6mj .framer-1yhiq8d-container, .framer-kfORU.framer-v-3nvegh .framer-1yhiq8d-container { flex: 1 0 0px; position: relative; right: unset; top: unset; width: 1px; }",
	".framer-kfORU.framer-v-8ty6mj .framer-89d9dz-container { left: -665px; right: unset; }",
	".framer-kfORU.framer-v-102cxdk.framer-12nsmg7, .framer-kfORU.framer-v-1o12xxq.framer-12nsmg7, .framer-kfORU.framer-v-3nvegh.framer-12nsmg7 { width: 350px; }",
	".framer-kfORU.framer-v-102cxdk .framer-17w7bd9, .framer-kfORU.framer-v-3nvegh .framer-17w7bd9 { align-content: center; align-items: center; flex-direction: column; gap: 30px; justify-content: center; }",
	".framer-kfORU.framer-v-102cxdk .framer-1j0qf9e, .framer-kfORU.framer-v-1o12xxq .framer-1j0qf9e, .framer-kfORU.framer-v-3nvegh .framer-1j0qf9e { flex: none; gap: 30px; order: 1; width: 100%; }",
	".framer-kfORU.framer-v-102cxdk .framer-15nin34, .framer-kfORU.framer-v-1o12xxq .framer-15nin34, .framer-kfORU.framer-v-3nvegh .framer-15nin34 { flex: none; order: 0; width: 100%; }",
	".framer-kfORU.framer-v-102cxdk .framer-89d9dz-container, .framer-kfORU.framer-v-102cxdk .framer-1yhiq8d-container, .framer-kfORU.framer-v-1o12xxq .framer-1yhiq8d-container { right: -360px; }",
	".framer-kfORU.framer-v-1o12xxq .framer-17w7bd9 { align-content: center; align-items: center; flex-direction: column; gap: 70px; justify-content: center; }",
	".framer-kfORU.framer-v-1o12xxq .framer-dp1m58-container, .framer-kfORU.framer-v-3nvegh .framer-dp1m58-container { flex: none; left: -360px; position: absolute; top: 0px; width: 100%; z-index: 1; }",
	".framer-kfORU.framer-v-1o12xxq .framer-89d9dz-container { position: relative; right: unset; top: unset; }",
	".framer-kfORU.framer-v-3nvegh .framer-89d9dz-container { left: -360px; right: unset; }",
	...css,
];
var FramertBrVeUFNs = withCSS(Component, css2, "framer-kfORU");
var stdin_default2 = FramertBrVeUFNs;
FramertBrVeUFNs.displayName = "Testimonial Slider";
FramertBrVeUFNs.defaultProps = {
	height: 376,
	width: 1140,
};
addPropertyControls(FramertBrVeUFNs, {
	variant: {
		options: [
			"d1YZz2RkZ",
			"FW7nM1M9g",
			"Jkarm6NYz",
			"pKN98hdhU",
			"uYhzLTjBi",
			"VDxAFIZpl",
		],
		optionTitles: [
			"Desktop 01",
			"Desktop 02",
			"Desktop 03",
			"Phone 01",
			"Phone 02",
			"Phone 03",
		],
		title: "Variant",
		type: ControlType.Enum,
	},
});
addFonts(
	FramertBrVeUFNs,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...TestimonialCardFonts,
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);
FramertBrVeUFNs.loader = {
	load: (props, context) => {
		const locale = context.locale;
		return Promise.allSettled([forwardLoader(stdin_default, {}, context)]);
	},
};

// virtual:testimonial-slider
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "pKN98hdhU",
	xl: "d1YZz2RkZ",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"1907350542b7624112d99063e9127837bac05866cdf3676335c1d928983f49a3"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				suppressHydrationWarning: true,
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders TestimonialSliderFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"1907350542b7624112d99063e9127837bac05866cdf3676335c1d928983f49a3"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				suppressHydrationWarning={true}
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var testimonial_slider_default = ComponentWithRoot;
export { testimonial_slider_default as default };
