// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 1907350542b76241 "Blimpy", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop 1' | 'Desktop 2' | 'Small' // Variant
 * image?: {src: string, srcSet?: string, alt?: string} // Image
 * number?: string // Number
 * onSvHml02b1Change?: any // onSvHml02b1Change
 * title?: string // Title
 * onlo8a8_BPXChange?: any // onlo8a8_BPXChange
 * categoryText1?: string // Category Text 1
 * onDHIbZALJOChange?: any // onDHIbZALJOChange
 * categoryText2?: string // Category Text 2
 * onaenoUMZBCCHange?: any // onaenoUMZBCCHange
 * categoryText3?: string // Category Text 3
 * onMrFkq96NwChange?: any // onMrFkq96NwChange
 * link?: string // Link
}} Props

 */
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-MVY5EKM2.js";
import { className, css, fonts } from "./chunks/chunk-RCFS46SR.js";
import { routes } from "./chunks/chunk-RHU4XTMM.js";

// virtual:work-card
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/hrNwRZ8eXwSTtYeen2aG/zmYzLkzAlLyE9WAXDRqi/D9SoZrrbA.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	Image,
	Link,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";

// /:https://framerusercontent.com/modules/tK9hDjWa7Qc4raz0Zq6p/lRSlBL3RRCgJRh2rKuCU/ykMXK3zQw.js
import { fontStore } from "unframer";
fontStore.loadFonts(["GF;Funnel Display-500", "GF;Funnel Display-700"]);
var fonts3 = [
	{
		explicitInter: true,
		fonts: [
			{
				family: "Funnel Display",
				openType: true,
				source: "google",
				style: "normal",
				url: "https://fonts.gstatic.com/s/funneldisplay/v2/B50bF7FGv37QNVWgE0ga--4PbZSRJXrOHcLHLoAYqGPXXcVwIZDKFA.woff2",
				weight: "500",
			},
			{
				family: "Funnel Display",
				openType: true,
				source: "google",
				style: "normal",
				url: "https://fonts.gstatic.com/s/funneldisplay/v2/B50bF7FGv37QNVWgE0ga--4PbZSRJXrOHcLHLoAYfWTXXcVwIZDKFA.woff2",
				weight: "700",
			},
		],
	},
];
var css3 = [
	`.framer-PbhA8 .framer-styles-preset-ik086a:not(.rich-text-wrapper), .framer-PbhA8 .framer-styles-preset-ik086a.rich-text-wrapper h5 { --framer-font-family: "Funnel Display", sans-serif; --framer-font-family-bold: "Funnel Display", sans-serif; --framer-font-open-type-features: 'blwf' on, 'cv09' on, 'cv03' on, 'cv04' on, 'cv11' on; --framer-font-size: 28px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-variation-axes: normal; --framer-font-weight: 500; --framer-font-weight-bold: 700; --framer-letter-spacing: -0.06em; --framer-line-height: 1.3em; --framer-paragraph-spacing: 40px; --framer-text-alignment: start; --framer-text-color: var(--token-1ca63064-b503-4f13-8e66-ff201796eaf9, #ffffff); --framer-text-decoration: underline; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; }`,
	`@media (max-width: 1199px) and (min-width: 810px) { .framer-PbhA8 .framer-styles-preset-ik086a:not(.rich-text-wrapper), .framer-PbhA8 .framer-styles-preset-ik086a.rich-text-wrapper h5 { --framer-font-family: "Funnel Display", sans-serif; --framer-font-family-bold: "Funnel Display", sans-serif; --framer-font-open-type-features: 'blwf' on, 'cv09' on, 'cv03' on, 'cv04' on, 'cv11' on; --framer-font-size: 28px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-variation-axes: normal; --framer-font-weight: 500; --framer-font-weight-bold: 700; --framer-letter-spacing: -0.06em; --framer-line-height: 1.3em; --framer-paragraph-spacing: 40px; --framer-text-alignment: start; --framer-text-color: var(--token-1ca63064-b503-4f13-8e66-ff201796eaf9, #ffffff); --framer-text-decoration: underline; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }`,
	`@media (max-width: 809px) and (min-width: 0px) { .framer-PbhA8 .framer-styles-preset-ik086a:not(.rich-text-wrapper), .framer-PbhA8 .framer-styles-preset-ik086a.rich-text-wrapper h5 { --framer-font-family: "Funnel Display", sans-serif; --framer-font-family-bold: "Funnel Display", sans-serif; --framer-font-open-type-features: 'blwf' on, 'cv09' on, 'cv03' on, 'cv04' on, 'cv11' on; --framer-font-size: 24px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-variation-axes: normal; --framer-font-weight: 500; --framer-font-weight-bold: 700; --framer-letter-spacing: -0.03em; --framer-line-height: 1.3em; --framer-paragraph-spacing: 40px; --framer-text-alignment: start; --framer-text-color: var(--token-1ca63064-b503-4f13-8e66-ff201796eaf9, #ffffff); --framer-text-decoration: underline; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }`,
];
var className3 = "framer-PbhA8";

// /:https://framerusercontent.com/modules/hrNwRZ8eXwSTtYeen2aG/zmYzLkzAlLyE9WAXDRqi/D9SoZrrbA.js
var enabledGestures = {
	CoHgJK7vv: {
		hover: true,
	},
	V7ogW0mgH: {
		hover: true,
	},
};
var cycleOrder = ["V7ogW0mgH", "CoHgJK7vv", "p5BPHk6Ho"];
var serializationHash = "framer-eouF8";
var variantClassNames = {
	CoHgJK7vv: "framer-v-1pxia8f",
	p5BPHk6Ho: "framer-v-1jv77x0",
	V7ogW0mgH: "framer-v-1ox8gmn",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	delay: 0,
	duration: 0.6,
	ease: [0.44, 0, 0.56, 1],
	type: "tween",
};
var toResponsiveImage = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider
			suppressHydrationWarning={true}
			value={contextValue}
		>
			{children}
		</MotionConfigContext.Provider>
	);
};
var humanReadableVariantMap = {
	"Desktop 1": "V7ogW0mgH",
	"Desktop 2": "CoHgJK7vv",
	Small: "p5BPHk6Ho",
};
var Variants = motion.create(React.Fragment);
var getProps = ({
	categoryText1,
	categoryText2,
	categoryText3,
	height,
	id,
	image,
	link,
	number,
	title,
	width,
	...props
}) => {
	return {
		...props,
		aenoUMZbC: categoryText2 ?? props.aenoUMZbC ?? "UI Design System",
		cRfL1IRRD: link ?? props.cRfL1IRRD,
		DHibZALJo: categoryText1 ?? props.DHibZALJo ?? "Data integration",
		jYC8bBCMU: image ??
			props.jYC8bBCMU ?? {
				alt: "Image",
				pixelHeight: 1424,
				pixelWidth: 1208,
				src: "https://framerusercontent.com/images/4OzNBdcz7osLcCx3bnM9StcZXEg.png?width=1208&height=1424",
				srcSet:
					"https://framerusercontent.com/images/4OzNBdcz7osLcCx3bnM9StcZXEg.png?scale-down-to=1024&width=1208&height=1424 868w,https://framerusercontent.com/images/4OzNBdcz7osLcCx3bnM9StcZXEg.png?width=1208&height=1424 1208w",
			},
		lo8a8_BPx: title ?? props.lo8a8_BPx ?? "Pana+Care TeleHealth App",
		MrFkq96Nw: categoryText3 ?? props.MrFkq96Nw ?? "Brand Guidelines",
		SvHml02b1: number ?? props.SvHml02b1 ?? "[ 01 ]",
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "V7ogW0mgH",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className4,
		layoutId,
		variant,
		jYC8bBCMU: jYC8bBCMU2,
		SvHml02b1: SvHml02b12,
		lo8a8_BPx: lo8a8_BPx2,
		DHibZALJo: DHibZALJo2,
		aenoUMZbC: aenoUMZbC2,
		MrFkq96Nw: MrFkq96Nw2,
		cRfL1IRRD: cRfL1IRRD2,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "V7ogW0mgH",
		enabledGestures,
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className, className3, className2];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup
			suppressHydrationWarning={true}
			id={layoutId ?? defaultLayoutId}
		>
			<Variants
				suppressHydrationWarning={true}
				animate={variants}
				initial={false}
			>
				<Transition suppressHydrationWarning={true} value={transition1}>
					<Link
						suppressHydrationWarning={true}
						href={cRfL1IRRD2}
						motionChild={true}
						nodeId={"V7ogW0mgH"}
						scopeId={"D9SoZrrbA"}
					>
						<motion.a
							suppressHydrationWarning={true}
							{...restProps}
							{...gestureHandlers}
							className={`${cx(scopingClassNames, "framer-1ox8gmn", className4, classNames)} framer-q3aimd`}
							data-framer-name={"Desktop 1"}
							layoutDependency={layoutDependency}
							layoutId={"V7ogW0mgH"}
							ref={refBinding}
							style={{
								...style,
							}}
							{...addPropertyOverrides(
								{
									"CoHgJK7vv-hover": {
										"data-framer-name": void 0,
									},
									"V7ogW0mgH-hover": {
										"data-framer-name": void 0,
									},
									CoHgJK7vv: {
										"data-framer-name": "Desktop 2",
									},
									p5BPHk6Ho: {
										"data-framer-name": "Small",
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<motion.div
								suppressHydrationWarning={true}
								className={"framer-bi03id"}
								data-framer-name={"Image & Number"}
								layoutDependency={layoutDependency}
								layoutId={"i6RBu6K0i"}
							>
								<RichText
									suppressHydrationWarning={true}
									__fromCanvasComponent={true}
									className={"framer-1rtlq5d"}
									data-framer-name={"[ 01 ]"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"dcEdPx52y"}
									style={{
										"--framer-paragraph-spacing": "0px",
									}}
									text={SvHml02b12}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.p
											suppressHydrationWarning={true}
											className={"framer-styles-preset-1me9qdm"}
											data-styles-preset={"DH9ENh_0Z"}
										>
											{"[ 01 ]"}
										</motion.p>
									</React.Fragment>
								</RichText>
								<motion.div
									suppressHydrationWarning={true}
									className={"framer-a4jrie"}
									data-framer-name={"Image Wrapper"}
									layoutDependency={layoutDependency}
									layoutId={"CyrvOEJLL"}
								>
									<Image
										suppressHydrationWarning={true}
										background={{
											alt: "Image",
											fit: "fill",
											pixelHeight: 1424,
											pixelWidth: 1208,
											sizes: componentViewport?.width || "100vw",
											...toResponsiveImage(jYC8bBCMU2),
										}}
										className={"framer-1j9w9y7"}
										layoutDependency={layoutDependency}
										layoutId={"zYofEFant"}
										style={{
											filter: "none",
											rotate: 0,
											scale: 1,
											WebkitFilter: "none",
										}}
										variants={{
											"CoHgJK7vv-hover": {
												filter: "blur(7px)",
												rotate: 3,
												scale: 1.2,
												WebkitFilter: "blur(7px)",
											},
											"V7ogW0mgH-hover": {
												filter: "blur(7px)",
												rotate: 3,
												scale: 1.2,
												WebkitFilter: "blur(7px)",
											},
										}}
									/>
								</motion.div>
							</motion.div>
							<motion.div
								suppressHydrationWarning={true}
								className={"framer-dfgoxz"}
								data-framer-name={"TItle"}
								layoutDependency={layoutDependency}
								layoutId={"DDEriTlzC"}
							>
								<RichText
									suppressHydrationWarning={true}
									__fromCanvasComponent={true}
									className={"framer-yi0whe"}
									data-framer-name={"Pana+Care TeleHealth App"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"DkhqDBG8t"}
									style={{
										"--framer-paragraph-spacing": "0px",
									}}
									text={lo8a8_BPx2}
									variants={{
										"CoHgJK7vv-hover": {
											"--extracted-1lwpl3i":
												"var(--token-d0efb30f-1ca4-4318-a615-3c27c4e89f33, rgb(255, 31, 0))",
										},
										"V7ogW0mgH-hover": {
											"--extracted-1lwpl3i":
												"var(--token-d0efb30f-1ca4-4318-a615-3c27c4e89f33, rgb(255, 31, 0))",
										},
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
									{...addPropertyOverrides(
										{
											"CoHgJK7vv-hover": {
												children: (
													<React.Fragment>
														<motion.h5
															suppressHydrationWarning={true}
															className={"framer-styles-preset-ik086a"}
															data-styles-preset={"ykMXK3zQw"}
															style={{
																"--framer-text-color":
																	"var(--extracted-1lwpl3i, var(--token-d0efb30f-1ca4-4318-a615-3c27c4e89f33, rgb(255, 31, 0)))",
															}}
														>
															{"Echo Bank Identity"}
														</motion.h5>
													</React.Fragment>
												),
											},
											"V7ogW0mgH-hover": {
												children: (
													<React.Fragment>
														<motion.h5
															suppressHydrationWarning={true}
															className={"framer-styles-preset-ik086a"}
															data-styles-preset={"ykMXK3zQw"}
															style={{
																"--framer-text-color":
																	"var(--extracted-1lwpl3i, var(--token-d0efb30f-1ca4-4318-a615-3c27c4e89f33, rgb(255, 31, 0)))",
															}}
														>
															{"Echo Bank Identity"}
														</motion.h5>
													</React.Fragment>
												),
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<React.Fragment>
										<motion.h5
											suppressHydrationWarning={true}
											className={"framer-styles-preset-ik086a"}
											data-styles-preset={"ykMXK3zQw"}
										>
											{"Echo Bank Identity"}
										</motion.h5>
									</React.Fragment>
								</RichText>
								<motion.div
									suppressHydrationWarning={true}
									className={"framer-1gbfvf2"}
									data-framer-name={"Service Category"}
									layoutDependency={layoutDependency}
									layoutId={"iAfzJa5xj"}
								>
									<RichText
										suppressHydrationWarning={true}
										__fromCanvasComponent={true}
										className={"framer-am2ath"}
										data-framer-name={"Logo & Visuals"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"Crpz43kUt"}
										style={{
											"--framer-paragraph-spacing": "0px",
										}}
										text={DHibZALJo2}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												suppressHydrationWarning={true}
												className={"framer-styles-preset-ju9k6k"}
												data-styles-preset={"yMD2hLIXl"}
											>
												{"Logo & Visuals"}
											</motion.p>
										</React.Fragment>
									</RichText>
									<motion.div
										suppressHydrationWarning={true}
										className={"framer-16nf68g"}
										data-framer-name={"Dot"}
										layoutDependency={layoutDependency}
										layoutId={"lbTbY6dAl"}
										style={{
											backgroundColor:
												"var(--token-1d0bdbdf-77ee-49c5-8a71-83b65bfd3f49, rgb(217, 217, 217))",
											borderBottomLeftRadius: "100%",
											borderBottomRightRadius: "100%",
											borderTopLeftRadius: "100%",
											borderTopRightRadius: "100%",
										}}
									/>
									<RichText
										suppressHydrationWarning={true}
										__fromCanvasComponent={true}
										className={"framer-1j3tje4"}
										data-framer-name={"UI Design System"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"ruQr7JLnL"}
										style={{
											"--framer-paragraph-spacing": "0px",
										}}
										text={aenoUMZbC2}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												suppressHydrationWarning={true}
												className={"framer-styles-preset-ju9k6k"}
												data-styles-preset={"yMD2hLIXl"}
											>
												{"UI Design System"}
											</motion.p>
										</React.Fragment>
									</RichText>
									<motion.div
										suppressHydrationWarning={true}
										className={"framer-1us6toj"}
										data-framer-name={"Dot"}
										layoutDependency={layoutDependency}
										layoutId={"emX3agDMl"}
										style={{
											backgroundColor:
												"var(--token-1d0bdbdf-77ee-49c5-8a71-83b65bfd3f49, rgb(217, 217, 217))",
											borderBottomLeftRadius: "100%",
											borderBottomRightRadius: "100%",
											borderTopLeftRadius: "100%",
											borderTopRightRadius: "100%",
										}}
									/>
									<RichText
										suppressHydrationWarning={true}
										__fromCanvasComponent={true}
										className={"framer-feib1i"}
										data-framer-name={"Brand Guidelines"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"QANrlXERV"}
										style={{
											"--framer-paragraph-spacing": "0px",
										}}
										text={MrFkq96Nw2}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												suppressHydrationWarning={true}
												className={"framer-styles-preset-ju9k6k"}
												data-styles-preset={"yMD2hLIXl"}
											>
												{"Brand Guidelines"}
											</motion.p>
										</React.Fragment>
									</RichText>
								</motion.div>
							</motion.div>
						</motion.a>
					</Link>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css4 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-eouF8.framer-q3aimd, .framer-eouF8 .framer-q3aimd { display: block; }",
	".framer-eouF8.framer-1ox8gmn { align-content: flex-start; align-items: flex-start; cursor: pointer; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 30px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; text-decoration: none; width: 604px; }",
	".framer-eouF8 .framer-bi03id { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 4px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-eouF8 .framer-1rtlq5d, .framer-eouF8 .framer-yi0whe { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-eouF8 .framer-a4jrie { align-content: center; align-items: center; aspect-ratio: 0.848314606741573 / 1; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: var(--framer-aspect-ratio-supported, 712px); justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-eouF8 .framer-1j9w9y7 { flex: none; height: 100%; left: calc(50.00000000000002% - 100% / 2); position: absolute; top: calc(50.00000000000002% - 100% / 2); width: 100%; z-index: 1; }",
	".framer-eouF8 .framer-dfgoxz { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 18px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-eouF8 .framer-1gbfvf2 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: wrap; gap: 17px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-eouF8 .framer-am2ath, .framer-eouF8 .framer-1j3tje4, .framer-eouF8 .framer-feib1i { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-eouF8 .framer-16nf68g, .framer-eouF8 .framer-1us6toj { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 5px); position: relative; width: 5px; }",
	".framer-eouF8.framer-v-1pxia8f .framer-a4jrie, .framer-eouF8.framer-v-1jv77x0 .framer-a4jrie { aspect-ratio: 1.1001821493624773 / 1; height: var(--framer-aspect-ratio-supported, 549px); }",
	".framer-eouF8.framer-v-1jv77x0 .framer-dfgoxz { gap: 12px; }",
	".framer-eouF8.framer-v-1jv77x0 .framer-1gbfvf2 { gap: 12px 12px; }",
	...css,
	...css3,
	...css2,
];
var FramerD9SoZrrbA = withCSS(Component, css4, "framer-eouF8");
var stdin_default = FramerD9SoZrrbA;
FramerD9SoZrrbA.displayName = "Work Card";
FramerD9SoZrrbA.defaultProps = {
	height: 850,
	width: 604,
};
addPropertyControls(FramerD9SoZrrbA, {
	variant: {
		options: ["V7ogW0mgH", "CoHgJK7vv", "p5BPHk6Ho"],
		optionTitles: ["Desktop 1", "Desktop 2", "Small"],
		title: "Variant",
		type: ControlType.Enum,
	},
	jYC8bBCMU: {
		__defaultAssetReference:
			"data:framer/asset-reference,4OzNBdcz7osLcCx3bnM9StcZXEg.png?originalFilename=Frame+4+%282%29.png&preferredSize=auto",
		__vekterDefault: {
			alt: "Image",
			assetReference:
				"data:framer/asset-reference,4OzNBdcz7osLcCx3bnM9StcZXEg.png?originalFilename=Frame+4+%282%29.png&preferredSize=auto",
		},
		title: "Image",
		type: ControlType.ResponsiveImage,
	},
	SvHml02b1: {
		defaultValue: "[ 01 ]",
		displayTextArea: false,
		title: "Number",
		type: ControlType.String,
	},
	onSvHml02b1Change: {
		changes: "SvHml02b1",
		type: ControlType.ChangeHandler,
	},
	lo8a8_BPx: {
		defaultValue: "Pana+Care TeleHealth App",
		displayTextArea: false,
		title: "Title",
		type: ControlType.String,
	},
	onlo8a8_BPxChange: {
		changes: "lo8a8_BPx",
		type: ControlType.ChangeHandler,
	},
	DHibZALJo: {
		defaultValue: "Data integration",
		displayTextArea: false,
		title: "Category Text 1",
		type: ControlType.String,
	},
	onDHibZALJoChange: {
		changes: "DHibZALJo",
		type: ControlType.ChangeHandler,
	},
	aenoUMZbC: {
		defaultValue: "UI Design System",
		displayTextArea: false,
		title: "Category Text 2",
		type: ControlType.String,
	},
	onaenoUMZbCChange: {
		changes: "aenoUMZbC",
		type: ControlType.ChangeHandler,
	},
	MrFkq96Nw: {
		defaultValue: "Brand Guidelines",
		displayTextArea: false,
		title: "Category Text 3",
		type: ControlType.String,
	},
	onMrFkq96NwChange: {
		changes: "MrFkq96Nw",
		type: ControlType.ChangeHandler,
	},
	cRfL1IRRD: {
		title: "Link",
		type: ControlType.Link,
	},
});
addFonts(
	FramerD9SoZrrbA,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts),
		...getFontsFromSharedStyle(fonts3),
		...getFontsFromSharedStyle(fonts2),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:work-card
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "p5BPHk6Ho",
	xl: "CoHgJK7vv",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"1907350542b7624112d99063e9127837bac05866cdf3676335c1d928983f49a3"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				suppressHydrationWarning: true,
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders WorkCardFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"1907350542b7624112d99063e9127837bac05866cdf3676335c1d928983f49a3"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				suppressHydrationWarning={true}
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var work_card_default = ComponentWithRoot;
export { work_card_default as default };
